### ISSUE TITLE
Disable Searchkick in Selenium Tests does not work

### ISSUE THREAD

**Issue by philippneugebauer** [ankane/searchkick#1031]
I was searching for a solution to deactivate `Searchkick` in my tests and found the following solution: `Searchkick.disable_callbacks`

Unfortunately, while it was fixing all my unit tests with minitest, the selenium tests still fail with the same message as before. Adding `Searchkick.disable_callbacks` to the `integration_test_helper` or even directly to the `test method` didn't help at all.

My error message:

```
Faraday::ConnectionFailed: Failed to open TCP connection to localhost:9200 (Connection refused - connect(2) for "localhost" port 9200)
```

My `test_helper.rb`:
```
ENV['RAILS_ENV'] ||= 'test'
require File.expand_path('../../config/environment', __FILE__)
require 'rails/test_help'
require 'simplecov'
require 'minitest/reporters'

Searchkick.disable_callbacks
SimpleCov.start

reporter_options = { color: true }
Minitest::Reporters.use! [Minitest::Reporters::DefaultReporter.new(reporter_options)]

class ActiveSupport::TestCase
  ActiveRecord::Migration.check_pending!

  fixtures :all
end
```

My `integration_test_helper.rb`:
```
require 'test_helper'
require 'capybara/dsl'
require 'capybara/rails'
require 'capybara/minitest'
require 'selenium-webdriver'
require 'capybara-screenshot/minitest'

Chromedriver.set_version '2.33'
Capybara.default_driver = :selenium_chrome_headless

class ActionDispatch::IntegrationTest
  # Make the Capybara DSL available in all integration tests
  include Capybara::DSL
  # Make `assert_*` methods behave like Minitest assertions
  include Capybara::Minitest::Assertions
  #include Capybara::Screenshot::MiniTestPlugin

  # Reset sessions and driver between tests
  # Use super wherever this method is redefined in your individual test classes
  def teardown
    Capybara.reset_sessions!
    Capybara.use_default_driver
  end
end
```

Did I do anything wrong or is this a possible bug?

**Comment by ankane** [comment]
Hey @philippneugebauer, can you paste the full stack trace for the exception?

**Comment by philippneugebauer** [comment]
```
Error:
IntegrationTest#test:
Faraday::ConnectionFailed: Failed to open TCP connection to localhost:9200 (Connection refused - connect(2) for "localhost" port 9200)
    /Users/ppn/.rbenv/versions/2.3.3/lib/ruby/2.3.0/net/http.rb:882:in `rescue in block in connect'
    /Users/ppn/.rbenv/versions/2.3.3/lib/ruby/2.3.0/net/http.rb:879:in `block in connect'
    /Users/ppn/.rbenv/versions/2.3.3/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
    /Users/ppn/.rbenv/versions/2.3.3/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
    /Users/ppn/.rbenv/versions/2.3.3/lib/ruby/2.3.0/net/http.rb:878:in `connect'
    /Users/ppn/.rbenv/versions/2.3.3/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
    /Users/ppn/.rbenv/versions/2.3.3/lib/ruby/2.3.0/net/http.rb:852:in `start'
    /Users/ppn/.rbenv/versions/2.3.3/lib/ruby/2.3.0/net/http.rb:1398:in `request'
    rack-mini-profiler (0.10.6) lib/patches/net_patches.rb:7:in `block in request_with_mini_profiler'
    rack-mini-profiler (0.10.6) lib/mini_profiler/profiling_methods.rb:37:in `step'
    rack-mini-profiler (0.10.6) lib/patches/net_patches.rb:6:in `request_with_mini_profiler'
    faraday (0.12.2) lib/faraday/adapter/net_http.rb:80:in `perform_request'
    faraday (0.12.2) lib/faraday/adapter/net_http.rb:38:in `block in call'
    faraday (0.12.2) lib/faraday/adapter/net_http.rb:85:in `with_net_http_connection'
    faraday (0.12.2) lib/faraday/adapter/net_http.rb:33:in `call'
    searchkick (2.3.2) lib/searchkick/middleware.rb:9:in `call'
    faraday (0.12.2) lib/faraday/rack_builder.rb:141:in `build_response'
    faraday (0.12.2) lib/faraday/connection.rb:386:in `run_request'
    elasticsearch-transport (5.0.4) lib/elasticsearch/transport/transport/http/faraday.rb:23:in `block in perform_request'
    elasticsearch-transport (5.0.4) lib/elasticsearch/transport/transport/base.rb:262:in `perform_request'
    elasticsearch-transport (5.0.4) lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
    elasticsearch-transport (5.0.4) lib/elasticsearch/transport/client.rb:131:in `perform_request'
    elasticsearch-api (5.0.4) lib/elasticsearch/api/actions/bulk.rb:95:in `bulk'
    searchkick (2.3.2) lib/searchkick/indexer.rb:18:in `perform'
    searchkick (2.3.2) lib/searchkick/logging.rb:126:in `perform'
    searchkick (2.3.2) lib/searchkick/indexer.rb:11:in `queue'
    searchkick (2.3.2) lib/searchkick/index.rb:527:in `bulk_index_helper'
    searchkick (2.3.2) lib/searchkick/index.rb:78:in `store'
    searchkick (2.3.2) lib/searchkick/logging.rb:28:in `block in store'
    activesupport (5.1.4) lib/active_support/notifications.rb:166:in `block in instrument'
    activesupport (5.1.4) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
    activesupport (5.1.4) lib/active_support/notifications.rb:166:in `instrument'
    searchkick (2.3.2) lib/searchkick/logging.rb:27:in `store'
    searchkick (2.3.2) lib/searchkick/index.rb:128:in `reindex_record'
    searchkick (2.3.2) lib/searchkick/model.rb:125:in `reindex'
    activesupport (5.1.4) lib/active_support/callbacks.rb:413:in `block in make_lambda'
    activesupport (5.1.4) lib/active_support/callbacks.rb:260:in `block in conditional'
    activesupport (5.1.4) lib/active_support/callbacks.rb:511:in `block in invoke_after'
    activesupport (5.1.4) lib/active_support/callbacks.rb:511:in `each'
    activesupport (5.1.4) lib/active_support/callbacks.rb:511:in `invoke_after'
    activesupport (5.1.4) lib/active_support/callbacks.rb:132:in `run_callbacks'
    activesupport (5.1.4) lib/active_support/callbacks.rb:827:in `_run_commit_callbacks'
    activerecord (5.1.4) lib/active_record/transactions.rb:343:in `committed!'
    activerecord (5.1.4) lib/active_record/connection_adapters/abstract/transaction.rb:86:in `commit_records'
    activerecord (5.1.4) lib/active_record/connection_adapters/abstract/transaction.rb:178:in `block in commit_transaction'
    /Users/ppn/.rbenv/versions/2.3.3/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
    activerecord (5.1.4) lib/active_record/connection_adapters/abstract/transaction.rb:168:in `commit_transaction'
    activerecord (5.1.4) lib/active_record/connection_adapters/abstract/transaction.rb:207:in `block in within_new_transaction'
    /Users/ppn/.rbenv/versions/2.3.3/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
    activerecord (5.1.4) lib/active_record/connection_adapters/abstract/transaction.rb:191:in `within_new_transaction'
    activerecord (5.1.4) lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `transaction'
    activerecord (5.1.4) lib/active_record/transactions.rb:210:in `transaction'
    activerecord (5.1.4) lib/active_record/transactions.rb:381:in `with_transaction_returning_status'
    activerecord (5.1.4) lib/active_record/transactions.rb:308:in `block in save'
    activerecord (5.1.4) lib/active_record/transactions.rb:323:in `rollback_active_record_state!'
    activerecord (5.1.4) lib/active_record/transactions.rb:307:in `save'
    activerecord (5.1.4) lib/active_record/suppressor.rb:42:in `save'
    app/controllers/projects_controller.rb:61:in `block in create_basic_info'
    actionpack (5.1.4) lib/action_controller/metal/mime_responds.rb:195:in `respond_to'
    app/controllers/projects_controller.rb:60:in `create_basic_info'
    actionpack (5.1.4) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
    actionpack (5.1.4) lib/abstract_controller/base.rb:186:in `process_action'
    actionpack (5.1.4) lib/action_controller/metal/rendering.rb:30:in `process_action'
    actionpack (5.1.4) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
    activesupport (5.1.4) lib/active_support/callbacks.rb:131:in `run_callbacks'
    actionpack (5.1.4) lib/abstract_controller/callbacks.rb:19:in `process_action'
    actionpack (5.1.4) lib/action_controller/metal/rescue.rb:20:in `process_action'
    actionpack (5.1.4) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
    activesupport (5.1.4) lib/active_support/notifications.rb:166:in `block in instrument'
    activesupport (5.1.4) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
    activesupport (5.1.4) lib/active_support/notifications.rb:166:in `instrument'
    actionpack (5.1.4) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
    actionpack (5.1.4) lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
    searchkick (2.3.2) lib/searchkick/logging.rb:209:in `process_action'
    activerecord (5.1.4) lib/active_record/railties/controller_runtime.rb:22:in `process_action'
    actionpack (5.1.4) lib/abstract_controller/base.rb:124:in `process'
    actionview (5.1.4) lib/action_view/rendering.rb:30:in `process'
    rack-mini-profiler (0.10.6) lib/mini_profiler/profiling_methods.rb:76:in `block in profile_method'
    actionpack (5.1.4) lib/action_controller/metal.rb:189:in `dispatch'
    actionpack (5.1.4) lib/action_controller/metal.rb:253:in `dispatch'
    actionpack (5.1.4) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
    actionpack (5.1.4) lib/action_dispatch/routing/route_set.rb:31:in `serve'
    actionpack (5.1.4) lib/action_dispatch/journey/router.rb:50:in `block in serve'
    actionpack (5.1.4) lib/action_dispatch/journey/router.rb:33:in `each'
    actionpack (5.1.4) lib/action_dispatch/journey/router.rb:33:in `serve'
    actionpack (5.1.4) lib/action_dispatch/routing/route_set.rb:834:in `call'
    simple_captcha2 (0.4.3) lib/simple_captcha/middleware.rb:47:in `call'
    rack (2.0.3) lib/rack/etag.rb:25:in `call'
    rack (2.0.3) lib/rack/conditional_get.rb:38:in `call'
    rack (2.0.3) lib/rack/head.rb:12:in `call'
    rack (2.0.3) lib/rack/session/abstract/id.rb:232:in `context'
    rack (2.0.3) lib/rack/session/abstract/id.rb:226:in `call'
    actionpack (5.1.4) lib/action_dispatch/middleware/cookies.rb:613:in `call'
    actionpack (5.1.4) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
    activesupport (5.1.4) lib/active_support/callbacks.rb:97:in `run_callbacks'
    actionpack (5.1.4) lib/action_dispatch/middleware/callbacks.rb:24:in `call'
    rollbar (2.15.5) lib/rollbar/middleware/rails/rollbar.rb:24:in `block in call'
    rollbar (2.15.5) lib/rollbar.rb:145:in `scoped'
    rollbar (2.15.5) lib/rollbar/middleware/rails/rollbar.rb:22:in `call'
    actionpack (5.1.4) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
    rollbar (2.15.5) lib/rollbar/middleware/rails/show_exceptions.rb:22:in `call_with_rollbar'
    actionpack (5.1.4) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
    railties (5.1.4) lib/rails/rack/logger.rb:36:in `call_app'
    railties (5.1.4) lib/rails/rack/logger.rb:24:in `block in call'
    activesupport (5.1.4) lib/active_support/tagged_logging.rb:69:in `block in tagged'
    activesupport (5.1.4) lib/active_support/tagged_logging.rb:26:in `tagged'
    activesupport (5.1.4) lib/active_support/tagged_logging.rb:69:in `tagged'
    railties (5.1.4) lib/rails/rack/logger.rb:24:in `call'
    actionpack (5.1.4) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
    actionpack (5.1.4) lib/action_dispatch/middleware/request_id.rb:25:in `call'
    rack (2.0.3) lib/rack/method_override.rb:22:in `call'
    rack (2.0.3) lib/rack/runtime.rb:22:in `call'
    activesupport (5.1.4) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
    actionpack (5.1.4) lib/action_dispatch/middleware/executor.rb:12:in `call'
    actionpack (5.1.4) lib/action_dispatch/middleware/static.rb:125:in `call'
    rack (2.0.3) lib/rack/sendfile.rb:111:in `call'
    rack-mini-profiler (0.10.6) lib/mini_profiler/profiler.rb:171:in `call'
    railties (5.1.4) lib/rails/engine.rb:522:in `call'
    rack (2.0.3) lib/rack/urlmap.rb:68:in `block in call'
    rack (2.0.3) lib/rack/urlmap.rb:53:in `each'
    rack (2.0.3) lib/rack/urlmap.rb:53:in `call'
    capybara (2.16.0) lib/capybara/server.rb:44:in `call'
    rack (2.0.3) lib/rack/handler/webrick.rb:86:in `service'
    /Users/ppn/.rbenv/versions/2.3.3/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
    /Users/ppn/.rbenv/versions/2.3.3/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
    /Users/ppn/.rbenv/versions/2.3.3/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
```

**Comment by ankane** [comment]
Thanks @philippneugebauer. One thing to check is if it's using a different thread, as `Searchkick.disable_callbacks` only affects the current thread for thread-safety. You can check this by printing `Thread.current.object_id` before the `Searchkick.disable_callbacks` and in your ProjectsController before the line that's throwing the error.

**Comment by philippneugebauer** [comment]
Unfortunately, it's the same:

```
$ rails test
Thread_id 70341301107220

# Running tests with run options --seed 31745:

.Thread_id 70341301107220
```

**Comment by ankane** [comment]
Can you also try printing `Thread.current[:searchkick_callbacks_enabled]`?

**Comment by philippneugebauer** [comment]
Sure:

```
$ rails test
Thread_id 70171100445220
Thread_callbacks

# Running tests with run options --seed 14775:

Thread_id 70171100445220
Thread_callbacks false
```

It seems like it doesn't have a value in the helper code, but it's `false` for the test

**Comment by ankane** [comment]
Here's the relevant code: https://github.com/ankane/searchkick/blob/9e2e074b1a04b5ca25e282bef5eb312faf276617/lib/searchkick/model.rb#L84

If `Project.searchkick_callbacks?` is false, then it seems like the `if` conditional is getting ignored.

**Comment by philippneugebauer** [comment]
I can confirm that, but still all the values are false

```
  test 'create visible published project' do
    puts "all: #{Thread.current[:searchkick_callbacks_enabled]}"
    puts "project: #{Project.search_callbacks?}"
    #Selenium starts
    puts "all: #{Thread.current[:searchkick_callbacks_enabled]}"
    puts "project: #{Project.search_callbacks?}"
end
```

```
        if respond_to?(:after_commit)
          puts "all_callbacks: #{Thread.current[:searchkick_callbacks_enabled]}"
          puts "project_callback: #{Project.search_callbacks?}"
          puts "test" if proc { self.class.search_callbacks? }
          after_commit callback_name, if: proc { self.class.search_callbacks? }
```
leads to the following output:

```
all_callbacks: false
project_callback: false
test
all_callbacks: false
project_callback: false
test
all_callbacks: false
project_callback: false
test
all: false
project: false
all: false
project: false
```

It feels like the proc check does not work.

**Comment by philippneugebauer** [comment]
I was able to disable the callbacks with the following code, but I don't really like that approach:

```
searchkick callbacks: !Rails.env.test?
```

**Comment by ankane** [comment]
It's very strange that would work but the other one wouldn't (as both use the `after_commit` conditional). You could try reproducing with a fresh Rails app. I don't have any other ideas right now, so will wait to see if others have the same issue.

**Comment by treznick** [comment]
Hi, I think we're having the same issue, but with rspec and capybara. From what I can tell it looks like the appropriate class variable on the model is not being set to false to disable callbacks. This might be a red herring to this issue, so if you'd prefer I'm happy to open another ticket.

When wrapping the offending spec (really all specs) in `Searchkick.disable_callbacks` and then `Searchkick.enable_callbacks`, the offending feature spec still tries to hit elasticsearch (which I know because the ES client is blowing up because we do some `Timecop`ing in this spec... anyway...).

Here's the offending spec. NB: some of the names have been changed to protect the innocent
```ruby
Timecop.travel(datetime) do
  Searchkick.disable_callbacks
  perform_enqueued_jobs do
    authenticate(user) do
      visit "/dashboard"
      click_on "Button"
      expect(page).to have_content("result")
    end
  end
  Searchkick.enable_callbacks
end
```

That blows up because the elasticsearch instance returns with a 403 because the current timestamp is now earlier than the signature expiry date:
```ruby
Elasticsearch::Transport::Transport::Errors::Forbidden:
       [403] {"message":"Signature expired: 20171206T012122Z is now earlier than 20171222T150120Z (20171222T150620Z - 5 min.)"}
```

When I put a `byebug` before the click action, I can confirm that `Thread.current[:searchkick_callbacks_enabled]` is `false`

But when I ask the model that is being indexed what the value of `@@searchkick_callbacks` (and this is *the only* model we use searchkick on, so there's no chance it's the wrong class variable), I get `:async`, as it's been configured in the model:
```ruby
class MyModel < ApplicationRecord
  searchkick callbacks: :async
end
```

The spec passes without the 403 from ES if instead of `Searchkick.disable_callbacks` I do this:
```ruby
Timecop.travel(datetime) do
  old_val = MyModel.class_variable_get(:@@searchkick_callbacks)
  MyModel.class_variable_set(:@@searchkick_callbacks, false)
  perform_enqueued_jobs do
    authenticate(user) do
      visit "/dashboard"
      click_on "Button"
      expect(page).to have_content("result")
    end
  end
  MyModel.class_variable_set(:@@searchkick_callbacks, old_val)
end
```

Anyway, I hope this helps. If this is not the issue, and you would prefer a separate issue, please let me know. Also thanks again for building this. It's a great gem!

**Comment by treznick** [comment]
ok, so, ignore most of my previous comment. Spent some time debugging and it looks like it is indeed that `Thread.current[:searchkick_callbacks_enabled]` is being set to `nil` in the thread that the feature spec is being run.

**Comment by ankane** [comment]
Seems like the solution is to make sure `Searchkick.disable_callbacks` is called in the same thread.

**Comment by cars10** [comment]
And hints on how to do that? We have the same problem with system tests in Rails 5.1.6.
