### ISSUE TITLE
Reindexing model causes Stack Level Too Deep infinite loop

### ISSUE THREAD

**Issue by casto101** [ankane/searchkick#1076]
When trying to call `Product.reindex` I'm hitting an infinite loop. From some digging in the stack trace, it appears that this happens when calling `__bulkify` in the `elasticsearch-api` gem. We're experiencing this after upgrading from an older version to searchkick 2.4.0 to support Elasticsearch 6.1. We have custom mapping, but the mapping have already been updated to the most recent syntax, and commenting out the custom mapping doesn't seem to prevent this error anyway. We were able to upgrade other models to the new syntax and index them without issue. Has anyone seen this issue before? Any thoughts or guidance would be greatly appreciated!

```
# This goes on for a long time, 'each' to 'block in as_json' repeats

# /Users/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5.1/lib/active_support/core_ext/object/json.rb:159:in `each'
# /Users/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5.1/lib/active_support/core_ext/object/json.rb:159:in `map'
# /Users/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5.1/lib/active_support/core_ext/object/json.rb:159:in `as_json'
# /Users/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5.1/lib/active_support/core_ext/object/json.rb:159:in `block in as_json'
# /Users/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5.1/lib/active_support/core_ext/object/json.rb:159:in `each'
# /Users/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5.1/lib/active_support/core_ext/object/json.rb:159:in `map'
# /Users/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5.1/lib/active_support/core_ext/object/json.rb:159:in `as_json'
# /Users/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5.1/lib/active_support/json/encoding.rb:35:in `encode'
# /Users/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5.1/lib/active_support/json/encoding.rb:22:in `encode'
# /Users/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5.1/lib/active_support/core_ext/object/json.rb:37:in `to_json_with_active_support_encoder'
# /Users/.rvm/gems/ruby-2.3.0/gems/multi_json-1.13.1/lib/multi_json/adapters/json_common.rb:19:in `dump'
# /Users/.rvm/gems/ruby-2.3.0/gems/multi_json-1.13.1/lib/multi_json/adapter.rb:25:in `dump'
# /Users/.rvm/gems/ruby-2.3.0/gems/multi_json-1.13.1/lib/multi_json.rb:139:in `dump'
# /Users/.rvm/gems/ruby-2.3.0/gems/elasticsearch-api-6.0.1/lib/elasticsearch/api/utils.rb:100:in `block in __bulkify'
# /Users/.rvm/gems/ruby-2.3.0/gems/elasticsearch-api-6.0.1/lib/elasticsearch/api/utils.rb:100:in `map'
# /Users/.rvm/gems/ruby-2.3.0/gems/elasticsearch-api-6.0.1/lib/elasticsearch/api/utils.rb:100:in `__bulkify'
# /Users/.rvm/gems/ruby-2.3.0/gems/elasticsearch-api-6.0.1/lib/elasticsearch/api/actions/bulk.rb:90:in `bulk'
# /Users/.rvm/gems/ruby-2.3.0/gems/searchkick-2.4.0/lib/searchkick/indexer.rb:18:in `perform'
# /Users/.rvm/gems/ruby-2.3.0/gems/searchkick-2.4.0/lib/searchkick/logging.rb:126:in `perform'
# /Users/.rvm/gems/ruby-2.3.0/gems/searchkick-2.4.0/lib/searchkick/indexer.rb:11:in `queue'
# /Users/.rvm/gems/ruby-2.3.0/gems/searchkick-2.4.0/lib/searchkick/index.rb:535:in `bulk_index_helper'
# /Users/.rvm/gems/ruby-2.3.0/gems/searchkick-2.4.0/lib/searchkick/index.rb:94:in `bulk_index'
# /Users/.rvm/gems/ruby-2.3.0/gems/searchkick-2.4.0/lib/searchkick/logging.rb:73:in `block in bulk_index'
# /Users/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5.1/lib/active_support/notifications.rb:164:in `block in instrument'
# /Users/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
# /Users/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5.1/lib/active_support/notifications.rb:164:in `instrument'
# /Users/.rvm/gems/ruby-2.3.0/gems/searchkick-2.4.0/lib/searchkick/logging.rb:72:in `bulk_index'
# /Users/.rvm/gems/ruby-2.3.0/gems/searchkick-2.4.0/lib/searchkick/index.rb:445:in `block in import_or_update'
# /Users/.rvm/gems/ruby-2.3.0/gems/searchkick-2.4.0/lib/searchkick/index.rb:524:in `with_retries'
# /Users/.rvm/gems/ruby-2.3.0/gems/searchkick-2.4.0/lib/searchkick/index.rb:444:in `import_or_update'
# /Users/.rvm/gems/ruby-2.3.0/gems/searchkick-2.4.0/lib/searchkick/index.rb:302:in `block in import_scope'
# /Users/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5.1/lib/active_record/relation/batches.rb:124:in `find_in_batches'
# /Users/.rvm/gems/ruby-2.3.0/gems/searchkick-2.4.0/lib/searchkick/index.rb:301:in `import_scope'
# /Users/.rvm/gems/ruby-2.3.0/gems/searchkick-2.4.0/lib/searchkick/index.rb:240:in `reindex_scope'
# /Users/.rvm/gems/ruby-2.3.0/gems/searchkick-2.4.0/lib/searchkick/model.rb:72:in `searchkick_reindex'
# ./spec/search/product_spec.rb:258:in `block (4 levels) in <top (required)>'
```

**Comment by casto101** [comment]
We managed to figure this out! We discovered that we were overriding the `document_type` method on our model. Unfortunately for us, the error logging in our stack trace didn't really lead us to the issue. Thanks for the library, it's been super helpful!
