### ISSUE TITLE
Issue with method #with_highlights and query "*".

### ISSUE THREAD

**Issue by szymonlipka** [ankane/searchkick#1140]
Hi, there is problem which I've illustrated on [gist](https://gist.github.com/szymonlipka/d56847ac0f792e7317eb0d1432c519b9) - when I search for query "*" and I try calling on the results method #with_highlights I get error:

```ruby
Product.search("*", fields: [:name], highlight: true).with_highlights
.../.rvm/gems/ruby-2.4.2/bundler/gems/searchkick-85bb8db3952b/lib/searchkick/results.rb:188:in `block in highlights': undefined method `map' for nil:NilClass (NoMethodError)
        from .../.rvm/gems/ruby-2.4.2/bundler/gems/searchkick-85bb8db3952b/lib/searchkick/results.rb:187:in `map'
        from .../.rvm/gems/ruby-2.4.2/bundler/gems/searchkick-85bb8db3952b/lib/searchkick/results.rb:187:in `highlights'
        from .../.rvm/gems/ruby-2.4.2/bundler/gems/searchkick-85bb8db3952b/lib/searchkick/results.rb:193:in `with_highlights'
        from searchkick_repro.rb:29:in `<main>'
```

I guess that's caused by fact that query "*" is specially treated by elasticsearch and doesn't return any highlights.

**Comment by ankane** [comment]
Hey @szymonlipka, thanks for reporting 👍 The error is fix on master. It'll now return an empty hash.
