### ISSUE TITLE
Model.reindex fails / ImportError->mapper_parsing_exception

### ISSUE THREAD

**Issue by FlorianBruniaux** [ankane/searchkick#1255]
Hello,

I'm trying to implement Searchkick on my project.
Rails 5.2.2 / Ruby 2.6.1
Elasticsearch is running locally with docker official image. I've tried with 6.2.0, 6.3.0 and 6.7.1

I'm unable to reindex models. The main error is 
`Searchkick::ImportError: {"type"=>"mapper_parsing_exception", "reason"=>"analyzer [{s=searchkick_index, json_class=Symbol}] not found for field [analyzed]"} on item with id '1'`

Thanks by advance for your help :) 

Full trace : 

```
Searchkick::ImportError: {"type"=>"mapper_parsing_exception", "reason"=>"analyzer [{s=searchkick_index, json_class=Symbol}] not found for field [analyzed]"} on item with id '1'
/Users/florianbruniaux/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/searchkick-4.0.0/lib/searchkick/indexer.rb:23:in `perform'
/Users/florianbruniaux/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/searchkick-4.0.0/lib/searchkick/logging.rb:126:in `perform'
/Users/florianbruniaux/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/searchkick-4.0.0/lib/searchkick/indexer.rb:11:in `queue'
/Users/florianbruniaux/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/searchkick-4.0.0/lib/searchkick/bulk_indexer.rb:43:in `bulk_index'
/Users/florianbruniaux/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/searchkick-4.0.0/lib/searchkick/index.rb:146:in `bulk_index'
/Users/florianbruniaux/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/searchkick-4.0.0/lib/searchkick/logging.rb:73:in `block in bulk_index'
/Users/florianbruniaux/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/activesupport-5.2.2/lib/active_support/notifications.rb:168:in `block in instrument'
/Users/florianbruniaux/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/activesupport-5.2.2/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/Users/florianbruniaux/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/activesupport-5.2.2/lib/active_support/notifications.rb:168:in `instrument'
/Users/florianbruniaux/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/searchkick-4.0.0/lib/searchkick/logging.rb:72:in `bulk_index'
/Users/florianbruniaux/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/searchkick-4.0.0/lib/searchkick/bulk_indexer.rb:77:in `block in import_or_update'
/Users/florianbruniaux/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/searchkick-4.0.0/lib/searchkick/bulk_indexer.rb:153:in `with_retries'
/Users/florianbruniaux/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/searchkick-4.0.0/lib/searchkick/bulk_indexer.rb:72:in `import_or_update'
/Users/florianbruniaux/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/searchkick-4.0.0/lib/searchkick/bulk_indexer.rb:33:in `block in import_scope'
/Users/florianbruniaux/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/relation/batches.rb:136:in `block in find_in_batches'
/Users/florianbruniaux/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/relation/batches.rb:238:in `block in in_batches'
/Users/florianbruniaux/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/relation/batches.rb:222:in `loop'
/Users/florianbruniaux/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/relation/batches.rb:222:in `in_batches'
/Users/florianbruniaux/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/relation/batches.rb:135:in `find_in_batches'
/Users/florianbruniaux/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/querying.rb:11:in `find_in_batches'
/Users/florianbruniaux/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/searchkick-4.0.0/lib/searchkick/bulk_indexer.rb:32:in `import_scope'
/Users/florianbruniaux/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/searchkick-4.0.0/lib/searchkick/index.rb:212:in `import_scope'
/Users/florianbruniaux/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/searchkick-4.0.0/lib/searchkick/index.rb:300:in `reindex_scope'
/Users/florianbruniaux/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/searchkick-4.0.0/lib/searchkick/index.rb:200:in `reindex'
/Users/florianbruniaux/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/searchkick-4.0.0/lib/searchkick/model.rb:59:in `searchkick_reindex'
/Users/florianbruniaux/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/searchkick-4.0.0/lib/tasks/searchkick.rake:22:in `block (4 levels) in <main>'
/Users/florianbruniaux/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/searchkick-4.0.0/lib/tasks/searchkick.rake:20:in `each'
/Users/florianbruniaux/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/searchkick-4.0.0/lib/tasks/searchkick.rake:20:in `block (3 levels) in <main>'
/Users/florianbruniaux/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `block in execute'
/Users/florianbruniaux/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `each'
/Users/florianbruniaux/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `execute'
/Users/florianbruniaux/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
/Users/florianbruniaux/.rbenv/versions/2.6.1/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
/Users/florianbruniaux/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
/Users/florianbruniaux/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:183:in `invoke'
/Users/florianbruniaux/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:160:in `invoke_task'
/Users/florianbruniaux/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/Users/florianbruniaux/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `each'
/Users/florianbruniaux/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `block in top_level'
/Users/florianbruniaux/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:125:in `run_with_threads'
/Users/florianbruniaux/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:110:in `top_level'
/Users/florianbruniaux/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:83:in `block in run'
/Users/florianbruniaux/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/florianbruniaux/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:80:in `run'
/Users/florianbruniaux/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/Users/florianbruniaux/.rbenv/versions/2.6.1/bin/rake:23:in `load'
/Users/florianbruniaux/.rbenv/versions/2.6.1/bin/rake:23:in `<main>'
Tasks: TOP => searchkick:reindex:all

```

**Comment by ankane** [comment]
Hey @FlorianBruniaux, please use the gist in the Contributing Guide to reproduce.

**Comment by FlorianBruniaux** [comment]
Hey @ankane thanks for your quick answers

It seems to work with the Gist. I think the problem is linked to my project.
```
Searchkick version: 4.0.0
Elasticsearch version: 6.3.0
-- create_table(:products)
   -> 0.0103s
{"took"=>90, "timed_out"=>false, "_shards"=>{"total"=>5, "successful"=>5, "skipped"=>0, "failed"=>0}, "hits"=>{"total"=>1, "max_score"=>2.8768208, "hits"=>[{"_index"=>"products_development_20190417132005668", "_type"=>"pr oduct", "_id"=>"1", "_score"=>2.8768208}]}}
``` 

It's strange because the entities tested are quite simples. For example class User (generated by devise). I'll try to identify if an other gem could be the problem.

Still the error :
```
Searchkick::ImportError: {"type"=>"mapper_parsing_exception", "reason"=>"analyzer [{s=searchkick_index, json_class=Symbol}] not found for field [analyzed]"} on item with id '1'
```

**Comment by FlorianBruniaux** [comment]
It seems to be a problem with the following gem : https://github.com/zenaton/zenaton-ruby
Because of a specific serialization system https://github.com/zenaton/zenaton-ruby/issues/56

I'll see with them

**Comment by FlorianBruniaux** [comment]
Fixed with the following branch : https://github.com/zenaton/zenaton-ruby/tree/fix/symbol-serialization

Not a Searchkick issue. It was a Zenaton compatibility issue
