### ISSUE TITLE
Faraday::TimeoutError: execution expired with AWS ES URL

### ISSUE THREAD

**Issue by maahesmahesh** [ankane/searchkick#1297]
I received the Faraday::TimeoutError: execution expired when i specify the ENV["ELASTICSEARCH_URL"] without port number along with aws_credentials.

For example:

In initializer file:
```
ENV["ELASTICSEARCH_URL"] = "https://es-domain-1234.us-east-1.es.amazonaws.com"

Searchkick.aws_credentials = {
  access_key_id: ENV["AWS_ACCESS_KEY_ID"],
  secret_access_key: ENV["AWS_SECRET_ACCESS_KEY"],
  region: "us-east-1"
}
```

Received error:
```
Faraday::TimeoutError: execution expired
	from /Users/maheswaran/.rvm/gems/ruby-2.4.1@convertfox/gems/httpclient-2.8.3/lib/httpclient/session.rb:611:in `initialize'
	from /Users/maheswaran/.rvm/gems/ruby-2.4.1@convertfox/gems/httpclient-2.8.3/lib/httpclient/session.rb:611:in `new'
	from /Users/maheswaran/.rvm/gems/ruby-2.4.1@convertfox/gems/httpclient-2.8.3/lib/httpclient/session.rb:611:in `create_socket'
	from /Users/maheswaran/.rvm/gems/ruby-2.4.1@convertfox/gems/httpclient-2.8.3/lib/httpclient/ssl_socket.rb:21:in `create_socket'
	from /Users/maheswaran/.rvm/gems/ruby-2.4.1@convertfox/gems/httpclient-2.8.3/lib/httpclient/session.rb:752:in `block in connect'
	from /Users/maheswaran/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/timeout.rb:103:in `timeout'
	from /Users/maheswaran/.rvm/gems/ruby-2.4.1@convertfox/gems/httpclient-2.8.3/lib/httpclient/session.rb:748:in `connect'
	from /Users/maheswaran/.rvm/gems/ruby-2.4.1@convertfox/gems/httpclient-2.8.3/lib/httpclient/session.rb:511:in `query'
	from /Users/maheswaran/.rvm/gems/ruby-2.4.1@convertfox/gems/httpclient-2.8.3/lib/httpclient/session.rb:177:in `query'
	from /Users/maheswaran/.rvm/gems/ruby-2.4.1@convertfox/gems/httpclient-2.8.3/lib/httpclient.rb:1242:in `do_get_block'
	from /Users/maheswaran/.rvm/gems/ruby-2.4.1@convertfox/gems/httpclient-2.8.3/lib/httpclient.rb:1019:in `block in do_request'
	from /Users/maheswaran/.rvm/gems/ruby-2.4.1@convertfox/gems/httpclient-2.8.3/lib/httpclient.rb:1133:in `protect_keep_alive_disconnected'
	from /Users/maheswaran/.rvm/gems/ruby-2.4.1@convertfox/gems/httpclient-2.8.3/lib/httpclient.rb:1014:in `do_request'
	from /Users/maheswaran/.rvm/gems/ruby-2.4.1@convertfox/gems/httpclient-2.8.3/lib/httpclient.rb:856:in `request'
	from /Users/maheswaran/.rvm/gems/ruby-2.4.1@convertfox/gems/faraday-0.9.2/lib/faraday/adapter/httpclient.rb:36:in `call'
	from /Users/maheswaran/.rvm/gems/ruby-2.4.1@convertfox/gems/faraday_middleware-aws-sigv4-0.2.4/lib/faraday_middleware/request/aws_sigv4.rb:15:in `call'
... 1 levels...
	from /Users/maheswaran/.rvm/gems/ruby-2.4.1@convertfox/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
	from /Users/maheswaran/.rvm/gems/ruby-2.4.1@convertfox/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
	from /Users/maheswaran/.rvm/gems/ruby-2.4.1@convertfox/gems/elasticsearch-transport-7.1.0/lib/elasticsearch/transport/transport/http/faraday.rb:40:in `block in perform_request'
	from /Users/maheswaran/.rvm/gems/ruby-2.4.1@convertfox/gems/elasticsearch-transport-7.1.0/lib/elasticsearch/transport/transport/base.rb:279:in `perform_request'
	from /Users/maheswaran/.rvm/gems/ruby-2.4.1@convertfox/gems/elasticsearch-transport-7.1.0/lib/elasticsearch/transport/transport/http/faraday.rb:37:in `perform_request'
	from /Users/maheswaran/.rvm/gems/ruby-2.4.1@convertfox/gems/elasticsearch-transport-7.1.0/lib/elasticsearch/transport/client.rb:160:in `perform_request'
	from /Users/maheswaran/.rvm/gems/ruby-2.4.1@convertfox/gems/elasticsearch-api-7.1.0/lib/elasticsearch/api/actions/search.rb:160:in `search'
	from /Users/maheswaran/.rvm/gems/ruby-2.4.1@convertfox/gems/searchkick-4.0.2/lib/searchkick/index.rb:63:in `total_docs'
	from (irb):1
	from /Users/maheswaran/.rvm/gems/ruby-2.4.1@convertfox/gems/railties-5.0.3/lib/rails/commands/console.rb:65:in `start'
	from /Users/maheswaran/.rvm/gems/ruby-2.4.1@convertfox/gems/railties-5.0.3/lib/rails/commands/console_helper.rb:9:in `start'
	from /Users/maheswaran/.rvm/gems/ruby-2.4.1@convertfox/gems/railties-5.0.3/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /Users/maheswaran/.rvm/gems/ruby-2.4.1@convertfox/gems/railties-5.0.3/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /Users/maheswaran/.rvm/gems/ruby-2.4.1@convertfox/gems/railties-5.0.3/lib/rails/commands.rb:18:in `<top (required)>'
	from /Users/maheswaran/convertfox-backend/bin/rails:9:in `require'
	from /Users/maheswaran/convertfox-backend/bin/rails:9:in `<main>'
```

It can be fixed by following methods:

1. Specify ELASTICSEARCH_URL with port number.
 `ENV["ELASTICSEARCH_URL"] = "https://es-domain-1234.us-east-1.es.amazonaws.com:443"`

2. Initialize Elasticsearch client.
```
require 'faraday_middleware/aws_sigv4'
ENV["ELASTICSEARCH_URL"] = "es-domain-1234.us-east-1.es.amazonaws.com"
Searchkick.client = Elasticsearch::Client.new hosts: [{ host: ENV["ELASTICSEARCH_URL"], port: '443', scheme: 'https' }] do |f|
  f.request :aws_sigv4,
            credentials: Aws::Credentials.new(ENV['NEW_AWS_ACCESS_KEY_ID'], ENV['NEW_AWS_SECRET_ACCESS_KEY']),
            service: 'es',
            region: "us-east-1"
end
```

**Comment by ankane** [comment]
Hey @maahesmahesh, due to a change with the `elasticsearch` gem, you'll need to specify the port. See https://github.com/elastic/elasticsearch-ruby/issues/669 and https://github.com/elastic/elasticsearch-ruby/issues/686

**Comment by ankane** [comment]
Added the port to the instructions in the readme. Thanks for reporting 👍
