### ISSUE TITLE
Incorrect types when bulk re-indexing (`text` instead of `keyword`, no `geo_point`)

### ISSUE THREAD

**Issue by cesarizu** [ankane/searchkick#1327]
When re-indexing using `Searchkick.callbacks(:bulk) { Product.all.map(&:reindex) }`, the indices on ES are created incorrectly, `keyword` fields are created as `text` and `geo_point` fields are created as plain objects.

Is there something else that I need to do to make this work? Or is this a bug?

I'm using the following versions:

elasticsearch (6.8 gem and 6.5 server)
searchkick (4.1.0)
mongoid (6.4.2)

**Comment by ankane** [comment]
Hi @cesarizu, please use the gist in the Contributing Guide to reproduce. In general, `Product.reindex` is your best option for a full reindex.

**Comment by cesarizu** [comment]
I've forked the gist reproducing the error here: https://gist.github.com/cesarizu/53ff8e99d9882c5382ef3213708d0262

Output:

```
Searchkick version: 4.1.0
Elasticsearch version: 7.1.0
-- create_table(:products)
   -> 0.0020s
Traceback (most recent call last):
        14: from test.rb:28:in `<main>'
        13: from /home/user/.rvm/gems/ruby-2.6.4@company/bundler/gems/searchkick-610937f8c16f/lib/searchkick/model.rb:44:in `searchkick_search'
        12: from /home/user/.rvm/gems/ruby-2.6.4@company/bundler/gems/searchkick-610937f8c16f/lib/searchkick.rb:119:in `search'
        11: from /home/user/.rvm/gems/ruby-2.6.4@company/bundler/gems/searchkick-610937f8c16f/lib/searchkick/query.rb:93:in `execute'
        10: from /home/user/.rvm/gems/ruby-2.6.4@company/bundler/gems/searchkick-610937f8c16f/lib/searchkick/logging.rb:12:in `execute_search'
         9: from /home/user/.rvm/gems/ruby-2.6.4@company/gems/activesupport-6.0.0/lib/active_support/notifications.rb:180:in `instrument'
         8: from /home/user/.rvm/gems/ruby-2.6.4@company/gems/activesupport-6.0.0/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
         7: from /home/user/.rvm/gems/ruby-2.6.4@company/gems/activesupport-6.0.0/lib/active_support/notifications.rb:180:in `block in instrument'
         6: from /home/user/.rvm/gems/ruby-2.6.4@company/bundler/gems/searchkick-610937f8c16f/lib/searchkick/logging.rb:13:in `block in execute_search'
         5: from /home/user/.rvm/gems/ruby-2.6.4@company/bundler/gems/searchkick-610937f8c16f/lib/searchkick/query.rb:225:in `execute_search'
         4: from /home/user/.rvm/gems/ruby-2.6.4@company/gems/elasticsearch-api-7.3.0/lib/elasticsearch/api/actions/search.rb:147:in `search'
         3: from /home/user/.rvm/gems/ruby-2.6.4@company/gems/elasticsearch-transport-7.3.0/lib/elasticsearch/transport/client.rb:152:in `perform_request'
         2: from /home/user/.rvm/gems/ruby-2.6.4@company/gems/elasticsearch-transport-7.3.0/lib/elasticsearch/transport/transport/http/faraday.rb:24:in `perform_request'
         1: from /home/user/.rvm/gems/ruby-2.6.4@company/gems/elasticsearch-transport-7.3.0/lib/elasticsearch/transport/transport/base.rb:327:in `perform_request'
/home/user/.rvm/gems/ruby-2.6.4@company/gems/elasticsearch-transport-7.3.0/lib/elasticsearch/transport/transport/base.rb:206:in `__raise_transport_error': [400] {"error":{"root_cause":[{"type":"query_shard_exception","reason":"[match] analyzer [searchkick_search] not found","index_uuid":"WNPb98VORLisM9dFmLt--g","index":"products_development"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"products_development","node":"B4Eq6chLRsuCyi-YLQaCKg","reason":{"type":"query_shard_exception","reason":"[match] analyzer [searchkick_search] not found","index_uuid":"WNPb98VORLisM9dFmLt--g","index":"products_development"}}]},"status":400} (Elasticsearch::Transport::Transport::Errors::BadRequest)
        5: from test.rb:28:in `<main>'
        4: from /home/user/.rvm/gems/ruby-2.6.4@company/bundler/gems/searchkick-610937f8c16f/lib/searchkick/model.rb:44:in `searchkick_search'
        3: from /home/user/.rvm/gems/ruby-2.6.4@company/bundler/gems/searchkick-610937f8c16f/lib/searchkick.rb:119:in `search'
        2: from /home/user/.rvm/gems/ruby-2.6.4@company/bundler/gems/searchkick-610937f8c16f/lib/searchkick/query.rb:92:in `execute'
        1: from /home/user/.rvm/gems/ruby-2.6.4@company/bundler/gems/searchkick-610937f8c16f/lib/searchkick/query.rb:99:in `rescue in execute'
/home/user/.rvm/gems/ruby-2.6.4@company/bundler/gems/searchkick-610937f8c16f/lib/searchkick/query.rb:211:in `handle_error': Bad mapping - run Product.reindex (Searchkick::InvalidQueryError)
```

The main reason I'm trying to do this is to be able to reindex a large db without using too much memory. Using `Product.reindex` is using a lot of memory in our case. Using `bulk` and batching seems to keep the memory down.

**Comment by ankane** [comment]
Hey @cesarizu, `Product.reindex` must be called on all indices at least once. You can use `Product.reindex(import: false)` to create an empty index. However, I'm skeptical `callbacks(:bulk)` uses less memory than `reindex` - if that's the case, we should fix `reindex`. Do you have a benchmark?

**Comment by ankane** [comment]
Closing due to no response
