### ISSUE TITLE
Deprecation warning for `faraday_middleware-aws-sigv4` gem

### ISSUE THREAD

**Issue by gdomingu** [ankane/searchkick#1329]
Hi there. I'm connecting to aws like
```
Searchkick.aws_credentials = {
		credentials: Aws::InstanceProfileCredentials.new,
		region: 'us-east-1'
}
```

But am getting a deprecation warning.
```
DEPRECATION WARNING: called deprecated method `access_key_id' of an Aws::CredentialProvider, use #credentials instead
/usr/local/lib/ruby/gems/2.4.0/gems/aws-sigv4-1.1.0/lib/aws-sigv4/signer.rb:670:in `credentials_set?'
/usr/local/lib/ruby/gems/2.4.0/gems/aws-sigv4-1.1.0/lib/aws-sigv4/signer.rb:661:in `get_credentials'
/usr/local/lib/ruby/gems/2.4.0/gems/aws-sigv4-1.1.0/lib/aws-sigv4/signer.rb:205:in `sign_request'
/usr/local/lib/ruby/gems/2.4.0/gems/faraday_middleware-aws-sigv4-0.3.0/lib/faraday_middleware/request/aws_sigv4.rb:22:in `sign!'
/usr/local/lib/ruby/gems/2.4.0/gems/faraday_middleware-aws-sigv4-0.3.0/lib/faraday_middleware/request/aws_sigv4.rb:14:in `call'
/usr/local/lib/ruby/gems/2.4.0/gems/searchkick-4.1.0/lib/searchkick/middleware.rb:9:in `call'
```

How should I resolve this? Do I need to use an older version of `faraday_middleware-aws-sigv4` gem to avoid this with searchkick?

**Comment by ankane** [comment]
Hey @gdomingu, try using `credentials_provider` instead of `credentials` as listed in the AWS docs: https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/Sigv4/Signer.html

If that doesn't solve it, your best bet is to look at the code in the aws-signv4 gem to see how to avoid triggering it.

**Comment by gdomingu** [comment]
@ankane ah that was it. How did I miss that? Thank you.
