### ISSUE TITLE
AWS Elasticsearch Configuration Errors

### ISSUE THREAD

**Issue by antwonlee** [ankane/searchkick#1334]
I am following the [instruction from the README,](https://github.com/ankane/searchkick#amazon-elasticsearch-service) but I am getting this error:

`cannot load such file -- aws-sdk/signers/v4`

I have searched StackOverflow but really couldn't find any answers.

Is this [faraday_middleware-aws-sigv4](https://github.com/winebarrel/faraday_middleware-aws-sigv4) gem issue?

Anyone else has trouble setting up AWS es configs?

**Comment by ankane** [comment]
Hey @antwonlee, can you paste the full backtrace?

**Comment by antwonlee** [comment]
@ankane This is what I have...

```ruby
# Gemfile
gem 'aws-sdk'
gem 'faraday_middleware-aws-signers-v4'
gem 'elasticsearch'
gem 'searchkick'
```

```ruby
# config/initializer/elasticsearch.rb
require 'faraday_middleware/aws_signers_v4'

ENV['ELASTICSEARCH_URL'] = "https://domain1234.us-east-2.es.amazonaws.com:443"

Searchkick.aws_credentials = {
  access_key_id: ENV['AWS_ACCESS_KEY_ID'],
  secret_access_key: ENV['AWS_SECRET_ACCESS_KEY'],
  region: ENV['AWS_REGION']
}
```

```
 bundle exec rake searchkick:reindex:all --trace
** Invoke searchkick:reindex:all (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute searchkick:reindex:all
Reindexing Job...
rake aborted!
LoadError: cannot load such file -- aws-sdk/signers/v4
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/skylight-core-4.2.0/lib/skylight/core/probes.rb:118:in `require'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/skylight-core-4.2.0/lib/skylight/core/probes.rb:118:in `require'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/faraday_middleware-aws-signers-v4-0.2.0.beta/lib/faraday_middleware/aws_signers_v4_ext.rb:1:in `<top (required)>'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/skylight-core-4.2.0/lib/skylight/core/probes.rb:118:in `require'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/skylight-core-4.2.0/lib/skylight/core/probes.rb:118:in `require'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/faraday_middleware-aws-signers-v4-0.2.0.beta/lib/faraday_middleware/request/aws_signers_v4.rb:2:in `<top (required)>'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/skylight-core-4.2.0/lib/skylight/core/probes.rb:118:in `require'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/skylight-core-4.2.0/lib/skylight/core/probes.rb:118:in `require'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/faraday_middleware-aws-signers-v4-0.2.0.beta/lib/faraday_middleware/aws_signers_v4.rb:7:in `block in <module:FaradayMiddleware>'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/faraday-0.17.0/lib/faraday.rb:217:in `block in load_middleware'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/faraday-0.17.0/lib/faraday.rb:199:in `middleware_mutex'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/faraday-0.17.0/lib/faraday.rb:216:in `load_middleware'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/faraday-0.17.0/lib/faraday.rb:190:in `lookup_middleware'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/faraday-0.17.0/lib/faraday/rack_builder.rb:228:in `use_symbol'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/faraday-0.17.0/lib/faraday/rack_builder.rb:93:in `request'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/2.6.0/forwardable.rb:230:in `request'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/searchkick-4.1.0/lib/searchkick.rb:60:in `block in client'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/elasticsearch-transport-7.4.0/lib/elasticsearch/transport/client.rb:137:in `block in initialize'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/faraday-0.17.0/lib/faraday/connection.rb:89:in `initialize'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/faraday-0.17.0/lib/faraday.rb:70:in `new'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/faraday-0.17.0/lib/faraday.rb:70:in `new'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/http/faraday.rb:41:in `__build_connection'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/base.rb:144:in `block in __build_connections'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/base.rb:136:in `map'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/base.rb:136:in `__build_connections'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/base.rb:47:in `initialize'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/elasticsearch-transport-7.4.0/lib/elasticsearch/transport/client.rb:136:in `new'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/elasticsearch-transport-7.4.0/lib/elasticsearch/transport/client.rb:136:in `initialize'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/elasticsearch-transport-7.4.0/lib/elasticsearch/transport.rb:32:in `new'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/elasticsearch-transport-7.4.0/lib/elasticsearch/transport.rb:32:in `new'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/searchkick-4.1.0/lib/searchkick.rb:54:in `client'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/searchkick-4.1.0/lib/searchkick/index.rb:255:in `client'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/searchkick-4.1.0/lib/searchkick/index.rb:105:in `all_indices'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/searchkick-4.1.0/lib/searchkick/index.rb:119:in `clean_indices'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/searchkick-4.1.0/lib/searchkick/index.rb:274:in `reindex_scope'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/searchkick-4.1.0/lib/searchkick/index.rb:200:in `reindex'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/searchkick-4.1.0/lib/searchkick/model.rb:60:in `searchkick_reindex'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/searchkick-4.1.0/lib/tasks/searchkick.rake:22:in `block (4 levels) in <top (required)>'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/searchkick-4.1.0/lib/tasks/searchkick.rake:20:in `each'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/searchkick-4.1.0/lib/tasks/searchkick.rake:20:in `block (3 levels) in <top (required)>'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rake-13.0.0/lib/rake/task.rb:280:in `block in execute'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rake-13.0.0/lib/rake/task.rb:280:in `each'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rake-13.0.0/lib/rake/task.rb:280:in `execute'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rake-13.0.0/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rake-13.0.0/lib/rake/task.rb:198:in `invoke_with_call_chain'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rake-13.0.0/lib/rake/task.rb:187:in `invoke'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rake-13.0.0/lib/rake/application.rb:160:in `invoke_task'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rake-13.0.0/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rake-13.0.0/lib/rake/application.rb:116:in `each'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rake-13.0.0/lib/rake/application.rb:116:in `block in top_level'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rake-13.0.0/lib/rake/application.rb:125:in `run_with_threads'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rake-13.0.0/lib/rake/application.rb:110:in `top_level'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rake-13.0.0/lib/rake/application.rb:83:in `block in run'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rake-13.0.0/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rake-13.0.0/lib/rake/application.rb:80:in `run'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rake-13.0.0/exe/rake:27:in `<top (required)>'
/Users/anthonylee/.rbenv/versions/2.6.3/bin/rake:23:in `load'
/Users/anthonylee/.rbenv/versions/2.6.3/bin/rake:23:in `<top (required)>'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/2.6.0/bundler/cli/exec.rb:74:in `load'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/2.6.0/bundler/cli/exec.rb:74:in `kernel_load'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/2.6.0/bundler/cli/exec.rb:28:in `run'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/2.6.0/bundler/cli.rb:463:in `exec'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/2.6.0/bundler/cli.rb:27:in `dispatch'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/2.6.0/bundler/cli.rb:18:in `start'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-1.17.2/exe/bundle:30:in `block in <top (required)>'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/2.6.0/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/Users/anthonylee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-1.17.2/exe/bundle:22:in `<top (required)>'
/Users/anthonylee/.rbenv/versions/2.6.3/bin/bundle:23:in `load'
/Users/anthonylee/.rbenv/versions/2.6.3/bin/bundle:23:in `<main>'
Tasks: TOP => searchkick:reindex:all
```

**Comment by antwonlee** [comment]
I had to downgrade the `aws-sdk`

```ruby
gem 'aws-sdk', '~> 2'
```

It is working now.

**Comment by ankane** [comment]
fwiw, it looks like you're using `faraday_middleware-aws-signers-v4`, not `faraday_middleware-aws-sigv4` as recommended.

**Comment by antwonlee** [comment]
@ankane omg.  How did I miss that?  Thanks!  Working perfectly.
