### ISSUE TITLE
NoMethodError: private method `select' called for "":String

### ISSUE THREAD

**Issue by aristotelesbr** [ankane/searchkick#1436]
this problem has been reported:  #308  😔 

```bash
NoMethodError: private method `select' called for "":String
```
Im using ruby 2.2.*, Rails 4.2.1 and searchkick version `3.1.2`, elasticsearch:6.5.2 with Linux Mint 20.04. the weirdest thing is using docker and everything works well in production.

`client.indices.get_aliases` this method always returns a blank string:

Error:
```bash
NoMethodError: private method `select' called for "":String
	from /usr/local/bundle/gems/searchkick-3.1.2/lib/searchkick/index.rb:108:in `all_indices'
	from /usr/local/bundle/gems/searchkick-3.1.2/lib/searchkick/index.rb:114:in `clean_indices'
	from /usr/local/bundle/gems/searchkick-3.1.2/lib/searchkick/index.rb:265:in `reindex_scope'
	from /usr/local/bundle/gems/searchkick-3.1.2/lib/searchkick/index.rb:195:in `reindex'
	from /usr/local/bundle/gems/searchkick-3.1.2/lib/searchkick/model.rb:59:in `searchkick_reindex'
	from (irb):25
```
Gemfile.lock details
```rb
searchkick (3.1.2)
      activemodel (>= 4.2)
      elasticsearch (>= 5)
      hashie
```

Any suggestions as to what might be happening?

**Comment by mirzahaiderali** [comment]
Hey @aristotelesbr, wondering if you were able to resolve this issue? I'm getting the same error on M1 machine
