### ISSUE TITLE
[Rails issue] User.search_index.refresh not working outside parallelize_setup block.

### ISSUE THREAD

**Issue by zw963** [ankane/searchkick#1437]
**Describe the bug**

I run a test on rails 6.0.3.2, with older 5.2 default.
This test is working if not use parallel test and use `User.reindex` instead of `User.search_index.refresh`.

Following is my test/test_helper.rb

```rb
# test/test_helper.rb

class ActiveSupport::TestCase
  # ......

  parallelize_setup do |worker|
    Searchkick.index_suffix = worker

    FactoryBot.create(:user)

    User.reindex

    p User.search_index.refresh  # it working here.
    Searchkick.disable_callbacks
  end

  parallelize_teardown do
    User.search_index.delete
  end
```

Following is my test file.

```rb
# test/controllers/api/v2/pms/guests_controller_test.rb

class Api::V2::Pms::GuestsControllerTest < ActionDispatch::IntegrationTest
  def setup
    Searchkick.enable_callbacks
    # ....
  end

  def teardown
    Searchkick.disable_callbacks
  end

  context '#index' do
    should 'list guests in pagination' do
      5.times do |i|
        create(:user, {
          name: "user#{i}",
          username: "user#{i}",
          email: "user#{i}@example.com",
          roles: %i[traveller],
          account: @account
        })
      end

      # User.reindex   # it works if use User.reindex

    # neither working  on enable parallel test nor disable it if outside parallelize_setup.
    p User.search_index.refresh 
  end
end
```

```sh
$: PARALLEL_WORKERS=2 UPLOADER_STORAGE=file DISABLE_SPRING=1 bundle exec rails test test/controllers/api/v2/pms/guests_controller_test.rb:28

ETraceback (most recent call last):
	20: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/minitest-5.14.1/lib/minitest.rb:68:in `block in autorun'
	19: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/minitest-5.14.1/lib/minitest.rb:138:in `run'
	18: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/activesupport-6.0.3.2/lib/active_support/testing/parallelization.rb:74:in `start'
	17: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/activesupport-6.0.3.2/lib/active_support/testing/parallelization.rb:74:in `map'
	16: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/activesupport-6.0.3.2/lib/active_support/testing/parallelization.rb:74:in `each'
	15: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/activesupport-6.0.3.2/lib/active_support/testing/parallelization.rb:74:in `times'
	14: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/activesupport-6.0.3.2/lib/active_support/testing/parallelization.rb:75:in `block in start'
	13: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/activesupport-6.0.3.2/lib/active_support/testing/parallelization.rb:75:in `fork'
	12: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/activesupport-6.0.3.2/lib/active_support/testing/parallelization.rb:110:in `block (2 levels) in start'
	11: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/activesupport-6.0.3.2/lib/active_support/testing/parallelization.rb:68:in `run_cleanup'
	10: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/activesupport-6.0.3.2/lib/active_support/testing/parallelization.rb:68:in `each'
	 9: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/activesupport-6.0.3.2/lib/active_support/testing/parallelization.rb:69:in `block in run_cleanup'
	 8: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/activesupport-6.0.3.2/lib/active_support/test_case.rb:130:in `block in parallelize_teardown'
	 7: from /home/zw963/Airhost/airhost_ror/test/test_helper.rb:56:in `block in <class:TestCase>'
	 6: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/searchkick-4.4.1/lib/searchkick/index.rb:27:in `delete'
	 5: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/elasticsearch-api-7.5.0/lib/elasticsearch/api/actions/indices/delete.rb:37:in `delete'
	 4: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/elasticsearch-api-7.5.0/lib/elasticsearch/api/namespace/common.rb:25:in `perform_request'
	 3: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/elasticsearch-transport-7.5.0/lib/elasticsearch/transport/client.rb:152:in `perform_request'
	 2: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/elasticsearch-transport-7.5.0/lib/elasticsearch/transport/transport/http/faraday.rb:24:in `perform_request'
	 1: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/elasticsearch-transport-7.5.0/lib/elasticsearch/transport/transport/base.rb:333:in `perform_request'
/home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/elasticsearch-transport-7.5.0/lib/elasticsearch/transport/transport/base.rb:205:in `__raise_transport_error': [404] {"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [users_test]","resource.type":"index_or_alias","resource.id":"users_test","index_uuid":"_na_","index":"users_test"}],"type":"index_not_found_exception","reason":"no such index [users_test]","resource.type":"index_or_alias","resource.id":"users_test","index_uuid":"_na_","index":"users_test"},"status":404} (Elasticsearch::Transport::Transport::Errors::NotFound)
```

**To reproduce**

Will add reproduce code later if need, Thank you.

**Comment by zw963** [comment]
Following is my searchkick config:

```rb
  searchkick(
    searchable: %i[name username email phone],
    filterable: %i[roles account_id name username email phone],
    callbacks: false,
    language: 'japanese'
  )

def search_data
    {
      name: name,
      username: username,
      email: email,
      phone: phone,
      account_id: account_id,
      roles: roles.map(&:to_s),
      order_count: order_count,
      created_at: created_at
    }
  end
```

**Comment by ankane** [comment]
Hey @zw963, it looks like `Searchkick.index_suffix` isn't set when that test case is running (the index name should be `users_testN` instead of `users_test`, where `N` is the worker number).

**Comment by zw963** [comment]
In fact, i don't know why, when i add a `puts` on the test case, it return `user_test`.

But, when i remove `puts` from test case,  instead, only add puts into `test_helper`, as below:

```rb
class ActiveSupport::TestCase
  # elasticsearch_classes = [Booking, User, House, UserProfile, Airhost::Order]
  elasticsearch_classes = [User]

  parallelize_setup do |worker|
    Searchkick.index_suffix = worker
    puts "Searchkick.index_suffix = #{Searchkick.index_suffix}"

    elasticsearch_classes.each do |klass|
      klass.reindex
    end

    Searchkick.disable_callbacks
  end

  parallelize_teardown do
    elasticsearch_classes.each do |klass|
      klass.search_index.delete
    end
  end
end
```
It return following  result:

```
Searchkick.index_suffix = 0
Searchkick.index_suffix = 2
Searchkick.index_suffix = 1
Searchkick.index_suffix = 3
Traceback (most recent call last):
        22: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/minitest-5.14.1/lib/minitest.rb:68:in `block in autorun'
        21: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/minitest-5.14.1/lib/minitest.rb:138:in `run'
        20: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/activesupport-6.0.3.2/lib/active_support/testing/parallelization.rb:74:in `start'
        19: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/activesupport-6.0.3.2/lib/active_support/testing/parallelization.rb:74:in `map'
        18: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/activesupport-6.0.3.2/lib/active_support/testing/parallelization.rb:74:in `each'
        17: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/activesupport-6.0.3.2/lib/active_support/testing/parallelization.rb:74:in `times'
        16: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/activesupport-6.0.3.2/lib/active_support/testing/parallelization.rb:75:in `block in start'
        15: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/activesupport-6.0.3.2/lib/active_support/testing/parallelization.rb:75:in `fork'
        14: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/activesupport-6.0.3.2/lib/active_support/testing/parallelization.rb:110:in `block (2 levels) in start'
        13: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/activesupport-6.0.3.2/lib/active_support/testing/parallelization.rb:68:in `run_cleanup'
        12: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/activesupport-6.0.3.2/lib/active_support/testing/parallelization.rb:68:in `each'
        11: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/activesupport-6.0.3.2/lib/active_support/testing/parallelization.rb:69:in `block in run_cleanup'
        10: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/activesupport-6.0.3.2/lib/active_support/test_case.rb:130:in `block in parallelize_teardown'
         9: from /home/zw963/Airhost/airhost_ror/test/elasticsearch_test_helper.rb:18:in `block in <class:TestCase>'
         8: from /home/zw963/Airhost/airhost_ror/test/elasticsearch_test_helper.rb:18:in `each'
         7: from /home/zw963/Airhost/airhost_ror/test/elasticsearch_test_helper.rb:19:in `block (2 levels) in <class:TestCase>'
         6: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/searchkick-4.4.1/lib/searchkick/index.rb:25:in `delete'
         5: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/elasticsearch-api-7.5.0/lib/elasticsearch/api/actions/indices/delete.rb:37:in `delete'
         4: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/elasticsearch-api-7.5.0/lib/elasticsearch/api/namespace/common.rb:25:in `perform_request'
         3: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/elasticsearch-transport-7.5.0/lib/elasticsearch/transport/client.rb:152:in `perform_request'
         2: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/elasticsearch-transport-7.5.0/lib/elasticsearch/transport/transport/http/faraday.rb:24:in `perform_request'
         1: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/elasticsearch-transport-7.5.0/lib/elasticsearch/transport/transport/base.rb:333:in `perform_request'
/home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/elasticsearch-transport-7.5.0/lib/elasticsearch/transport/transport/base.rb:205:in `__raise_transport_error': [404] {"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [users_test_20200830155430544]","index_uuid":"1CjtsGaXRVyG31v3AVwctA","index":"users_test_20200830155430544"}],"type":"index_not_found_exception","reason":"no such index [users_test_20200830155430544]","index_uuid":"1CjtsGaXRVyG31v3AVwctA","index":"users_test_20200830155430544"},"status":404} (Elasticsearch::Transport::Transport::Errors::NotFound)
Traceback (most recent call last):
        22: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/minitest-5.14.1/lib/minitest.rb:68:in `block in autorun'
        21: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/minitest-5.14.1/lib/minitest.rb:138:in `run'
        20: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/activesupport-6.0.3.2/lib/active_support/testing/parallelization.rb:74:in `start'
        19: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/activesupport-6.0.3.2/lib/active_support/testing/parallelization.rb:74:in `map'
        18: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/activesupport-6.0.3.2/lib/active_support/testing/parallelization.rb:74:in `each'
        17: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/activesupport-6.0.3.2/lib/active_support/testing/parallelization.rb:74:in `times'
        16: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/activesupport-6.0.3.2/lib/active_support/testing/parallelization.rb:75:in `block in start'
        15: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/activesupport-6.0.3.2/lib/active_support/testing/parallelization.rb:75:in `fork'
        14: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/activesupport-6.0.3.2/lib/active_support/testing/parallelization.rb:110:in `block (2 levels) in start'
        13: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/activesupport-6.0.3.2/lib/active_support/testing/parallelization.rb:68:in `run_cleanup'
        12: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/activesupport-6.0.3.2/lib/active_support/testing/parallelization.rb:68:in `each'
        11: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/activesupport-6.0.3.2/lib/active_support/testing/parallelization.rb:69:in `block in run_cleanup'
        10: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/activesupport-6.0.3.2/lib/active_support/test_case.rb:130:in `block in parallelize_teardown'
         9: from /home/zw963/Airhost/airhost_ror/test/elasticsearch_test_helper.rb:18:in `block in <class:TestCase>'
         8: from /home/zw963/Airhost/airhost_ror/test/elasticsearch_test_helper.rb:18:in `each'
         7: from /home/zw963/Airhost/airhost_ror/test/elasticsearch_test_helper.rb:19:in `block (2 levels) in <class:TestCase>'
         6: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/searchkick-4.4.1/lib/searchkick/index.rb:25:in `delete'
         5: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/elasticsearch-api-7.5.0/lib/elasticsearch/api/actions/indices/delete.rb:37:in `delete'
         4: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/elasticsearch-api-7.5.0/lib/elasticsearch/api/namespace/common.rb:25:in `perform_request'
         3: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/elasticsearch-transport-7.5.0/lib/elasticsearch/transport/client.rb:152:in `perform_request'
         2: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/elasticsearch-transport-7.5.0/lib/elasticsearch/transport/transport/http/faraday.rb:24:in `perform_request'
         1: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/elasticsearch-transport-7.5.0/lib/elasticsearch/transport/transport/base.rb:333:in `perform_request'
/home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/elasticsearch-transport-7.5.0/lib/elasticsearch/transport/transport/base.rb:205:in `__raise_transport_error': [404] {"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [users_test_20200830155430544]","index_uuid":"1CjtsGaXRVyG31v3AVwctA","index":"users_test_20200830155430544"}],"type":"index_not_found_exception","reason":"no such index [users_test_20200830155430544]","index_uuid":"1CjtsGaXRVyG31v3AVwctA","index":"users_test_20200830155430544"},"status":404} (Elasticsearch::Transport::Transport::Errors::NotFound)
```

But if i add a `p` back to test case, it get different result, it so wired!

![image](https://user-images.githubusercontent.com/549126/91654374-bc3b6280-eada-11ea-92e6-f7d0d078c4ec.png)


```
Searchkick.index_suffix = 0
Searchkick.index_suffix = 3
Searchkick.index_suffix = 2
Searchkick.index_suffix = 1
Traceback (most recent call last):
        22: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/minitest-5.14.1/lib/minitest.rb:68:in `block in autorun'
        21: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/minitest-5.14.1/lib/minitest.rb:138:in `run'
        20: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/activesupport-6.0.3.2/lib/active_support/testing/parallelization.rb:74:in `start'
        19: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/activesupport-6.0.3.2/lib/active_support/testing/parallelization.rb:74:in `map'
        18: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/activesupport-6.0.3.2/lib/active_support/testing/parallelization.rb:74:in `each'
        17: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/activesupport-6.0.3.2/lib/active_support/testing/parallelization.rb:74:in `times'
        16: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/activesupport-6.0.3.2/lib/active_support/testing/parallelization.rb:75:in `block in start'
        15: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/activesupport-6.0.3.2/lib/active_support/testing/parallelization.rb:75:in `fork'
        14: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/activesupport-6.0.3.2/lib/active_support/testing/parallelization.rb:110:in `block (2 levels) in start'
        13: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/activesupport-6.0.3.2/lib/active_support/testing/parallelization.rb:68:in `run_cleanup'
        12: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/activesupport-6.0.3.2/lib/active_support/testing/parallelization.rb:68:in `each'
        11: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/activesupport-6.0.3.2/lib/active_support/testing/parallelization.rb:69:in `block in run_cleanup'
        10: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/activesupport-6.0.3.2/lib/active_support/test_case.rb:130:in `block in parallelize_teardown'
         9: from /home/zw963/Airhost/airhost_ror/test/elasticsearch_test_helper.rb:18:in `block in <class:TestCase>'
         8: from /home/zw963/Airhost/airhost_ror/test/elasticsearch_test_helper.rb:18:in `each'
         7: from /home/zw963/Airhost/airhost_ror/test/elasticsearch_test_helper.rb:19:in `block (2 levels) in <class:TestCase>'
         6: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/searchkick-4.4.1/lib/searchkick/index.rb:25:in `delete'
         5: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/elasticsearch-api-7.5.0/lib/elasticsearch/api/actions/indices/delete.rb:37:in `delete'
         4: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/elasticsearch-api-7.5.0/lib/elasticsearch/api/namespace/common.rb:25:in `perform_request'
         3: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/elasticsearch-transport-7.5.0/lib/elasticsearch/transport/client.rb:152:in `perform_request'
         2: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/elasticsearch-transport-7.5.0/lib/elasticsearch/transport/transport/http/faraday.rb:24:in `perform_request'
         1: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/elasticsearch-transport-7.5.0/lib/elasticsearch/transport/transport/base.rb:333:in `perform_request'
/home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/elasticsearch-transport-7.5.0/lib/elasticsearch/transport/transport/base.rb:205:in `__raise_transport_error': [404] {"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [users_test_20200830160219868]","index_uuid":"EZb12TvfQIKNlljx9te2mg","index":"users_test_20200830160219868"}],"type":"index_not_found_exception","reason":"no such index [users_test_20200830160219868]","index_uuid":"EZb12TvfQIKNlljx9te2mg","index":"users_test_20200830160219868"},"status":404} (Elasticsearch::Transport::Transport::Errors::NotFound)
Traceback (most recent call last):
        22: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/minitest-5.14.1/lib/minitest.rb:68:in `block in autorun'
        21: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/minitest-5.14.1/lib/minitest.rb:138:in `run'
        20: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/activesupport-6.0.3.2/lib/active_support/testing/parallelization.rb:74:in `start'
        19: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/activesupport-6.0.3.2/lib/active_support/testing/parallelization.rb:74:in `map'
        18: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/activesupport-6.0.3.2/lib/active_support/testing/parallelization.rb:74:in `each'
        17: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/activesupport-6.0.3.2/lib/active_support/testing/parallelization.rb:74:in `times'
        16: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/activesupport-6.0.3.2/lib/active_support/testing/parallelization.rb:75:in `block in start'
        15: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/activesupport-6.0.3.2/lib/active_support/testing/parallelization.rb:75:in `fork'
        14: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/activesupport-6.0.3.2/lib/active_support/testing/parallelization.rb:110:in `block (2 levels) in start'
        13: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/activesupport-6.0.3.2/lib/active_support/testing/parallelization.rb:68:in `run_cleanup'
        12: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/activesupport-6.0.3.2/lib/active_support/testing/parallelization.rb:68:in `each'
        11: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/activesupport-6.0.3.2/lib/active_support/testing/parallelization.rb:69:in `block in run_cleanup'
        10: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/activesupport-6.0.3.2/lib/active_support/test_case.rb:130:in `block in parallelize_teardown'
         9: from /home/zw963/Airhost/airhost_ror/test/elasticsearch_test_helper.rb:18:in `block in <class:TestCase>'
         8: from /home/zw963/Airhost/airhost_ror/test/elasticsearch_test_helper.rb:18:in `each'
         7: from /home/zw963/Airhost/airhost_ror/test/elasticsearch_test_helper.rb:19:in `block (2 levels) in <class:TestCase>'
         6: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/searchkick-4.4.1/lib/searchkick/index.rb:27:in `delete'
         5: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/elasticsearch-api-7.5.0/lib/elasticsearch/api/actions/indices/delete.rb:37:in `delete'
         4: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/elasticsearch-api-7.5.0/lib/elasticsearch/api/namespace/common.rb:25:in `perform_request'
         3: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/elasticsearch-transport-7.5.0/lib/elasticsearch/transport/client.rb:152:in `perform_request'
         2: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/elasticsearch-transport-7.5.0/lib/elasticsearch/transport/transport/http/faraday.rb:24:in `perform_request'
         1: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/elasticsearch-transport-7.5.0/lib/elasticsearch/transport/transport/base.rb:333:in `perform_request'
/home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/elasticsearch-transport-7.5.0/lib/elasticsearch/transport/transport/base.rb:205:in `__raise_transport_error': [404] {"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [users_test]","resource.type":"index_or_alias","resource.id":"users_test","index_uuid":"_na_","index":"users_test"}],"type":"index_not_found_exception","reason":"no such index [users_test]","resource.type":"index_or_alias","resource.id":"users_test","index_uuid":"_na_","index":"users_test"},"status":404} (Elasticsearch::Transport::Transport::Errors::NotFound)
ETraceback (most recent call last):
        22: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/minitest-5.14.1/lib/minitest.rb:68:in `block in autorun'
        21: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/minitest-5.14.1/lib/minitest.rb:138:in `run'
        20: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/activesupport-6.0.3.2/lib/active_support/testing/parallelization.rb:74:in `start'
        19: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/activesupport-6.0.3.2/lib/active_support/testing/parallelization.rb:74:in `map'
        18: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/activesupport-6.0.3.2/lib/active_support/testing/parallelization.rb:74:in `each'
        17: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/activesupport-6.0.3.2/lib/active_support/testing/parallelization.rb:74:in `times'
        16: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/activesupport-6.0.3.2/lib/active_support/testing/parallelization.rb:75:in `block in start'
        15: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/activesupport-6.0.3.2/lib/active_support/testing/parallelization.rb:75:in `fork'
        14: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/activesupport-6.0.3.2/lib/active_support/testing/parallelization.rb:110:in `block (2 levels) in start'
        13: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/activesupport-6.0.3.2/lib/active_support/testing/parallelization.rb:68:in `run_cleanup'
        12: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/activesupport-6.0.3.2/lib/active_support/testing/parallelization.rb:68:in `each'
        11: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/activesupport-6.0.3.2/lib/active_support/testing/parallelization.rb:69:in `block in run_cleanup'
        10: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/activesupport-6.0.3.2/lib/active_support/test_case.rb:130:in `block in parallelize_teardown'
         9: from /home/zw963/Airhost/airhost_ror/test/elasticsearch_test_helper.rb:18:in `block in <class:TestCase>'
         8: from /home/zw963/Airhost/airhost_ror/test/elasticsearch_test_helper.rb:18:in `each'
         7: from /home/zw963/Airhost/airhost_ror/test/elasticsearch_test_helper.rb:19:in `block (2 levels) in <class:TestCase>'
         6: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/searchkick-4.4.1/lib/searchkick/index.rb:27:in `delete'
         5: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/elasticsearch-api-7.5.0/lib/elasticsearch/api/actions/indices/delete.rb:37:in `delete'
         4: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/elasticsearch-api-7.5.0/lib/elasticsearch/api/namespace/common.rb:25:in `perform_request'
         3: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/elasticsearch-transport-7.5.0/lib/elasticsearch/transport/client.rb:152:in `perform_request'
         2: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/elasticsearch-transport-7.5.0/lib/elasticsearch/transport/transport/http/faraday.rb:24:in `perform_request'
         1: from /home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/elasticsearch-transport-7.5.0/lib/elasticsearch/transport/transport/base.rb:333:in `perform_request'
/home/zw963/others/.rvm/gems/ruby-2.6.1@airhost_ror/gems/elasticsearch-transport-7.5.0/lib/elasticsearch/transport/transport/base.rb:205:in `__raise_transport_error': [404] {"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [users_test]","resource.type":"index_or_alias","resource.id":"users_test","index_uuid":"_na_","index":"users_test"}],"type":"index_not_found_exception","reason":"no such index [users_test]","resource.type":"index_or_alias","resource.id":"users_test","index_uuid":"_na_","index":"users_test"},"status":404} (Elasticsearch::Transport::Transport::Errors::NotFound)


Finished tests in 5.018999s, 0.1992 tests/s, 0.0000 assertions/s.


Error:
Api::V2::Pms::GuestsControllerTest#test_: #index should list guests in pagination. :
Elasticsearch::Transport::Transport::Errors::NotFound: [404] {"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [users_test]","resource.type":"index_or_alias","resource.id":"users_test","index_uuid":"_na_","index":"users_test"}],"type":"index_not_found_exception","reason":"no such index [users_test]","resource.type":"index_or_alias","resource.id":"users_test","index_uuid":"_na_","index":"users_test"},"status":404}
    test/controllers/api/v2/pms/guests_controller_test.rb:28:in `block (2 levels) in <class:GuestsControllerTest>'
    test/controllers/api/v2/pms/guests_controller_test.rb:30:in `instance_exec'
    test/controllers/api/v2/pms/guests_controller_test.rb:30:in `block in create_test_from_should_hash'
```

**Comment by ankane** [comment]
Hey @zw963, try adding `p Searchkick.index_suffix` to the failing test case to see what it outputs.

**Comment by zw963** [comment]
> Hey @zw963, try adding the following to the failing test case to see what it outputs:
> 
> ```ruby
> p Searchkick.index_suffix
> p User.search_index.name
> ```

I add following code in my test case.

```rb
**************************************************
0
"users_test"
**************************************************
```

Get following result:

```
**************************************************
0
"users_test"
**************************************************
```

Thanks, @ankane

**Comment by ankane** [comment]
It looks like the index name is getting cached before the suffix is added, since the `User` model is loaded before `parallelize_setup` is run (due to `elasticsearch_classes = [User]` being set when the test helper loads). 

Try using a method for `elasticsearch_classes`.

```ruby
class ActiveSupport::TestCase
  def elasticsearch_classes
    [User]
  end

  parallelize_setup do |worker|
    Searchkick.index_suffix = worker

    elasticsearch_classes.each do |klass|
      klass.reindex
    end
  end
end
```

**Comment by zw963** [comment]
Sorry, still not working. https://dpaste.com/3NAJGJJPA

Following is my code.

```rb
class ActiveSupport::TestCase
  parallelize_setup do |worker|
    Searchkick.index_suffix = worker
    puts "Searchkick.index_suffix = #{Searchkick.index_suffix}"
    User.reindex
    Searchkick.disable_callbacks
  end

  parallelize_teardown do
    User.search_index.delete
  end
end

```

**Comment by ankane** [comment]
My best guess is the `User` class is being loaded somewhere else before `parallelize_setup` runs. You can try adding a `puts` statement to the top of the class to check. Another thing you could try is:

```ruby
class User
  searchkick index_prefix: -> { }
end
```

which should prevent the index name from being cached.

**Comment by zw963** [comment]
After add above config,  test not raise any error anymore, though test still failed because some reason, anyway,
i think this issue get resolved. thank you.
