### ISSUE TITLE
Faraday::TimeoutError during bulk re-index

### ISSUE THREAD

**Issue by kapso** [ankane/searchkick#1462]
Running into `Faraday::TimeoutError` during bulk re-index (via Sidekiq jobs). I am guessing this is most likely due to Elasticsearch (v7.10.2) server overload or BulkIndexer `batch_size` - ours is `1000`

I understand I can try increasing Faraday timeout via `Faraday.options.timeout = 2.minutes.to_i`

But I was curious if there's a way to increase the timeout for Faraday from within Searchkick context, that way the timeout for Faraday only changes for Elasticsearch bulk index requests, and not any request (non-Searchkick) originating from Faraday.

Error:
```
2021-02-07T10:40:14.767431+00:00 app[worker_a.8]: E, [2021-02-07T10:40:14.767261 #4] ERROR -- : [ActiveJob] [Searchkick::BulkReindexJob] [fa2446ff-5091-4631-bbc8-6b24dacaed7a] Error performing Searchkick::BulkReindexJob (Job ID: fa2446ff-5091-4631-bbc8-6b24dacaed7a) from Sidekiq(searchkick) in 63963.09ms: Faraday::TimeoutError (request timed out):
2021-02-07T10:40:14.767453+00:00 app[worker_a.8]: /app/vendor/bundle/ruby/2.7.0/gems/typhoeus-1.4.0/lib/typhoeus/adapters/faraday.rb:100:in `block in request'
2021-02-07T10:40:14.767454+00:00 app[worker_a.8]: /app/vendor/bundle/ruby/2.7.0/gems/typhoeus-1.4.0/lib/typhoeus/request/callbacks.rb:146:in `block in execute_callbacks'
2021-02-07T10:40:14.767454+00:00 app[worker_a.8]: /app/vendor/bundle/ruby/2.7.0/gems/typhoeus-1.4.0/lib/typhoeus/request/callbacks.rb:145:in `each'
2021-02-07T10:40:14.767455+00:00 app[worker_a.8]: /app/vendor/bundle/ruby/2.7.0/gems/typhoeus-1.4.0/lib/typhoeus/request/callbacks.rb:145:in `execute_callbacks'
2021-02-07T10:40:14.767455+00:00 app[worker_a.8]: /app/vendor/bundle/ruby/2.7.0/gems/typhoeus-1.4.0/lib/typhoeus/request/operations.rb:35:in `finish'
2021-02-07T10:40:14.767456+00:00 app[worker_a.8]: /app/vendor/bundle/ruby/2.7.0/gems/typhoeus-1.4.0/lib/typhoeus/easy_factory.rb:164:in `block in set_callback'
2021-02-07T10:40:14.767456+00:00 app[worker_a.8]: /app/vendor/bundle/ruby/2.7.0/gems/ethon-0.12.0/lib/ethon/easy/response_callbacks.rb:68:in `block in complete'
2021-02-07T10:40:14.767456+00:00 app[worker_a.8]: /app/vendor/bundle/ruby/2.7.0/gems/ethon-0.12.0/lib/ethon/easy/response_callbacks.rb:68:in `each'
2021-02-07T10:40:14.767457+00:00 app[worker_a.8]: /app/vendor/bundle/ruby/2.7.0/gems/ethon-0.12.0/lib/ethon/easy/response_callbacks.rb:68:in `complete'
2021-02-07T10:40:14.767458+00:00 app[worker_a.8]: /app/vendor/bundle/ruby/2.7.0/gems/ddtrace-0.45.0/lib/ddtrace/contrib/ethon/easy_patch.rb:62:in `complete'
2021-02-07T10:40:14.767459+00:00 app[worker_a.8]: /app/vendor/bundle/ruby/2.7.0/gems/ethon-0.12.0/lib/ethon/easy/operations.rb:33:in `perform'
2021-02-07T10:40:14.767459+00:00 app[worker_a.8]: /app/vendor/bundle/ruby/2.7.0/gems/ddtrace-0.45.0/lib/ddtrace/contrib/ethon/easy_patch.rb:40:in `perform'
2021-02-07T10:40:14.767459+00:00 app[worker_a.8]: /app/vendor/bundle/ruby/2.7.0/gems/typhoeus-1.4.0/lib/typhoeus/request/operations.rb:16:in `run'
2021-02-07T10:40:14.767460+00:00 app[worker_a.8]: /app/vendor/bundle/ruby/2.7.0/gems/typhoeus-1.4.0/lib/typhoeus/request/cacheable.rb:18:in `run'
2021-02-07T10:40:14.767461+00:00 app[worker_a.8]: /app/vendor/bundle/ruby/2.7.0/gems/typhoeus-1.4.0/lib/typhoeus/request/block_connection.rb:31:in `run'
2021-02-07T10:40:14.767461+00:00 app[worker_a.8]: /app/vendor/bundle/ruby/2.7.0/gems/typhoeus-1.4.0/lib/typhoeus/request/stubbable.rb:25:in `run'
2021-02-07T10:40:14.767462+00:00 app[worker_a.8]: /app/vendor/bundle/ruby/2.7.0/gems/typhoeus-1.4.0/lib/typhoeus/request/before.rb:26:in `run'
2021-02-07T10:40:14.767462+00:00 app[worker_a.8]: /app/vendor/bundle/ruby/2.7.0/gems/typhoeus-1.4.0/lib/typhoeus/adapters/faraday.rb:82:in `perform_request'
2021-02-07T10:40:14.767463+00:00 app[worker_a.8]: /app/vendor/bundle/ruby/2.7.0/gems/typhoeus-1.4.0/lib/typhoeus/adapters/faraday.rb:72:in `call'
2021-02-07T10:40:14.767463+00:00 app[worker_a.8]: /app/vendor/bundle/ruby/2.7.0/gems/searchkick-4.4.2/lib/searchkick/middleware.rb:9:in `call'
2021-02-07T10:40:14.767464+00:00 app[worker_a.8]: /app/vendor/bundle/ruby/2.7.0/gems/faraday-1.3.0/lib/faraday/rack_builder.rb:154:in `build_response'
2021-02-07T10:40:14.767464+00:00 app[worker_a.8]: /app/vendor/bundle/ruby/2.7.0/gems/faraday-1.3.0/lib/faraday/connection.rb:492:in `run_request'
2021-02-07T10:40:14.767465+00:00 app[worker_a.8]: /app/vendor/bundle/ruby/2.7.0/gems/elasticsearch-transport-7.10.1/lib/elasticsearch/transport/transport/http/faraday.rb:40:in `block in perform_request'
```

Gemfile:
```
ruby 2.7.2

gem 'rails', '6.1.1'
gem 'sidekiq', '6.1.3'

gem 'searchjoy', '0.5.1'
gem 'searchkick', '4.4.2'
gem 'typhoeus', '1.4.0'
```

**Comment by ankane** [comment]
Hey @kapso, this should already be supported. Check out the readme for timeout options.

**Comment by ankane** [comment]
Cleaning up issues
