### ISSUE TITLE
Searchkick::ImportError when IDs are UUIDs (strings) instead of integers

### ISSUE THREAD

**Issue by arimendelow** [ankane/searchkick#1479]
Basically, my models use UUIDs instead of normal integer IDs. When making an object and trying to index it, Searchkick throws the following error - it looks like it's expecting the ID to be type long, but it's a string - how can I change the ID type in Searchkick?

Thanks!
```
Searchkick::ImportError: {"type"=>"mapper_parsing_exception", "reason"=>"failed to parse field [orderer_ids] of type [long] in document with id '812bdfce-a526-40fa-93ef-13418d866fdd'. Preview of field's value: '812bdfce-a526-40fa-93ef-13418d866fdd'", "caused_by"=>{"type"=>"illegal_argument_exception", "reason"=>"For input string: \"812bdfce-a526-40fa-93ef-13418d866fdd\""}} on item with id '812bdfce-a526-40fa-93ef-13418d866fdd'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/searchkick-4.4.1/lib/searchkick/indexer.rb:23:in `perform'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/searchkick-4.4.1/lib/searchkick/logging.rb:126:in `perform'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/searchkick-4.4.1/lib/searchkick/indexer.rb:11:in `queue'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/searchkick-4.4.1/lib/searchkick/bulk_indexer.rb:43:in `bulk_index'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/searchkick-4.4.1/lib/searchkick/index.rb:132:in `store'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/searchkick-4.4.1/lib/searchkick/logging.rb:28:in `block in store'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/notifications.rb:180:in `block in instrument'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/notifications.rb:180:in `instrument'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/searchkick-4.4.1/lib/searchkick/logging.rb:27:in `store'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/searchkick-4.4.1/lib/searchkick/record_indexer.rb:74:in `reindex_record'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/searchkick-4.4.1/lib/searchkick/record_indexer.rb:51:in `reindex'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/searchkick-4.4.1/lib/searchkick/model.rb:83:in `reindex'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:428:in `block in make_lambda'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:263:in `block in conditional'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:517:in `block in invoke_after'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:517:in `each'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:517:in `invoke_after'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:136:in `run_callbacks'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:825:in `_run_commit_callbacks'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.2/lib/active_record/transactions.rb:339:in `committed!'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/transaction.rb:127:in `commit_records'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/transaction.rb:265:in `block in commit_transaction'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/transaction.rb:255:in `commit_transaction'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/transaction.rb:293:in `block in within_new_transaction'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/transaction.rb:278:in `within_new_transaction'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/database_statements.rb:280:in `transaction'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.2/lib/active_record/transactions.rb:212:in `transaction'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.2/lib/active_record/transactions.rb:366:in `with_transaction_returning_status'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.2/lib/active_record/transactions.rb:314:in `save'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.2/lib/active_record/suppressor.rb:44:in `save'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.2/lib/active_record/persistence.rb:38:in `create'
/Users/arimendelow/Documents/code/sj/sj-api/db/seeds.rb:18:in `<main>'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:55:in `load'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:55:in `load'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:318:in `block in load'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:291:in `load_dependency'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:318:in `load'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/railties-6.0.3.2/lib/rails/engine.rb:557:in `block in load_seed'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/railties-6.0.3.2/lib/rails/engine.rb:675:in `with_inline_jobs'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/railties-6.0.3.2/lib/rails/engine.rb:557:in `load_seed'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.2/lib/active_record/tasks/database_tasks.rb:440:in `load_seed'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.2/lib/active_record/railties/databases.rake:331:in `block (2 levels) in <main>'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/railties-6.0.3.2/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/railties-6.0.3.2/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/railties-6.0.3.2/lib/rails/command.rb:48:in `invoke'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/railties-6.0.3.2/lib/rails/commands.rb:18:in `<main>'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:324:in `block in require'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:291:in `load_dependency'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:324:in `require'
/Users/arimendelow/Documents/code/sj/sj-api/bin/rails:11:in `<top (required)>'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `load'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `call'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/spring-2.1.0/bin/spring:49:in `<top (required)>'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `load'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `<top (required)>'
/Users/arimendelow/Documents/code/sj/sj-api/bin/spring:16:in `require'
```

**Comment by arimendelow** [comment]
Update: this seems to be an issue specifically when using `orderer_ids`

**Comment by arimendelow** [comment]
Update: bombing Elasticsearch fixed this. Thanks!

**Comment by ankane** [comment]
It sounds like the mapping was out-of-date. Be sure to run `Model.reindex` after changing `search_data`.

**Comment by arimendelow** [comment]
Right, that's a good point too :)
