### ISSUE TITLE
How can I debug the following error? `Only call searchkick once per model`

### ISSUE THREAD

**Issue by arimendelow** [ankane/searchkick#1480]
Very strangely, upon switching to using UUIDs, some models that trigger GraphQL subscriptions throw the following error: `Only call searchkick once per model`.

I have confirmed that searchkick is definitely not being called more than once in any model. This error message isn't shown if using integer IDs or if I disable the GQL subscriptions trigger.

Making no changes other than commenting out the `GraphqlSchema.subscriptions.trigger` call fixes the error. However, that is not a permanent fix, as I need the subscriptions triggered.

I'm using the [graphql-ruby](https://github.com/rmosolgo/graphql-ruby) gem, and you can read more about the subscriptions trigger [here](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/subscriptions.rb).

Here is an example stacktrace:
```
rails aborted!
Only call searchkick once per model
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/searchkick-4.4.1/lib/searchkick/model.rb:13:in `searchkick'
/Users/arimendelow/Documents/code/sj/sj-api/app/models/recipe.rb:12:in `<class:Recipe>'
/Users/arimendelow/Documents/code/sj/sj-api/app/models/recipe.rb:3:in `<main>'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:324:in `block in require'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:289:in `block in load_dependency'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:701:in `new_constants_in'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:289:in `load_dependency'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:324:in `require'
/Users/arimendelow/Documents/code/sj/sj-api/app/graphql/mutations/recipe/create_or_edit_recipe.rb:3:in `<main>'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:55:in `load'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:55:in `load'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:510:in `block in load_file'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:701:in `new_constants_in'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:509:in `load_file'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:406:in `block in require_or_load'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:40:in `block in load_interlock'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/dependencies/interlock.rb:13:in `loading'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:40:in `load_interlock'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:389:in `require_or_load'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/active_support.rb:49:in `block in require_or_load'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/active_support.rb:17:in `allow_bootsnap_retry'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/active_support.rb:48:in `require_or_load'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:544:in `load_missing_constant'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/active_support.rb:61:in `block in load_missing_constant'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/active_support.rb:17:in `allow_bootsnap_retry'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/active_support.rb:60:in `load_missing_constant'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:214:in `const_missing'
/Users/arimendelow/Documents/code/sj/sj-api/app/graphql/types/mutation_type.rb:27:in `<class:MutationType>'
/Users/arimendelow/Documents/code/sj/sj-api/app/graphql/types/mutation_type.rb:5:in `<module:Types>'
/Users/arimendelow/Documents/code/sj/sj-api/app/graphql/types/mutation_type.rb:3:in `<main>'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:55:in `load'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:55:in `load'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:510:in `block in load_file'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:701:in `new_constants_in'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:509:in `load_file'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:406:in `block in require_or_load'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:40:in `block in load_interlock'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/dependencies/interlock.rb:13:in `loading'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:40:in `load_interlock'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:389:in `require_or_load'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/active_support.rb:49:in `block in require_or_load'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/active_support.rb:17:in `allow_bootsnap_retry'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/active_support.rb:48:in `require_or_load'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:544:in `load_missing_constant'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/active_support.rb:61:in `block in load_missing_constant'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/active_support.rb:17:in `allow_bootsnap_retry'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/active_support.rb:60:in `load_missing_constant'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:214:in `const_missing'
/Users/arimendelow/Documents/code/sj/sj-api/app/graphql/graphql_schema.rb:16:in `<class:GraphqlSchema>'
/Users/arimendelow/Documents/code/sj/sj-api/app/graphql/graphql_schema.rb:3:in `<main>'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:55:in `load'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:55:in `load'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:510:in `block in load_file'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:701:in `new_constants_in'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:509:in `load_file'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:406:in `block in require_or_load'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:40:in `block in load_interlock'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/dependencies/interlock.rb:13:in `loading'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:40:in `load_interlock'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:389:in `require_or_load'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/active_support.rb:49:in `block in require_or_load'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/active_support.rb:17:in `allow_bootsnap_retry'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/active_support.rb:48:in `require_or_load'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:544:in `load_missing_constant'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/active_support.rb:61:in `block in load_missing_constant'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/active_support.rb:17:in `allow_bootsnap_retry'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/active_support.rb:60:in `load_missing_constant'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:214:in `const_missing'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:581:in `load_missing_constant'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/active_support.rb:61:in `block in load_missing_constant'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/active_support.rb:17:in `allow_bootsnap_retry'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/active_support.rb:60:in `load_missing_constant'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:214:in `const_missing'
/Users/arimendelow/Documents/code/sj/sj-api/app/models/notification.rb:39:in `notify_create'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:428:in `block in make_lambda'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:273:in `block in simple'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:517:in `block in invoke_after'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:517:in `each'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:517:in `invoke_after'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:136:in `run_callbacks'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:825:in `_run_commit_callbacks'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.2/lib/active_record/transactions.rb:339:in `committed!'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/transaction.rb:127:in `commit_records'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/transaction.rb:265:in `block in commit_transaction'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/transaction.rb:255:in `commit_transaction'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/transaction.rb:293:in `block in within_new_transaction'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/transaction.rb:278:in `within_new_transaction'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/database_statements.rb:280:in `transaction'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.2/lib/active_record/transactions.rb:212:in `transaction'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.2/lib/active_record/associations/collection_association.rb:134:in `transaction'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.2/lib/active_record/associations/collection_association.rb:344:in `_create_record'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.2/lib/active_record/associations/has_many_association.rb:115:in `_create_record'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.2/lib/active_record/associations/association.rb:199:in `create!'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.2/lib/active_record/associations/collection_proxy.rb:363:in `create!'
/Users/arimendelow/Documents/code/sj/sj-api/db/seeds.rb:145:in `block (2 levels) in <main>'
/Users/arimendelow/Documents/code/sj/sj-api/db/seeds.rb:144:in `times'
/Users/arimendelow/Documents/code/sj/sj-api/db/seeds.rb:144:in `block in <main>'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.2/lib/active_record/relation/delegation.rb:87:in `each'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.2/lib/active_record/relation/delegation.rb:87:in `each'
/Users/arimendelow/Documents/code/sj/sj-api/db/seeds.rb:143:in `<main>'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:55:in `load'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:55:in `load'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:318:in `block in load'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:291:in `load_dependency'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:318:in `load'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/railties-6.0.3.2/lib/rails/engine.rb:557:in `block in load_seed'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/railties-6.0.3.2/lib/rails/engine.rb:675:in `with_inline_jobs'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/railties-6.0.3.2/lib/rails/engine.rb:557:in `load_seed'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.2/lib/active_record/tasks/database_tasks.rb:440:in `load_seed'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.2/lib/active_record/railties/databases.rake:331:in `block (2 levels) in <main>'
/Users/arimendelow/.rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `block in execute'
/Users/arimendelow/.rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `each'
/Users/arimendelow/.rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `execute'
/Users/arimendelow/.rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/Users/arimendelow/.rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:199:in `synchronize'
/Users/arimendelow/.rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
/Users/arimendelow/.rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:243:in `block in invoke_prerequisites'
/Users/arimendelow/.rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:241:in `each'
/Users/arimendelow/.rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:241:in `invoke_prerequisites'
/Users/arimendelow/.rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
/Users/arimendelow/.rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:199:in `synchronize'
/Users/arimendelow/.rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
/Users/arimendelow/.rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:243:in `block in invoke_prerequisites'
/Users/arimendelow/.rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:241:in `each'
/Users/arimendelow/.rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:241:in `invoke_prerequisites'
/Users/arimendelow/.rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
/Users/arimendelow/.rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:199:in `synchronize'
/Users/arimendelow/.rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
/Users/arimendelow/.rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:188:in `invoke'
/Users/arimendelow/.rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:160:in `invoke_task'
/Users/arimendelow/.rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/Users/arimendelow/.rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `each'
/Users/arimendelow/.rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `block in top_level'
/Users/arimendelow/.rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:125:in `run_with_threads'
/Users/arimendelow/.rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:110:in `top_level'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/railties-6.0.3.2/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/Users/arimendelow/.rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/railties-6.0.3.2/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/railties-6.0.3.2/lib/rails/command.rb:48:in `invoke'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/railties-6.0.3.2/lib/rails/commands.rb:18:in `<main>'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:324:in `block in require'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:291:in `load_dependency'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:324:in `require'
/Users/arimendelow/Documents/code/sj/sj-api/bin/rails:11:in `<top (required)>'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `load'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `call'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/spring-2.1.0/bin/spring:49:in `<top (required)>'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `load'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `<top (required)>'
/Users/arimendelow/Documents/code/sj/sj-api/bin/spring:16:in `require'
/Users/arimendelow/Documents/code/sj/sj-api/bin/spring:16:in `<top (required)>'
bin/rails:5:in `load'
bin/rails:5:in `<main>'
Tasks: TOP => db:reset => db:setup => db:seed
```

Thanks!

**Comment by ankane** [comment]
Hey @arimendelow, my guess is the app is loading the model multiple times. I'd try adding debugging to the model. You also try forking the gem and adding debugging around here: https://github.com/ankane/searchkick/blob/a9b57db1ff4dedcac82cc7cf0ebf7d0891d99a6e/lib/searchkick/model.rb#L13

**Comment by arimendelow** [comment]
Sounds good, thanks! Any idea why would using string ids instead of integer ids would cause something like this?

**Comment by arimendelow** [comment]
Ah, one of my graphql resolvers was importing a couple of my models, and recent updates seems to not make this necessary anymore. Removing those imports seems to have fixed this. Unsure why string ids brought this issue to life, but happy we were able to resolve it! Thanks for the help!
