### ISSUE TITLE
Reindex error when there's a custom mapped filterable field whose type does not support ignore_above parameter

### ISSUE THREAD

**Issue by mdesantis** [ankane/searchkick#1611]
**Describe the bug**
As per title: reindexing breaks when there's a custom mapped filterable field whose type does not support ignore_above parameter. For instance, suppose you have a `price` field, you set is as a filterable field, and you have the following `.searchkick` configuration which includes custom mapping for it:

```ruby
  searchkick merge_mappings: true,
             mappings: {
              properties: {
                price: { type: 'scaled_float', scaling_factor: 100 }
              }
             },
             filterable: [:price]
```

When you run `Model.reindex`, you get the following error:

```
gems/opensearch-transport-2.1.0/lib/opensearch/transport/transport/base.rb:227:in `__raise_transport_error': [400] {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"unknown parameter [ignore_above] on mapper [price] of type [scaled_float]"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [_doc]: unknown parameter [ignore_above] on mapper [price] of type [scaled_float]","caused_by":{"type":"mapper_parsing_exception","reason":"unknown parameter [ignore_above] on mapper [price] of type [scaled_float]"}},"status":400} (OpenSearch::Transport::Transport::Errors::BadRequest)
	from gems/opensearch-transport-2.1.0/lib/opensearch/transport/transport/base.rb:356:in `perform_request'
	from gems/opensearch-transport-2.1.0/lib/opensearch/transport/transport/http/faraday.rb:45:in `perform_request'
	from gems/opensearch-transport-2.1.0/lib/opensearch/transport/client.rb:193:in `perform_request'
	from gems/opensearch-ruby-2.1.0/lib/opensearch.rb:48:in `method_missing'
	from gems/opensearch-api-2.1.0/lib/opensearch/api/namespace/common.rb:47:in `perform_request'
	from gems/opensearch-api-2.1.0/lib/opensearch/api/actions/indices/create.rb:56:in `create'
	from bundler/gems/searchkick-52b5bda0d8de/lib/searchkick/index.rb:16:in `create'
	from bundler/gems/searchkick-52b5bda0d8de/lib/searchkick/index.rb:260:in `create_index'
	from bundler/gems/searchkick-52b5bda0d8de/lib/searchkick/index.rb:364:in `full_reindex'
	from bundler/gems/searchkick-52b5bda0d8de/lib/searchkick/index.rb:253:in `reindex'
	from bundler/gems/searchkick-52b5bda0d8de/lib/searchkick/model.rb:77:in `searchkick_reindex'
	from main.rb:37:in `<main>'
```

**To reproduce**
Use this code to reproduce when possible:

```ruby
require "bundler/inline"

gemfile do
  source "https://rubygems.org"

  gem "activerecord", require: "active_record"
  gem "activejob", require: "active_job"
  gem "sqlite3"
  gem "searchkick", git: "https://github.com/ankane/searchkick.git"
  # uncomment one
  # gem "elasticsearch"
  gem "opensearch-ruby"
end

puts "Searchkick version: #{Searchkick::VERSION}"
puts "Server version: #{Searchkick.server_version}"

ActiveRecord::Base.establish_connection adapter: "sqlite3", database: ":memory:"
ActiveJob::Base.queue_adapter = :inline

ActiveRecord::Schema.define do
  create_table :cars do |t|
    t.decimal :price
  end
end

class Car < ActiveRecord::Base
  searchkick merge_mappings: true,
             mappings: {
              properties: {
                price: { type: 'scaled_float', scaling_factor: 100 }
              }
             },
             filterable: [:price]
end

Car.reindex
Car.create!(price: 12.34)
Car.search_index.refresh
p Car.search("*", where: { price: 12.34 }).response
p Car.search("*", where: { price: 23.45 }).response
```

**Additional context**

- It happens also with `float` type, and with any other type which doesn't support `ignore_above` parameter I guess.

- It happens on both ES and OS. 

- The following quick-and-dirty workaround fixes it (just to show you the lines causing the issue):

```diff
diff --git a/lib/searchkick/index_options.rb b/lib/searchkick/index_options.rb
index f7cdf4e..73d2b01 100644
--- a/lib/searchkick/index_options.rb
+++ b/lib/searchkick/index_options.rb
@@ -373,7 +373,14 @@ def generate_mappings
         if options.key?(:filterable) && !mapping_options[:filterable].include?(field)
           fields[field] = {type: default_type, index: false}
         else
-          fields[field] = keyword_mapping
+          types_not_supporting_ignore_above_parameter = %w[float scaled_float]
+          type = options[:mappings]&.dig(:properties, field.to_sym, :type)
+          fields[field] =
+            if types_not_supporting_ignore_above_parameter.include?(type)
+              keyword_mapping.slice(*keyword_mapping.keys - [:ignore_above])
+            else
+              keyword_mapping
+            end
         end
 
         if !options[:searchable] || mapping_options[:searchable].include?(field)
```

**Comment by ankane** [comment]
Hey @mdesantis, non-string fields shouldn't be passed to `filterable`, as mentioned in the docs: https://github.com/ankane/searchkick#filterable-fields

**Comment by mdesantis** [comment]
Makes sense, going to try that! I miss that part of the docs. By the way let me take advantage of this issue to thank you for this well-rounded gem :)
