### ISSUE TITLE
Results#build_hits may have issues with multi-model search?

### ISSUE THREAD

**Issue by geoffharcourt** [ankane/searchkick#1622]
**First**
I didn't find an existing report that matched this issue.

**Describe the bug**
In our CI suite, we're sometimes seeing unexpected failures, I suspect when the indices haven't been cleaned up. The exception is occurring when `#model_name` is being called on the missing records. It looks like in a multi-model search that the call to `#model_name` is being made against an array of models when the search of more than one model, so the method is undefined.

**To reproduce**
Use this code to reproduce when possible:

I'm still trying to reproduce this in a smaller test case. This is giving the right warning but not throwing an exception as I'm hoping.

```ruby
require "bundler/inline"

gemfile do
  source "https://rubygems.org"

  gem "activerecord", require: "active_record"
  gem "activejob", require: "active_job"
  gem "sqlite3"
  gem "searchkick", git: "https://github.com/ankane/searchkick.git"
  # uncomment one
  # gem "elasticsearch"
  gem "opensearch-ruby"
end

puts "Searchkick version: #{Searchkick::VERSION}"
puts "Server version: #{Searchkick.server_version}"

ActiveRecord::Base.establish_connection adapter: "sqlite3", database: ":memory:"
ActiveJob::Base.queue_adapter = :inline

ActiveRecord::Schema.define do
  create_table :products do |t|
    t.string :name
  end

  create_table :items do |t|
    t.string :name
  end
end

class Item < ActiveRecord::Base
  searchkick
end

class Product < ActiveRecord::Base
  searchkick
end

Item.reindex(refresh: true)
Product.reindex(refresh: true)
Item.create!(name: "Test")
Product.create!(name: "Test")
Item.search_index.refresh
Product.search_index.refresh

Searchkick.disable_callbacks
Item.delete_all

p Searchkick.search("test", fields: [:name], models: [Item, Product]).results
```

**Additional context**
Here's the failure from our CI suite when we're calling `Searchkick.search(query_term, options).results`:

```


NoMethodError:
--
  | undefined method `model_name' for [Unit(id: integer, unit_type_uid: integer, slug: string, title: string, description: text, vision_of_mastery: string, activities_overview: text, min_length: integer, max_length: integer, created_at: datetime, updated_at: datetime, engaging_description: text, restricted_access: boolean, grade_id: integer, video_url: string, position: integer, skill_recommendations: text, arc_of_writing_instruction: text, arc_of_reading_instruction: text, supporting_resources_and_guidance: text, instruction_type: integer, state: integer, edition_id: integer, originator_id: integer, book_club_resources: text, supplemental_texts_resources: text, unit_overview: text, culminating_task_description: text), Unit(id: integer, unit_type_uid: integer, slug: string, title: string, description: text, vision_of_mastery: string, activities_overview: text, min_length: integer, max_length: integer, created_at: datetime, updated_at: datetime, engaging_description: text, restricted_access: boolean, grade_id: integer, video_url: string, position: integer, skill_recommendations: text, arc_of_writing_instruction: text, arc_of_reading_instruction: text, supporting_resources_and_guidance: text, instruction_type: integer, state: integer, edition_id: integer, originator_id: integer, book_club_resources: text, supplemental_texts_resources: text, unit_overview: text, culminating_task_description: text)]:Array
  |  
  | [Screenshot Image]: /app/tmp/capybara/failures_r_spec_example_groups_teacher_view_search_library_views_search_results_can_filter_by_all__supplemental_or_curriculum_units_only_471.png
  |  
  |  
  | # /bundle/ruby/3.2.0/gems/searchkick-5.2.2/lib/searchkick/results.rb:307:in `block in build_hits'
  | # /bundle/ruby/3.2.0/gems/searchkick-5.2.2/lib/searchkick/results.rb:307:in `map'
  | # /bundle/ruby/3.2.0/gems/searchkick-5.2.2/lib/searchkick/results.rb:307:in `build_hits'
  | # /bundle/ruby/3.2.0/gems/searchkick-5.2.2/lib/searchkick/results.rb:25:in `with_hit'
  | # /bundle/ruby/3.2.0/gems/searchkick-5.2.2/lib/searchkick/results.rb:19:in `each'
  | # /bundle/ruby/3.2.0/gems/searchkick-5.2.2/lib/searchkick/results.rb:19:in `map'
  | # /bundle/ruby/3.2.0/gems/searchkick-5.2.2/lib/searchkick/results.rb:19:in `results'
  | # ./app/services/search/library.rb:108:in `block (2 levels) in execute_search'
```

**Comment by ankane** [comment]
Hi @geoffharcourt, I'm not sure how to reproduce the error, but feel free to create a new issue if you figure out how (I'd try logging `options` when the error occurs).

**Comment by geoffharcourt** [comment]
Still no small reproduction yet, but some data from what it looks like when this happens. We have a missing record that's not in the database but is in the index, and then `#build_hits` fails because it gets an array of two models for the `:model` in an item in the results collection.

When we fail for `EnglishText #1` missing from the database, these is `missing_records`:

```ruby
[
  {
    :id=>"1",
    :model=>EnglishText(a_bunch_of_attributes...),
  },
  {
    :id=>"1",
    :model=>[
      Unit(a_bunch_of_attributes...),
      Unit(a_bunch_of_attributes...),
    ],
  },
]
```

In the `options` I noticed that the `index_mapping` for the `units_test` index is an array with `Unit` specified twice:

```
:index_mapping=>{"english_texts_test"=>[EnglishText(a_bunch_of_attributes...)], "units_test"=>[Unit(a_bunch_of_attributes..., Unit(a_bunch_of_attributes...)]
```

We have two models that inherit from the same base class, and I'm wondering if that's somehow resulting in the duplication in the array being built up. I'm not sure if deduplicating the models in `Query#params` would fix this or not. Continuing to investigate.

**Comment by ankane** [comment]
Just pushed a fix. Thanks for reporting!

**Comment by geoffharcourt** [comment]
Thank you @ankane this was plaguing our CI!
