### ISSUE TITLE
While using opensearch-ruby got error: end of file reached (Faraday::ConnectionFailed)

### ISSUE THREAD

**Issue by theodor85** [ankane/searchkick#1656]
**Describe the bug**
I try to use the last versions of searchkick gem and opensearch-ruby gem. But cannot establish connection to Opensearch.

In 4.6.3 is the same problem 

**To reproduce**
Use this code to reproduce:

```ruby
require "bundler/inline"

gemfile do
  source "https://rubygems.org"

  gem "activerecord", require: "active_record"
  gem "activejob", require: "active_job"
  gem "sqlite3"
  gem 'searchkick', '~> 5.3', '>= 5.3.0'
  gem 'opensearch-ruby', '~> 3.0', '>= 3.0.1'
end

puts "Searchkick version: #{Searchkick::VERSION}"
ENV["OPENSEARCH_URL"] = 'http://0.0.0.0:9200'

puts "Server version: #{Searchkick.server_version}"
```

I have my Opensearch server up and runnig on 9200 port (in docker container) and I can reach it by curl.

But I get an error in last string (invoking `Searchkick.server_version`):

```
/home/ted/.rvm/rubies/ruby-3.1.0/lib/ruby/3.1.0/net/protocol.rb:227:in `rbuf_fill': end of file reached (Faraday::ConnectionFailed)
        from /home/ted/.rvm/rubies/ruby-3.1.0/lib/ruby/3.1.0/net/protocol.rb:193:in `readuntil'
        from /home/ted/.rvm/rubies/ruby-3.1.0/lib/ruby/3.1.0/net/protocol.rb:203:in `readline'
        from /home/ted/.rvm/rubies/ruby-3.1.0/lib/ruby/3.1.0/net/http/response.rb:42:in `read_status_line'
        from /home/ted/.rvm/rubies/ruby-3.1.0/lib/ruby/3.1.0/net/http/response.rb:31:in `read_new'
        from /home/ted/.rvm/rubies/ruby-3.1.0/lib/ruby/3.1.0/net/http.rb:1575:in `block in transport_request'
        from /home/ted/.rvm/rubies/ruby-3.1.0/lib/ruby/3.1.0/net/http.rb:1566:in `catch'
        from /home/ted/.rvm/rubies/ruby-3.1.0/lib/ruby/3.1.0/net/http.rb:1566:in `transport_request'
        from /home/ted/.rvm/rubies/ruby-3.1.0/lib/ruby/3.1.0/net/http.rb:1539:in `request'
        from /home/ted/.rvm/gems/ruby-3.1.0@empty/gems/faraday-net_http-3.0.2/lib/faraday/adapter/net_http.rb:113:in `block in request_with_wrapped_block'
        from /home/ted/.rvm/rubies/ruby-3.1.0/lib/ruby/3.1.0/net/http.rb:966:in `start'
        from /home/ted/.rvm/gems/ruby-3.1.0@empty/gems/faraday-net_http-3.0.2/lib/faraday/adapter/net_http.rb:112:in `request_with_wrapped_block'
        from /home/ted/.rvm/gems/ruby-3.1.0@empty/gems/faraday-net_http-3.0.2/lib/faraday/adapter/net_http.rb:102:in `perform_request'
        from /home/ted/.rvm/gems/ruby-3.1.0@empty/gems/faraday-net_http-3.0.2/lib/faraday/adapter/net_http.rb:66:in `block in call'
        from /home/ted/.rvm/gems/ruby-3.1.0@empty/gems/faraday-2.7.11/lib/faraday/adapter.rb:45:in `connection'
        from /home/ted/.rvm/gems/ruby-3.1.0@empty/gems/faraday-net_http-3.0.2/lib/faraday/adapter/net_http.rb:65:in `call'
        from /home/ted/.rvm/gems/ruby-3.1.0@empty/gems/searchkick-5.3.0/lib/searchkick/middleware.rb:16:in `call'
        from /home/ted/.rvm/gems/ruby-3.1.0@empty/gems/faraday-2.7.11/lib/faraday/rack_builder.rb:153:in `build_response'
        from /home/ted/.rvm/gems/ruby-3.1.0@empty/gems/faraday-2.7.11/lib/faraday/connection.rb:444:in `run_request'
        from /home/ted/.rvm/gems/ruby-3.1.0@empty/gems/opensearch-ruby-3.0.1/lib/opensearch/transport/transport/http/faraday.rb:56:in `block in perform_request'
        from /home/ted/.rvm/gems/ruby-3.1.0@empty/gems/opensearch-ruby-3.0.1/lib/opensearch/transport/transport/base.rb:299:in `perform_request'
        from /home/ted/.rvm/gems/ruby-3.1.0@empty/gems/opensearch-ruby-3.0.1/lib/opensearch/transport/transport/http/faraday.rb:45:in `perform_request'
        from /home/ted/.rvm/gems/ruby-3.1.0@empty/gems/opensearch-ruby-3.0.1/lib/opensearch/transport/client.rb:193:in `perform_request'
        from /home/ted/.rvm/gems/ruby-3.1.0@empty/gems/opensearch-ruby-3.0.1/lib/opensearch.rb:92:in `open_search_validation_request'
        from /home/ted/.rvm/gems/ruby-3.1.0@empty/gems/opensearch-ruby-3.0.1/lib/opensearch.rb:59:in `verify_open_search'
        from /home/ted/.rvm/gems/ruby-3.1.0@empty/gems/opensearch-ruby-3.0.1/lib/opensearch.rb:47:in `method_missing'
        from /home/ted/.rvm/gems/ruby-3.1.0@empty/gems/opensearch-ruby-3.0.1/lib/opensearch/api/actions/info.rb:45:in `info'
        from /home/ted/.rvm/gems/ruby-3.1.0@empty/gems/searchkick-5.3.0/lib/searchkick.rb:124:in `server_info'
        from /home/ted/.rvm/gems/ruby-3.1.0@empty/gems/searchkick-5.3.0/lib/searchkick.rb:128:in `server_version'
        from check.rb:19:in `<main>'
/home/ted/.rvm/rubies/ruby-3.1.0/lib/ruby/3.1.0/net/protocol.rb:227:in `rbuf_fill': end of file reached (EOFError)
        from /home/ted/.rvm/rubies/ruby-3.1.0/lib/ruby/3.1.0/net/protocol.rb:193:in `readuntil'
        from /home/ted/.rvm/rubies/ruby-3.1.0/lib/ruby/3.1.0/net/protocol.rb:203:in `readline'
        from /home/ted/.rvm/rubies/ruby-3.1.0/lib/ruby/3.1.0/net/http/response.rb:42:in `read_status_line'
        from /home/ted/.rvm/rubies/ruby-3.1.0/lib/ruby/3.1.0/net/http/response.rb:31:in `read_new'
        from /home/ted/.rvm/rubies/ruby-3.1.0/lib/ruby/3.1.0/net/http.rb:1575:in `block in transport_request'
        from /home/ted/.rvm/rubies/ruby-3.1.0/lib/ruby/3.1.0/net/http.rb:1566:in `catch'
        from /home/ted/.rvm/rubies/ruby-3.1.0/lib/ruby/3.1.0/net/http.rb:1566:in `transport_request'
        from /home/ted/.rvm/rubies/ruby-3.1.0/lib/ruby/3.1.0/net/http.rb:1539:in `request'
        from /home/ted/.rvm/gems/ruby-3.1.0@empty/gems/faraday-net_http-3.0.2/lib/faraday/adapter/net_http.rb:113:in `block in request_with_wrapped_block'
        from /home/ted/.rvm/rubies/ruby-3.1.0/lib/ruby/3.1.0/net/http.rb:966:in `start'
        from /home/ted/.rvm/gems/ruby-3.1.0@empty/gems/faraday-net_http-3.0.2/lib/faraday/adapter/net_http.rb:112:in `request_with_wrapped_block'
        from /home/ted/.rvm/gems/ruby-3.1.0@empty/gems/faraday-net_http-3.0.2/lib/faraday/adapter/net_http.rb:102:in `perform_request'
        from /home/ted/.rvm/gems/ruby-3.1.0@empty/gems/faraday-net_http-3.0.2/lib/faraday/adapter/net_http.rb:66:in `block in call'
        from /home/ted/.rvm/gems/ruby-3.1.0@empty/gems/faraday-2.7.11/lib/faraday/adapter.rb:45:in `connection'
        from /home/ted/.rvm/gems/ruby-3.1.0@empty/gems/faraday-net_http-3.0.2/lib/faraday/adapter/net_http.rb:65:in `call'
        from /home/ted/.rvm/gems/ruby-3.1.0@empty/gems/searchkick-5.3.0/lib/searchkick/middleware.rb:16:in `call'
        from /home/ted/.rvm/gems/ruby-3.1.0@empty/gems/faraday-2.7.11/lib/faraday/rack_builder.rb:153:in `build_response'
        from /home/ted/.rvm/gems/ruby-3.1.0@empty/gems/faraday-2.7.11/lib/faraday/connection.rb:444:in `run_request'
        from /home/ted/.rvm/gems/ruby-3.1.0@empty/gems/opensearch-ruby-3.0.1/lib/opensearch/transport/transport/http/faraday.rb:56:in `block in perform_request'
        from /home/ted/.rvm/gems/ruby-3.1.0@empty/gems/opensearch-ruby-3.0.1/lib/opensearch/transport/transport/base.rb:299:in `perform_request'
        from /home/ted/.rvm/gems/ruby-3.1.0@empty/gems/opensearch-ruby-3.0.1/lib/opensearch/transport/transport/http/faraday.rb:45:in `perform_request'
        from /home/ted/.rvm/gems/ruby-3.1.0@empty/gems/opensearch-ruby-3.0.1/lib/opensearch/transport/client.rb:193:in `perform_request'
        from /home/ted/.rvm/gems/ruby-3.1.0@empty/gems/opensearch-ruby-3.0.1/lib/opensearch.rb:92:in `open_search_validation_request'
        from /home/ted/.rvm/gems/ruby-3.1.0@empty/gems/opensearch-ruby-3.0.1/lib/opensearch.rb:59:in `verify_open_search'
        from /home/ted/.rvm/gems/ruby-3.1.0@empty/gems/opensearch-ruby-3.0.1/lib/opensearch.rb:47:in `method_missing'
        from /home/ted/.rvm/gems/ruby-3.1.0@empty/gems/opensearch-ruby-3.0.1/lib/opensearch/api/actions/info.rb:45:in `info'
        from /home/ted/.rvm/gems/ruby-3.1.0@empty/gems/searchkick-5.3.0/lib/searchkick.rb:124:in `server_info'
        from /home/ted/.rvm/gems/ruby-3.1.0@empty/gems/searchkick-5.3.0/lib/searchkick.rb:128:in `server_version'
        from check.rb:19:in `<main>'
```

**Comment by theodor85** [comment]
I solved the problem by adding `DISABLE_SECURITY_PLUGIN=true` env variable to Opensearch service in docker-compose. So, now my docker compose looks like:

```
  opensearch:
    image: opensearchproject/opensearch:1.3.13
    ports:
      - "9200:9200"
      - "9600:9600"
    environment:
      - discovery.type=single-node
      - 'DISABLE_SECURITY_PLUGIN=true'
    volumes:
      - opensearch_data:/usr/share/opensearch/data
```

and everything works correctly
