### ISSUE TITLE
ArgumentError: wrong number of arguments (given 0, expected 1)

### ISSUE THREAD

**Issue by sealabcore** [ankane/searchkick#1692]
This is related to this existing bug
https://github.com/ankane/searchkick/issues/1192

**Describe the bug**
When running my test suite I am getting a very frequent intermittent error whenever my tests try to create factories.

```ruby
ArgumentError: wrong number of arguments (given 0, expected 1)
```

**To reproduce**
Hard to reproduce as it requires very specific gems to be installed.

**Additional context**

The original issue mentions that this library isn't compatible with a newer version of `net-http-persistent` and to use `gem 'net-http-persistent', '~>2.9'`, but I was hoping to not have to downgrade my app to an older version of `net-http-persistent` as that version is from 2014.

Can this library be upgraded to use a later version?

Stacktrace

```ruby
ArgumentError: wrong number of arguments (given 0, expected 1)
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/net-protocol-0.2.2/lib/net/protocol.rb:116:in `initialize'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/webmock-3.23.1/lib/webmock/http_lib_adapters/net_http.rb:121:in `new'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/webmock-3.23.1/lib/webmock/http_lib_adapters/net_http.rb:121:in `start_without_connect'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/webmock-3.23.1/lib/webmock/http_lib_adapters/net_http.rb:143:in `start'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/net-http-persistent-4.0.2/lib/net/http/persistent.rb:662:in `start'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/net-http-persistent-4.0.2/lib/net/http/persistent.rb:867:in `reset'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/net-http-persistent-4.0.2/lib/net/http/persistent.rb:604:in `connection_for'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/net-http-persistent-4.0.2/lib/net/http/persistent.rb:892:in `request'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/faraday-net_http_persistent-2.0.2/lib/faraday/adapter/net_http_persistent.rb:68:in `perform_request'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/faraday-net_http-2.1.0/lib/faraday/adapter/net_http.rb:66:in `block in call'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/faraday-2.0.1/lib/faraday/adapter.rb:45:in `connection'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/faraday-net_http-2.1.0/lib/faraday/adapter/net_http.rb:65:in `call'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/faraday_middleware-aws-sigv4-1.0.1/lib/faraday_middleware/request/aws_sigv4.rb:18:in `call'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/searchkick-5.3.1/lib/searchkick/middleware.rb:16:in `call'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/faraday-2.0.1/lib/faraday/rack_builder.rb:153:in `build_response'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/faraday-2.0.1/lib/faraday/connection.rb:445:in `run_request'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/opensearch-ruby-3.4.0/lib/opensearch/transport/transport/http/faraday.rb:56:in `block in perform_request'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/opensearch-ruby-3.4.0/lib/opensearch/transport/transport/base.rb:297:in `perform_request'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/opensearch-ruby-3.4.0/lib/opensearch/transport/transport/http/faraday.rb:45:in `perform_request'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/opensearch-ruby-3.4.0/lib/opensearch/transport/client.rb:191:in `perform_request'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/opensearch-ruby-3.4.0/lib/opensearch.rb:48:in `method_missing'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/opensearch-ruby-3.4.0/lib/opensearch/api/actions/bulk.rb:72:in `bulk'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/searchkick-5.3.1/lib/searchkick/indexer.rb:22:in `perform'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/searchkick-5.3.1/lib/searchkick.rb:226:in `block in callbacks'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/notifications.rb:206:in `block in instrument'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/notifications/instrumenter.rb:58:in `instrument'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/notifications.rb:206:in `instrument'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/searchkick-5.3.1/lib/searchkick.rb:225:in `callbacks'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/searchkick-5.3.1/lib/searchkick/record_indexer.rb:132:in `block in maybe_bulk'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/searchkick-5.3.1/lib/searchkick/record_indexer.rb:154:in `with_retries'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/searchkick-5.3.1/lib/searchkick/record_indexer.rb:131:in `maybe_bulk'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/searchkick-5.3.1/lib/searchkick/record_indexer.rb:92:in `import_inline'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/searchkick-5.3.1/lib/searchkick/record_indexer.rb:79:in `reindex_items'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/searchkick-5.3.1/lib/searchkick/reindex_v2_job.rb:14:in `perform'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activejob-7.1.3.4/lib/active_job/execution.rb:69:in `block in _perform_job'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/bugsnag-6.27.1/lib/bugsnag/integrations/rails/active_job.rb:36:in `block (2 levels) in included'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:130:in `instance_exec'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:130:in `block in run_callbacks'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activejob-traffic_control-0.1.3/lib/active_job/traffic_control/disable.rb:44:in `block (2 levels) in <module:Disable>'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:130:in `instance_exec'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:130:in `block in run_callbacks'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activejob-traffic_control-0.1.3/lib/active_job/traffic_control/throttle.rb:50:in `block (2 levels) in <module:Throttle>'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:130:in `instance_exec'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:130:in `block in run_callbacks'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activejob-traffic_control-0.1.3/lib/active_job/traffic_control/concurrency.rb:56:in `block (2 levels) in <module:Concurrency>'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:130:in `instance_exec'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:130:in `block in run_callbacks'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/i18n-1.14.5/lib/i18n.rb:351:in `with_locale'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activejob-7.1.3.4/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:130:in `instance_exec'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:130:in `block in run_callbacks'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/core_ext/time/zones.rb:65:in `use_zone'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activejob-7.1.3.4/lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:130:in `instance_exec'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:130:in `block in run_callbacks'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:141:in `run_callbacks'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activejob-7.1.3.4/lib/active_job/execution.rb:68:in `_perform_job'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activejob-7.1.3.4/lib/active_job/instrumentation.rb:32:in `_perform_job'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activejob-7.1.3.4/lib/active_job/execution.rb:52:in `perform_now'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activejob-7.1.3.4/lib/active_job/instrumentation.rb:26:in `block in perform_now'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/railties/job_runtime.rb:13:in `block in instrument'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activejob-7.1.3.4/lib/active_job/instrumentation.rb:40:in `block in instrument'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/notifications.rb:206:in `block in instrument'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/notifications/instrumenter.rb:58:in `instrument'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/notifications.rb:206:in `instrument'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activejob-7.1.3.4/lib/active_job/instrumentation.rb:39:in `instrument'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/railties/job_runtime.rb:11:in `instrument'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activejob-7.1.3.4/lib/active_job/instrumentation.rb:26:in `perform_now'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activejob-7.1.3.4/lib/active_job/logging.rb:18:in `block in perform_now'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/tagged_logging.rb:135:in `block in tagged'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/tagged_logging.rb:39:in `tagged'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/tagged_logging.rb:135:in `tagged'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/broadcast_logger.rb:240:in `method_missing'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activejob-7.1.3.4/lib/active_job/logging.rb:25:in `tag_logger'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activejob-7.1.3.4/lib/active_job/logging.rb:18:in `perform_now'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activejob-7.1.3.4/lib/active_job/execution.rb:30:in `block in execute'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activejob-7.1.3.4/lib/active_job/railtie.rb:67:in `block (4 levels) in <class:Railtie>'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/reloader.rb:77:in `block in wrap'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/execution_wrapper.rb:92:in `wrap'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/reloader.rb:74:in `wrap'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activejob-7.1.3.4/lib/active_job/railtie.rb:66:in `block (3 levels) in <class:Railtie>'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:130:in `instance_exec'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:130:in `block in run_callbacks'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:141:in `run_callbacks'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activejob-7.1.3.4/lib/active_job/execution.rb:28:in `execute'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activejob-7.1.3.4/lib/active_job/queue_adapters/sidekiq_adapter.rb:70:in `perform'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/sidekiq-7.3.1/lib/sidekiq/testing.rb:295:in `execute_job'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/sidekiq-7.3.1/lib/sidekiq/testing.rb:290:in `block in process_job'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/sidekiq-7.3.1/lib/sidekiq/middleware/chain.rb:170:in `invoke'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/sidekiq-7.3.1/lib/sidekiq/testing.rb:289:in `process_job'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/sidekiq-7.3.1/lib/sidekiq/testing.rb:99:in `block in atomic_push'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/sidekiq-7.3.1/lib/sidekiq/testing.rb:95:in `each'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/sidekiq-7.3.1/lib/sidekiq/testing.rb:95:in `atomic_push'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/sidekiq-7.3.1/lib/sidekiq/client.rb:229:in `block (2 levels) in raw_push'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/redis-client-0.22.2/lib/redis_client/decorator.rb:51:in `block in pipelined'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/redis-client-0.22.2/lib/redis_client.rb:426:in `pipelined'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/redis-client-0.22.2/lib/redis_client/decorator.rb:51:in `pipelined'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/sidekiq-7.3.1/lib/sidekiq/client.rb:228:in `block in raw_push'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/connection_pool-2.4.1/lib/connection_pool.rb:110:in `block (2 levels) in with'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/connection_pool-2.4.1/lib/connection_pool.rb:109:in `handle_interrupt'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/connection_pool-2.4.1/lib/connection_pool.rb:109:in `block in with'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/connection_pool-2.4.1/lib/connection_pool.rb:106:in `handle_interrupt'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/connection_pool-2.4.1/lib/connection_pool.rb:106:in `with'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/sidekiq-7.3.1/lib/sidekiq/client.rb:225:in `raw_push'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/sidekiq-pro-7.3.1/lib/sidekiq/batch/client.rb:40:in `raw_push'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/sidekiq-7.3.1/lib/sidekiq/client.rb:93:in `push'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/sidekiq-7.3.1/lib/sidekiq/job.rb:372:in `client_push'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/sidekiq-7.3.1/lib/sidekiq/job.rb:209:in `perform_async'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activejob-7.1.3.4/lib/active_job/queue_adapters/sidekiq_adapter.rb:25:in `enqueue'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activejob-7.1.3.4/lib/active_job/enqueuing.rb:97:in `block in enqueue'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activejob-7.1.3.4/lib/active_job/instrumentation.rb:40:in `block in instrument'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/notifications.rb:206:in `block in instrument'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/notifications/instrumenter.rb:58:in `instrument'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/notifications.rb:206:in `instrument'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activejob-7.1.3.4/lib/active_job/instrumentation.rb:39:in `instrument'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activerecord-7.1.3.4/lib/active_record/railties/job_runtime.rb:18:in `instrument'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activejob-7.1.3.4/lib/active_job/instrumentation.rb:21:in `block (2 levels) in <module:Instrumentation>'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:130:in `instance_exec'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:130:in `block in run_callbacks'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/tagged_logging.rb:135:in `block in tagged'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/tagged_logging.rb:39:in `tagged'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/tagged_logging.rb:135:in `tagged'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/broadcast_logger.rb:240:in `method_missing'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activejob-7.1.3.4/lib/active_job/logging.rb:25:in `tag_logger'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activejob-7.1.3.4/lib/active_job/logging.rb:14:in `block (2 levels) in <module:Logging>'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:130:in `instance_exec'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:130:in `block in run_callbacks'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:141:in `run_callbacks'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activejob-7.1.3.4/lib/active_job/enqueuing.rb:93:in `enqueue'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activejob-7.1.3.4/lib/active_job/enqueuing.rb:60:in `perform_later'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/searchkick-5.3.1/lib/searchkick/record_indexer.rb:31:in `reindex'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/searchkick-5.3.1/lib/searchkick/index.rb:346:in `reindex_records'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/searchkick-5.3.1/lib/searchkick/index.rb:218:in `reindex'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/searchkick-5.3.1/lib/searchkick/model.rb:31:in `reindex'
    test/factories/notes.rb:37:in `block (4 levels) in <main>'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/factory_bot-6.4.6/lib/factory_bot/callback.rb:13:in `instance_exec'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/factory_bot-6.4.6/lib/factory_bot/callback.rb:13:in `run'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/factory_bot-6.4.6/lib/factory_bot/callbacks_observer.rb:11:in `block in update'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/factory_bot-6.4.6/lib/factory_bot/callbacks_observer.rb:10:in `each'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/factory_bot-6.4.6/lib/factory_bot/callbacks_observer.rb:10:in `update'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/factory_bot-6.4.6/lib/factory_bot/evaluation.rb:20:in `notify'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/factory_bot-6.4.6/lib/factory_bot/strategy/create.rb:13:in `block in result'
    <internal:kernel>:90:in `tap'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/factory_bot-6.4.6/lib/factory_bot/strategy/create.rb:9:in `result'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/factory_bot-6.4.6/lib/factory_bot/factory.rb:43:in `run'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/factory_bot-6.4.6/lib/factory_bot/factory_runner.rb:29:in `block in run'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.4/lib/active_support/notifications.rb:208:in `instrument'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/factory_bot-6.4.6/lib/factory_bot/factory_runner.rb:28:in `run'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/factory_bot-6.4.6/lib/factory_bot/strategy_syntax_method_registrar.rb:28:in `block in define_singular_strategy_method'
    test/workers/bulk_remove_from_search_index_worker_test.rb:9:in `block (2 levels) in <class:BulkRemoveFromSearchIndexWorkerTest>'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/sidekiq-7.3.1/lib/sidekiq/testing.rb:23:in `__set_test_mode'
    /Users/miketaylor/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/sidekiq-7.3.1/lib/sidekiq/testing.rb:53:in `inline!'
    test/workers/bulk_remove_from_search_index_worker_test.rb:8:in `block in <class:BulkRemoveFromSearchIndexWorkerTest>'
```

**Comment by ankane** [comment]
Hi @sealabcore, check out https://github.com/ankane/searchkick/issues/1192#issuecomment-419123341 (I'm not sure if it's still the case, but it's not an issue with Searchkick).

**Comment by sealabcore** [comment]
For future readers, this was actually an issue with the Webmock library. My patch is here:

https://github.com/bblimke/webmock/pull/1067
