### ISSUE TITLE
Problems Reindexing with Rails 4

### ISSUE THREAD

**Issue by mstruve** [ankane/searchkick#196]
I had an [issue](https://github.com/ankane/searchkick/issues/153) before with an outdated multi-json not parsing things correctly but I got that problem resolved with a Rails upgrade.  However now I am running into an elasticsearch problem when I try to reindex.

I am using searchkick version 0.7.4 and Rails 4.0.4.

Model Setup:

```
class Deal < ActiveRecord::Base  
  searchkick

  def search_data
    {
      product_name: product_name,
      brand_name: brand_name
    }
  end
end
```

Trace:

```
aisle50(dev)> Deal.reindex
  Deal Load (52.4ms)  SELECT "deals".* FROM "deals" WHERE "deals"."deleted" = 'f' ORDER BY "deals"."id" ASC LIMIT 1000
Elasticsearch::Transport::Transport::Errors::BadRequest: [400] {"error":"Unexpected end-of-input: expected close marker for OBJECT (from [Source: [B@45dbd25c; line: 1, column: 0])\n at [Source: [B@45dbd25c; line: 1, column: 3]"}
        from /Users/mollystruve/.rvm/gems/ruby-1.9.3-p545@aisle50web/gems/elasticsearch-transport-0.4.11/lib/elasticsearch/transport/transport/base.rb:132:in `__raise_transport_error'
        from /Users/mollystruve/.rvm/gems/ruby-1.9.3-p545@aisle50web/gems/elasticsearch-transport-0.4.11/lib/elasticsearch/transport/transport/base.rb:227:in `perform_request'
        from /Users/mollystruve/.rvm/gems/ruby-1.9.3-p545@aisle50web/gems/elasticsearch-transport-0.4.11/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
        from /Users/mollystruve/.rvm/gems/ruby-1.9.3-p545@aisle50web/gems/elasticsearch-transport-0.4.11/lib/elasticsearch/transport/client.rb:92:in `perform_request'
        from /Users/mollystruve/.rvm/gems/ruby-1.9.3-p545@aisle50web/gems/elasticsearch-api-0.4.11/lib/elasticsearch/api/actions/bulk.rb:81:in `bulk'
        from /Users/mollystruve/.rvm/gems/ruby-1.9.3-p545@aisle50web/gems/searchkick-0.7.4/lib/searchkick/index.rb:44:in `block in import'
        from /Users/mollystruve/.rvm/gems/ruby-1.9.3-p545@aisle50web/gems/searchkick-0.7.4/lib/searchkick/index.rb:43:in `each'
        from /Users/mollystruve/.rvm/gems/ruby-1.9.3-p545@aisle50web/gems/searchkick-0.7.4/lib/searchkick/index.rb:43:in `import'
        from /Users/mollystruve/.rvm/gems/ruby-1.9.3-p545@aisle50web/gems/searchkick-0.7.4/lib/searchkick/reindex.rb:60:in `block in searchkick_import'
        from /Users/mollystruve/.rvm/gems/ruby-1.9.3-p545@aisle50web/gems/activerecord-4.0.4/lib/active_record/relation/batches.rb:76:in `find_in_batches'
        from /Users/mollystruve/.rvm/gems/ruby-1.9.3-p545@aisle50web/gems/activerecord-deprecated_finders-1.0.3/lib/active_record/deprecated_finders/relation.rb:70:in `find_in_batches'
        from /Users/mollystruve/.rvm/gems/ruby-1.9.3-p545@aisle50web/gems/activerecord-4.0.4/lib/active_record/querying.rb:8:in `find_in_batches'
        from /Users/mollystruve/.rvm/gems/ruby-1.9.3-p545@aisle50web/gems/searchkick-0.7.4/lib/searchkick/reindex.rb:59:in `searchkick_import'
        from /Users/mollystruve/.rvm/gems/ruby-1.9.3-p545@aisle50web/gems/searchkick-0.7.4/lib/searchkick/reindex.rb:17:in `reindex'
        from (irb):2
        from /Users/mollystruve/.rvm/gems/ruby-1.9.3-p545@aisle50web/gems/railties-4.0.4/lib/rails/commands/console.rb:90:in `start'
        from /Users/mollystruve/.rvm/gems/ruby-1.9.3-p545@aisle50web/gems/railties-4.0.4/lib/rails/commands/console.rb:9:in `start'
        from /Users/mollystruve/.rvm/gems/ruby-1.9.3-p545@aisle50web/gems/railties-4.0.4/lib/rails/commands.rb:62:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
```

If I switch back to searchkick version 0.5.3 which is what I was using prior to the rails 4 upgrade, with rails 4 then I end up with the below trace:

```
aisle50(dev)> Deal.reindex
  Deal Load (26.1ms)  SELECT "deals".* FROM "deals" WHERE "deals"."deleted" = 'f' ORDER BY "deals"."id" ASC LIMIT 1000
[ERROR] 400 > {"error":"Unexpected end-of-input: expected close marker for OBJECT (from [Source: [B@57e52afd; line: 1, column: 0])\n at [Source: [B@57e52afd; line: 1, column: 3]"}, retrying (1)...
[ERROR] 400 > {"error":"Unexpected end-of-input: expected close marker for OBJECT (from [Source: [B@75888b29; line: 1, column: 0])\n at [Source: [B@75888b29; line: 1, column: 3]"}, retrying (2)...
[ERROR] 400 > {"error":"Unexpected end-of-input: expected close marker for OBJECT (from [Source: [B@8ce1366; line: 1, column: 0])\n at [Source: [B@8ce1366; line: 1, column: 3]"}, retrying (3)...
[ERROR] 400 > {"error":"Unexpected end-of-input: expected close marker for OBJECT (from [Source: [B@12d1de09; line: 1, column: 0])\n at [Source: [B@12d1de09; line: 1, column: 3]"}, retrying (4)...
[ERROR] 400 > {"error":"Unexpected end-of-input: expected close marker for OBJECT (from [Source: [B@71dfcbc3; line: 1, column: 0])\n at [Source: [B@71dfcbc3; line: 1, column: 3]"}, retrying (5)...
[ERROR] Too many exceptions occured, giving up. The HTTP response was: 400 > {"error":"Unexpected end-of-input: expected close marker for OBJECT (from [Source: [B@7bd590a3; line: 1, column: 0])\n at [Source: [B@7bd590a3; line: 1, colu
mn: 3]"}
=> true
```

Any suggestions or thoughts? Thanks!

**Comment by DanBradbury** [comment]
I just stumbled on this post and had the exact same issue.. Why are OJs default options throwing such egregious errors on the elasticsearch end? Everything formatted by OJ looks to be correct JSON formatting.

Really sucks that the solution is to remove formatting config just to have elasticsearch play well with others. Anyone else run into a similar issue and have a better workaround? Either way I'll dig into the problem a bit more and see if I can figure out a method that doesn't require the removal of the indent options.
