### ISSUE TITLE
Facets and Ranges

### ISSUE THREAD

**Issue by khelal** [ankane/searchkick#262]
I'm trying to a search using both a regular facet and a range facet:

```
module ProjectSearch
  extend ActiveSupport::Concern

  BUDGET_RANGES = [
    {from: 0, to: 1},
    {from: 1, to: 2_000_000_00},
    {from: 2_000_000_00, to: 5_000_000_00},
    {from: 5_000_000_00, to: 10_000_000_00},
    {from: 10_000_000_00, to: 50_000_000_00},
    {from: 50_000_000_00, to: 100_000_000_00},
    {from: 100_000_000_00}
  ]

  included do
    searchkick

    def self.do_search(query='*')
      projects = Project.search query,
        operator: "or",
        misspellings: true,
        facets: [
          :construction_types,
          budget_cents: {ranges: BUDGET_RANGES}
        ]

      projects.each do |p|
        puts p.title
      end

    end

    # Define how data is indexed
    def search_data
      as_json only: [:title, :description, :construction_types, :budget_cents]
    end

  end

end
```

But I get the following error:

```
2.1.2 :014 > Project.do_search
Searchkick::InvalidQueryError: [400] {"error":"SearchPhaseExecutionException[Failed to execute phase [query], all shards failed; shardFailures {[tLfy7GQsRiyoE3cE8ZjVQw][a_20140821224456017][0]: SearchParseException[[a_20140821224456017][0]: query[ConstantScore(*:*)],from[0],size[100000]: Parse Failure [Failed to parse source [{\"query\":{\"match_all\":{}},\"size\":100000,\"from\":0,\"facets\":{\"construction_types\":{\"terms\":{\"field\":\"construction_types\",\"size\":100000}},\"{:budget_cents=>{:ranges=>[{:from=>0, :to=>1}, {:from=>1, :to=>200000000}, {:from=>200000000, :to=>500000000}, {:from=>500000000, :to=>1000000000}, {:from=>1000000000, :to=>5000000000}, {:from=>5000000000, :to=>10000000000}, {:from=>10000000000}]}}\":{\"terms\":{\"field\":{\"budget_cents\":{\"ranges\":[{\"from\":0,\"to\":1},{\"from\":1,\"to\":200000000},{\"from\":200000000,\"to\":500000000},{\"from\":500000000,\"to\":1000000000},{\"from\":1000000000,\"to\":5000000000},{\"from\":5000000000,\"to\":10000000000},{\"from\":10000000000}]}},\"size\":100000}}},\"fields\":[]}]]]; nested: ElasticsearchParseException[unknown parameter [field] while parsing terms facet [{:budget_cents=>{:ranges=>[{:from=>0, :to=>1}, {:from=>1, :to=>200000000}, {:from=>200000000, :to=>500000000}, {:from=>500000000, :to=>1000000000}, {:from=>1000000000, :to=>5000000000}, {:from=>5000000000, :to=>10000000000}, {:from=>10000000000}]}}]]; }{[tLfy7GQsRiyoE3cE8ZjVQw][a_20140821224456017][1]: SearchParseException[[a_20140821224456017][1]: query[ConstantScore(*:*)],from[0],size[100000]: Parse Failure [Failed to parse source [{\"query\":{\"match_all\":{}},\"size\":100000,\"from\":0,\"facets\":{\"construction_types\":{\"terms\":{\"field\":\"construction_types\",\"size\":100000}},\"{:budget_cents=>{:ranges=>[{:from=>0, :to=>1}, {:from=>1, :to=>200000000}, {:from=>200000000, :to=>500000000}, {:from=>500000000, :to=>1000000000}, {:from=>1000000000, :to=>5000000000}, {:from=>5000000000, :to=>10000000000}, {:from=>10000000000}]}}\":{\"terms\":{\"field\":{\"budget_cents\":{\"ranges\":[{\"from\":0,\"to\":1},{\"from\":1,\"to\":200000000},{\"from\":200000000,\"to\":500000000},{\"from\":500000000,\"to\":1000000000},{\"from\":1000000000,\"to\":5000000000},{\"from\":5000000000,\"to\":10000000000},{\"from\":10000000000}]}},\"size\":100000}}},\"fields\":[]}]]]; nested: ElasticsearchParseException[unknown parameter [field] while parsing terms facet [{:budget_cents=>{:ranges=>[{:from=>0, :to=>1}, {:from=>1, :to=>200000000}, {:from=>200000000, :to=>500000000}, {:from=>500000000, :to=>1000000000}, {:from=>1000000000, :to=>5000000000}, {:from=>5000000000, :to=>10000000000}, {:from=>10000000000}]}}]]; }{[tLfy7GQsRiyoE3cE8ZjVQw][a_20140821224456017][2]: SearchParseException[[a_20140821224456017][2]: query[ConstantScore(*:*)],from[0],size[100000]: Parse Failure [Failed to parse source [{\"query\":{\"match_all\":{}},\"size\":100000,\"from\":0,\"facets\":{\"construction_types\":{\"terms\":{\"field\":\"construction_types\",\"size\":100000}},\"{:budget_cents=>{:ranges=>[{:from=>0, :to=>1}, {:from=>1, :to=>200000000}, {:from=>200000000, :to=>500000000}, {:from=>500000000, :to=>1000000000}, {:from=>1000000000, :to=>5000000000}, {:from=>5000000000, :to=>10000000000}, {:from=>10000000000}]}}\":{\"terms\":{\"field\":{\"budget_cents\":{\"ranges\":[{\"from\":0,\"to\":1},{\"from\":1,\"to\":200000000},{\"from\":200000000,\"to\":500000000},{\"from\":500000000,\"to\":1000000000},{\"from\":1000000000,\"to\":5000000000},{\"from\":5000000000,\"to\":10000000000},{\"from\":10000000000}]}},\"size\":100000}}},\"fields\":[]}]]]; nested: ElasticsearchParseException[unknown parameter [field] while parsing terms facet [{:budget_cents=>{:ranges=>[{:from=>0, :to=>1}, {:from=>1, :to=>200000000}, {:from=>200000000, :to=>500000000}, {:from=>500000000, :to=>1000000000}, {:from=>1000000000, :to=>5000000000}, {:from=>5000000000, :to=>10000000000}, {:from=>10000000000}]}}]]; }{[tLfy7GQsRiyoE3cE8ZjVQw][a_20140821224456017][3]: SearchParseException[[a_20140821224456017][3]: query[ConstantScore(*:*)],from[0],size[100000]: Parse Failure [Failed to parse source [{\"query\":{\"match_all\":{}},\"size\":100000,\"from\":0,\"facets\":{\"construction_types\":{\"terms\":{\"field\":\"construction_types\",\"size\":100000}},\"{:budget_cents=>{:ranges=>[{:from=>0, :to=>1}, {:from=>1, :to=>200000000}, {:from=>200000000, :to=>500000000}, {:from=>500000000, :to=>1000000000}, {:from=>1000000000, :to=>5000000000}, {:from=>5000000000, :to=>10000000000}, {:from=>10000000000}]}}\":{\"terms\":{\"field\":{\"budget_cents\":{\"ranges\":[{\"from\":0,\"to\":1},{\"from\":1,\"to\":200000000},{\"from\":200000000,\"to\":500000000},{\"from\":500000000,\"to\":1000000000},{\"from\":1000000000,\"to\":5000000000},{\"from\":5000000000,\"to\":10000000000},{\"from\":10000000000}]}},\"size\":100000}}},\"fields\":[]}]]]; nested: ElasticsearchParseException[unknown parameter [field] while parsing terms facet [{:budget_cents=>{:ranges=>[{:from=>0, :to=>1}, {:from=>1, :to=>200000000}, {:from=>200000000, :to=>500000000}, {:from=>500000000, :to=>1000000000}, {:from=>1000000000, :to=>5000000000}, {:from=>5000000000, :to=>10000000000}, {:from=>10000000000}]}}]]; }{[tLfy7GQsRiyoE3cE8ZjVQw][a_20140821224456017][4]: SearchParseException[[a_20140821224456017][4]: query[ConstantScore(*:*)],from[0],size[100000]: Parse Failure [Failed to parse source [{\"query\":{\"match_all\":{}},\"size\":100000,\"from\":0,\"facets\":{\"construction_types\":{\"terms\":{\"field\":\"construction_types\",\"size\":100000}},\"{:budget_cents=>{:ranges=>[{:from=>0, :to=>1}, {:from=>1, :to=>200000000}, {:from=>200000000, :to=>500000000}, {:from=>500000000, :to=>1000000000}, {:from=>1000000000, :to=>5000000000}, {:from=>5000000000, :to=>10000000000}, {:from=>10000000000}]}}\":{\"terms\":{\"field\":{\"budget_cents\":{\"ranges\":[{\"from\":0,\"to\":1},{\"from\":1,\"to\":200000000},{\"from\":200000000,\"to\":500000000},{\"from\":500000000,\"to\":1000000000},{\"from\":1000000000,\"to\":5000000000},{\"from\":5000000000,\"to\":10000000000},{\"from\":10000000000}]}},\"size\":100000}}},\"fields\":[]}]]]; nested: ElasticsearchParseException[unknown parameter [field] while parsing terms facet [{:budget_cents=>{:ranges=>[{:from=>0, :to=>1}, {:from=>1, :to=>200000000}, {:from=>200000000, :to=>500000000}, {:from=>500000000, :to=>1000000000}, {:from=>1000000000, :to=>5000000000}, {:from=>5000000000, :to=>10000000000}, {:from=>10000000000}]}}]]; }]","status":400}
    from /Users/khelal/.rvm/gems/ruby-2.1.2@monaqasat/gems/searchkick-0.8.2/lib/searchkick/query.rb:390:in `rescue in execute'
    from /Users/khelal/.rvm/gems/ruby-2.1.2@monaqasat/gems/searchkick-0.8.2/lib/searchkick/query.rb:372:in `execute'
    from /Users/khelal/.rvm/gems/ruby-2.1.2@monaqasat/gems/searchkick-0.8.2/lib/searchkick/logging.rb:11:in `block in execute_with_instrumentation'
    from /Users/khelal/.rvm/gems/ruby-2.1.2@monaqasat/gems/activesupport-3.2.19/lib/active_support/notifications.rb:123:in `block in instrument'
    from /Users/khelal/.rvm/gems/ruby-2.1.2@monaqasat/gems/activesupport-3.2.19/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
    from /Users/khelal/.rvm/gems/ruby-2.1.2@monaqasat/gems/activesupport-3.2.19/lib/active_support/notifications.rb:123:in `instrument'
    from /Users/khelal/.rvm/gems/ruby-2.1.2@monaqasat/gems/searchkick-0.8.2/lib/searchkick/logging.rb:10:in `execute_with_instrumentation'
    from /Users/khelal/.rvm/gems/ruby-2.1.2@monaqasat/gems/searchkick-0.8.2/lib/searchkick/model.rb:29:in `block (2 levels) in searchkick'
    from /Users/khelal/Sites/protenders/app/indexers/project_search.rb:18:in `do_search'
    from (irb):14
    from /Users/khelal/.rvm/gems/ruby-2.1.2@monaqasat/gems/railties-3.2.19/lib/rails/commands/console.rb:47:in `start'
    from /Users/khelal/.rvm/gems/ruby-2.1.2@monaqasat/gems/railties-3.2.19/lib/rails/commands/console.rb:8:in `start'
    from /Users/khelal/.rvm/gems/ruby-2.1.2@monaqasat/gems/railties-3.2.19/lib/rails/commands.rb:41:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'
2.1.2 :015 >
```

Any ideas what I might be doing wrong?

**Comment by cgude** [comment]
What type does the price field need to be in postgres and elasticsearch mapping? Can you pls post your code or shed any insight on how to call the correct ranges in the view?  Been trying to index price ranges as many things, strings, integers, decimals in postgres and various combinations in searchkick indexing but always getting the same error stating number format exception (pasted below).  Also tried different versions of searchkick but no luck.  The main functions of indexing seem to be working fine (show correct count in the range category in the agg view) but when I click on various ranges, does not pass the parameters correctly to the view to show the relevant results that are in that selected range.  Either shows no results or pulls all the records.  Can you pls tell me what I'm doing wrong?  Thanks so much.  Here is the error I keep getting:
[400] {"error":{"root_cause":[{"type":"number_format_exception","reason":"For input string: \"15.0-50.0\""}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query_fetch","grouped":true,"failed_shards":[{"shard":0,"index":"jobs_development_20170114194319648","node":"gKOH56YPR5GYONV84-O92A","reason":{"type":"number_format_exception","reason":"For input string: \"15.0-50.0\""}}]},"status":400}
