### ISSUE TITLE
Reindex failed in last phase (refresh)

### ISSUE THREAD

**Issue by RaVbaker** [ankane/searchkick#297]
I'm not sure it's correct behavior but looks like for me it shouldn't fail whole reindex when previous one disappears. I understand that some other update in mean time causes that but is it ok to fail whole reindex just cause of this? It took for me about 1h to reindex whole DB and it failed in last part. 

```
Elasticsearch::Transport::Transport::Errors::NotFound: [404] {"error":"IndexMissingException[[products_staging_20140829121614298] missing]","status":404}
/home/app/app/shared/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.5/lib/elasticsearch/transport/transport/base.rb:132:in `__raise_transport_error'
/home/app/app/shared/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.5/lib/elasticsearch/transport/transport/base.rb:224:in `perform_request'
/home/app/app/shared/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.5/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
/home/app/app/shared/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.5/lib/elasticsearch/transport/client.rb:104:in `perform_request'
/home/app/app/shared/bundle/jruby/1.9/gems/elasticsearch-api-1.0.5/lib/elasticsearch/api/namespace/common.rb:21:in `perform_request'
/home/app/app/shared/bundle/jruby/1.9/gems/elasticsearch-api-1.0.5/lib/elasticsearch/api/actions/indices/delete.rb:41:in `delete'
/home/app/app/shared/bundle/jruby/1.9/bundler/gems/searchkick-e3967beead10/lib/searchkick/index.rb:14:in `delete'
/home/app/app/shared/bundle/jruby/1.9/bundler/gems/searchkick-e3967beead10/lib/searchkick/reindex.rb:45:in `clean_indices'
/home/app/app/shared/bundle/jruby/1.9/bundler/gems/searchkick-e3967beead10/lib/searchkick/reindex.rb:44:in `clean_indices'
/home/app/app/shared/bundle/jruby/1.9/bundler/gems/searchkick-e3967beead10/lib/searchkick/reindex.rb:26:in `reindex'
```

**Comment by rubyconvict** [comment]
I have a similar problem:

```
$ RAILS_ENV=development RACK_ENV=development bundle exec rake searchkick:reindex:all --trace

** Invoke searchkick:reindex:all (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute searchkick:reindex:all
Reindexing Service...
I, [2015-01-13T10:54:51.338939 #5735]  INFO -- : GET http://127.0.0.1:9200/_aliases [status:404, request:0.003s, query:N/A]
D, [2015-01-13T10:54:51.338974 #5735] DEBUG -- : < {"_index":"http:","_type":"127.0.0.1:9200","_id":"_aliases","found":false}
   curl -X GET 'http://localhost:9200/_aliases?pretty'

   # 2015-01-13T10:54:51+01:00 [404] (0.003s)
   #
   # {"_index":"http:","_type":"127.0.0.1:9200","_id":"_aliases","found":false}

F, [2015-01-13T10:54:51.339163 #5735] FATAL -- : [404] {"_index":"http:","_type":"127.0.0.1:9200","_id":"_aliases","found":false}
rake aborted!
Elasticsearch::Transport::Transport::Errors::NotFound: [404] {"_index":"http:","_type":"127.0.0.1:9200","_id":"_aliases","found":false}
/home/me/project/vendor/bundle/ruby/2.1.0/gems/elasticsearch-transport-1.0.6/lib/elasticsearch/transport/transport/base.rb:132:in `__raise_transport_error'
/home/me/project/vendor/bundle/ruby/2.1.0/gems/elasticsearch-transport-1.0.6/lib/elasticsearch/transport/transport/base.rb:224:in `perform_request'
/home/me/project/vendor/bundle/ruby/2.1.0/gems/elasticsearch-transport-1.0.6/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
/home/me/project/vendor/bundle/ruby/2.1.0/gems/elasticsearch-transport-1.0.6/lib/elasticsearch/transport/client.rb:111:in `perform_request'
/home/me/project/vendor/bundle/ruby/2.1.0/gems/elasticsearch-api-1.0.6/lib/elasticsearch/api/namespace/common.rb:21:in `perform_request'
/home/me/project/vendor/bundle/ruby/2.1.0/gems/elasticsearch-api-1.0.6/lib/elasticsearch/api/actions/indices/get_aliases.rb:29:in `get_aliases'
/home/me/project/vendor/bundle/ruby/2.1.0/gems/searchkick-0.8.5/lib/searchkick/reindex.rb:42:in `clean_indices'
/home/me/project/vendor/bundle/ruby/2.1.0/gems/searchkick-0.8.5/lib/searchkick/reindex.rb:13:in `reindex'
/home/me/project/vendor/bundle/ruby/2.1.0/gems/searchkick-0.8.5/lib/searchkick/tasks.rb:27:in `block (4 levels) in <top (required)>'
/home/me/project/vendor/bundle/ruby/2.1.0/gems/searchkick-0.8.5/lib/searchkick/tasks.rb:25:in `each'
/home/me/project/vendor/bundle/ruby/2.1.0/gems/searchkick-0.8.5/lib/searchkick/tasks.rb:25:in `block (3 levels) in <top (required)>'
/home/me/project/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:240:in `call'
/home/me/project/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:240:in `block in execute'
/home/me/project/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:235:in `each'
/home/me/project/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:235:in `execute'
/home/me/project/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/home/mkalita/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/home/me/project/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/home/me/project/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:165:in `invoke'
/home/me/project/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:150:in `invoke_task'
/home/me/project/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/home/me/project/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:106:in `each'
/home/me/project/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:106:in `block in top_level'
/home/me/project/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:115:in `run_with_threads'
/home/me/project/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:100:in `top_level'
/home/me/project/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:78:in `block in run'
/home/me/project/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:176:in `standard_exception_handling'
/home/me/project/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:75:in `run'
/home/me/project/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/bin/rake:33:in `<top (required)>'
/home/me/project/vendor/bundle/ruby/2.1.0/bin/rake:23:in `load'
/home/me/project/vendor/bundle/ruby/2.1.0/bin/rake:23:in `<main>'
Tasks: TOP => searchkick:reindex:all
```

I just put searchkick in my model:
```
class Service < ActiveRecord::Base
  searchkick
end
```

**Comment by rubyconvict** [comment]
only removing typhoeus gem helped:
https://github.com/ankane/searchkick/issues/362

**Comment by ankane** [comment]
Cleaning up issues. The `reindex` method now has a `resume` option fwiw.
