### ISSUE TITLE
undefined method `status' for true:TrueClass

### ISSUE THREAD

**Issue by proletarian** [ankane/searchkick#327]
Recently updated searchkick, ruby and rails and now I get an error for any command. The response coming back is a boolean down in Patron.

Here's what comes up in the console:

2.1.4 :001 > Product.reindex
D, [2014-11-14T13:05:25.829224 #34253] DEBUG -- : [httplog] Sending: GET http://localhost:9200/_aliases
D, [2014-11-14T13:05:25.833536 #34253] DEBUG -- : [httplog] Status: 200
D, [2014-11-14T13:05:25.833612 #34253] DEBUG -- : [httplog] Benchmark: 0.004146 seconds
D, [2014-11-14T13:05:25.833676 #34253] DEBUG -- : [httplog] Response:
{"users_development_20140816120322202":{"aliases":{"users_development":{}}},"businesses_development_20140704223343387":{"aliases":{"businesses_development":{}}},"products":{"aliases":{}},"products_development_20140731230310652":{"aliases":{"products_development":{}}}}
NoMethodError: undefined method `status' for true:TrueClass
	from /Users/adeel/.rvm/gems/ruby-2.1.4/gems/faraday-0.9.0/lib/faraday/adapter/patron.rb:38:in `call'
	from /Users/adeel/.rvm/gems/ruby-2.1.4/gems/faraday-0.9.0/lib/faraday/rack_builder.rb:139:in `build_response'
	from /Users/adeel/.rvm/gems/ruby-2.1.4/gems/faraday-0.9.0/lib/faraday/connection.rb:377:in `run_request'
	from /Users/adeel/.rvm/gems/ruby-2.1.4/gems/elasticsearch-transport-1.0.6/lib/elasticsearch/transport/transport/http/faraday.rb:21:in `block in perform_request'
	from /Users/adeel/.rvm/gems/ruby-2.1.4/gems/elasticsearch-transport-1.0.6/lib/elasticsearch/transport/transport/base.rb:187:in `call'
	from /Users/adeel/.rvm/gems/ruby-2.1.4/gems/elasticsearch-transport-1.0.6/lib/elasticsearch/transport/transport/base.rb:187:in `perform_request'
	from /Users/adeel/.rvm/gems/ruby-2.1.4/gems/elasticsearch-transport-1.0.6/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
	from /Users/adeel/.rvm/gems/ruby-2.1.4/gems/elasticsearch-transport-1.0.6/lib/elasticsearch/transport/client.rb:111:in `perform_request'
	from /Users/adeel/.rvm/gems/ruby-2.1.4/gems/elasticsearch-api-1.0.6/lib/elasticsearch/api/namespace/common.rb:21:in `perform_request'
	from /Users/adeel/.rvm/gems/ruby-2.1.4/gems/elasticsearch-api-1.0.6/lib/elasticsearch/api/actions/indices/get_aliases.rb:29:in `get_aliases'
	from /Users/adeel/.rvm/gems/ruby-2.1.4/gems/searchkick-0.8.5/lib/searchkick/reindex.rb:42:in `clean_indices'
	from /Users/adeel/.rvm/gems/ruby-2.1.4/gems/searchkick-0.8.5/lib/searchkick/reindex.rb:13:in `reindex'
	from (irb):1
	from /Users/adeel/.rvm/gems/ruby-2.1.4/gems/railties-4.0.11/lib/rails/commands/console.rb:90:in `start'
	from /Users/adeel/.rvm/gems/ruby-2.1.4/gems/railties-4.0.11/lib/rails/commands/console.rb:9:in `start'
	from /Users/adeel/.rvm/gems/ruby-2.1.4/gems/railties-4.0.11/lib/rails/commands.rb:62:in `<top (required)>'
	from script/rails:6:in `require'

**Comment by proletarian** [comment]
Ended up taking out ES for other reasons, closing this. Happy new year!
