### ISSUE TITLE
Indexing a field larger than 32k gives an error in a strange way

### ISSUE THREAD

**Issue by dsandber** [ankane/searchkick#343]
Here's a test case.  An error isn't thrown (based on the print out of "Got here") but the following error/stack-trace is printed (twice).  

Ideally this would either index properly or throw an exception so that the cause of the problem could be easily debugged.

```
[2014-12-12 21:34:09] ERROR Tmp : <Elasticsearch::Transport::Transport::Errors::InternalServerError> [500] {"error":"IllegalArgumentException[Document contains at least one immense term in field=\"description\" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped.  Please correct the analyzer to not produce such terms.  The prefix of the first immense term is: '[97, 111, 122, 105, 106, 111, 105, 106, 119, 101, 10, 97, 111, 122, 105, 106, 111, 105, 106, 119, 101, 10, 97, 111, 122, 105, 106, 111, 105, 106]...', original message: bytes can b
e at most 32766 in length; got 39996]; nested: MaxBytesLengthExceededException[bytes can be at most 32766 in length; got 39996]; ","status":500}
        /Users/dsandber/.rvm/gems/ruby-2.1.5/gems/elasticsearch-transport-1.0.5/lib/elasticsearch/transport/transport/base.rb:132:in `__raise_tr
ansport_error'
        /Users/dsandber/.rvm/gems/ruby-2.1.5/gems/elasticsearch-transport-1.0.5/lib/elasticsearch/transport/transport/base.rb:224:in `perform_re
quest'  
        /Users/dsandber/.rvm/gems/ruby-2.1.5/gems/elasticsearch-transport-1.0.5/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `per
form_request'
        /Users/dsandber/.rvm/gems/ruby-2.1.5/gems/elasticsearch-transport-1.0.5/lib/elasticsearch/transport/client.rb:104:in `perform_request' 
        /Users/dsandber/.rvm/gems/ruby-2.1.5/gems/elasticsearch-api-1.0.5/lib/elasticsearch/api/actions/index.rb:99:in `index'
        /Users/dsandber/.rvm/gems/ruby-2.1.5/gems/searchkick-0.8.3/lib/searchkick/index.rb:26:in `store'
        /Users/dsandber/.rvm/gems/ruby-2.1.5/gems/searchkick-0.8.3/lib/searchkick/logging.rb:24:in `block in store_with_instrumentation'
        /Users/dsandber/.rvm/gems/ruby-2.1.5/gems/activesupport-4.0.5/lib/active_support/notifications.rb:159:in `block in instrument'
        /Users/dsandber/.rvm/gems/ruby-2.1.5/gems/activesupport-4.0.5/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
        /Users/dsandber/.rvm/gems/ruby-2.1.5/gems/activesupport-4.0.5/lib/active_support/notifications.rb:159:in `instrument'
        /Users/dsandber/.rvm/gems/ruby-2.1.5/gems/searchkick-0.8.3/lib/searchkick/logging.rb:23:in `store_with_instrumentation'
        /Users/dsandber/.rvm/gems/ruby-2.1.5/gems/searchkick-0.8.3/lib/searchkick/model.rb:78:in `reindex'
        /Users/dsandber/.rvm/gems/ruby-2.1.5/gems/activesupport-4.0.5/lib/active_support/callbacks.rb:375:in `_run__2161728537592601140__commit_
_callbacks'
        /Users/dsandber/.rvm/gems/ruby-2.1.5/gems/activesupport-4.0.5/lib/active_support/callbacks.rb:80:in `run_callbacks'
        /Users/dsandber/.rvm/gems/ruby-2.1.5/gems/activerecord-4.0.5/lib/active_record/transactions.rb:298:in `committed!'
        /Users/dsandber/.rvm/gems/ruby-2.1.5/gems/activerecord-4.0.5/lib/active_record/connection_adapters/abstract/transaction.rb:147:in `block in commit_records'
        /Users/dsandber/.rvm/gems/ruby-2.1.5/gems/activerecord-4.0.5/lib/active_record/connection_adapters/abstract/transaction.rb:145:in `each'
        /Users/dsandber/.rvm/gems/ruby-2.1.5/gems/activerecord-4.0.5/lib/active_record/connection_adapters/abstract/transaction.rb:145:in `commit_records'
        /Users/dsandber/.rvm/gems/ruby-2.1.5/gems/activerecord-4.0.5/lib/active_record/connection_adapters/abstract/transaction.rb:181:in `perform_commit'
        /Users/dsandber/.rvm/gems/ruby-2.1.5/gems/activerecord-4.0.5/lib/active_record/connection_adapters/abstract/transaction.rb:120:in `commit'
        /Users/dsandber/.rvm/gems/ruby-2.1.5/gems/activerecord-4.0.5/lib/active_record/connection_adapters/abstract/database_statements.rb:247:in `commit_transaction'
        /Users/dsandber/.rvm/gems/ruby-2.1.5/gems/activerecord-4.0.5/lib/active_record/connection_adapters/abstract/database_statements.rb:227:in `within_new_transaction'
        /Users/dsandber/.rvm/gems/ruby-2.1.5/gems/activerecord-4.0.5/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
        /Users/dsandber/.rvm/gems/ruby-2.1.5/gems/activerecord-4.0.5/lib/active_record/transactions.rb:209:in `transaction'
        /Users/dsandber/.rvm/gems/ruby-2.1.5/gems/activerecord-4.0.5/lib/active_record/transactions.rb:327:in `with_transaction_returning_status'
        /Users/dsandber/.rvm/gems/ruby-2.1.5/gems/activerecord-4.0.5/lib/active_record/transactions.rb:270:in `block in save'
        /Users/dsandber/.rvm/gems/ruby-2.1.5/gems/activerecord-4.0.5/lib/active_record/transactions.rb:285:in `rollback_active_record_state!'
        /Users/dsandber/.rvm/gems/ruby-2.1.5/gems/activerecord-4.0.5/lib/active_record/transactions.rb:269:in `save'
        /Users/dsandber/.rvm/gems/ruby-2.1.5/gems/activerecord-4.0.5/lib/active_record/persistence.rb:34:in `create'
        /Users/dsandber/git/jobfusion/app/models/tmp.rb:23:in `make_new'
        (irb):59:in `irb_binding'
        /Users/dsandber/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/irb/workspace.rb:86:in `eval'
        /Users/dsandber/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/irb/workspace.rb:86:in `evaluate'
        /Users/dsandber/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/irb/context.rb:380:in `evaluate'
        /Users/dsandber/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/irb.rb:492:in `block (2 levels) in eval_input'
        /Users/dsandber/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/irb.rb:624:in `signal_status'
        /Users/dsandber/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/irb.rb:489:in `block in eval_input'
        /Users/dsandber/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/irb/ruby-lex.rb:247:in `block (2 levels) in each_top_level_statement'
        /Users/dsandber/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/irb/ruby-lex.rb:233:in `loop'
        /Users/dsandber/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/irb/ruby-lex.rb:233:in `block in each_top_level_statement'
        /Users/dsandber/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/irb/ruby-lex.rb:232:in `catch'
        /Users/dsandber/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/irb/ruby-lex.rb:232:in `each_top_level_statement'
        /Users/dsandber/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/irb.rb:488:in `eval_input'
        /Users/dsandber/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/irb.rb:397:in `block in start'
        /Users/dsandber/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/irb.rb:396:in `catch'
        /Users/dsandber/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/irb.rb:396:in `start'
        /Users/dsandber/.rvm/gems/ruby-2.1.5/gems/railties-4.0.5/lib/rails/commands/console.rb:90:in `start'
        /Users/dsandber/.rvm/gems/ruby-2.1.5/gems/railties-4.0.5/lib/rails/commands/console.rb:9:in `start'
        /Users/dsandber/.rvm/gems/ruby-2.1.5/gems/railties-4.0.5/lib/rails/commands.rb:62:in `<top (required)>'
        bin/rails:4:in `require'
        bin/rails:4:in `<main>'
```

``` ruby
class Tmp < ActiveRecord::Base
  searchkick

  def search_data
    {
        description:description
    }
  end

  def self.make_new
    repeat = "aozijoijwe\n"
    str = repeat * (40000 / repeat.length)
    t = Tmp.create(description:str)
    t.save!
    print "Got here\n"
  end
end
```

**Comment by scrol** [comment]
I got the same issue,[ bytes can be at most 32766 in length; got 96876], how do i fix it?

**Comment by jiteshshetty** [comment]
Folks, I am having the same problem, I am trying to index a huge text blob, do you guys know what is the best way to solve this? I get an error like this:

Elasticsearch::Transport::Transport::Errors::InternalServerError: [500] {"error":"IllegalArgumentException[Document contains at least one immense term in field=\"attachment_body\" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped.  Please correct the analyzer to not produce such terms.  The prefix of the first immense term is: '[10, -62, -87, 32, 50, 48, 49, 52, 32, 65, 109, 97, 122, 111, 110, 32, 87, 101, 98, 32, 83, 101, 114, 118, 105, 99, 101, 115, 44, 32]...', original message: bytes can be at most 32766 in length; got 42511]; nested: MaxBytesLengthExceededException[bytes can be at most 32766 in length; got 42511]; ","status":500}


Thank You.

-Jitesh

**Comment by joostliketoast** [comment]
Having the same problem, Is there anyway to do full text search?(on long articles)

suggested fix on stack is to not index it:
http://stackoverflow.com/questions/24019868/utf8-encoding-is-longer-than-the-max-length-32766
