### ISSUE TITLE
Index missing

### ISSUE THREAD

**Issue by bgvo** [ankane/searchkick#394]
Hi. I'm getting this error:

```
Started GET "/api/v1/search/all?query=jungla+de+cristal" for 83.43.10.32 at 2015-02-16 08:41:06 +0000
2015-02-16T08:41:06.253107+00:00 app[web.1]: Processing by Api::V1::SearchesController#all as HTML
2015-02-16T08:41:06.253113+00:00 app[web.1]:   Parameters: {"query"=>"jungla de cristal"}
2015-02-16T08:41:06.299261+00:00 app[web.1]:   Item Search (45.0ms)  curl http://22591720d1e397263547826347856e4924-eu-west-1.foundcluster.com:9200/items_production/_search?pretty -d '{"query":{"dis_max":{"queries":[{"match":{"n.analyzed":{"query":"jungla de cristal","operator":"and","boost":10,"analyzer":"searchkick_search"}}},{"match":{"n.analyzed":{"query":"jungla de cristal","operator":"and","boost":10,"analyzer":"searchkick_search2"}}},{"match":{"n.analyzed":{"query":"jungla de cristal","operator":"and","boost":1,"fuzziness":1,"max_expansions":3,"analyzer":"searchkick_search"}}},{"match":{"n.analyzed":{"query":"jungla de cristal","operator":"and","boost":1,"fuzziness":1,"max_expansions":3,"analyzer":"searchkick_search2"}}}]}},"size":10,"from":0,"filter":{"and":[{"term":{"dst":"book"}}]},"fields":[]}'
2015-02-16T08:41:06.299401+00:00 app[web.1]: Completed 500 Internal Server Error in 46ms
2015-02-16T08:41:06.300438+00:00 app[web.1]:
2015-02-16T08:41:06.300442+00:00 app[web.1]: Searchkick::MissingIndexError (Index missing - run Item.reindex):
2015-02-16T08:41:06.300443+00:00 app[web.1]:   app/models/item.rb:71:in `search_books'
2015-02-16T08:41:06.300445+00:00 app[web.1]:   app/utils/searchable.rb:9:in `all'
2015-02-16T08:41:06.300447+00:00 app[web.1]:   app/controllers/api/v1/searches_controller.rb:5:in `all'
```

I had an incomplete index (items_production_xxxxx...) so a created again. I notices that what Searchkick was doing was creating a new index (items_production_20150216073919977). So I found myself with two indexes for the same collection. I deleted the first one (the incompleted one) supposing that the new created index was going to be "selected" by default. 

How can I change index name so that my new index is detected (supposing that this is what I have to do)?

Thanks in advance.

**Comment by ankane** [comment]
Searchkick creates an alias when reindexing completes successfully, so run `Item.reindex` again and make sure it completes.

**Comment by paulholladay** [comment]
is there any way to override this behaviour? we really need 2 environments using the same index.
