### ISSUE TITLE
Test fails on fresh install

### ISSUE THREAD

**Issue by adelevie** [ankane/searchkick#435]
```
  1) Error:
TestFacets#test_stats_facets:
Searchkick::InvalidQueryError: [400] {"error":"SearchPhaseExecutionException[Failed to execute phase [query_fetch], all shards failed; shardFailures {[iiGeLL-NREyak6atm324aw][products_test_20150430121039440][0]: SearchParseException[[products_test_20150430121039440][0]: query[+(_all:product^10.0 | _all:product^10.0 | _all:product~1 | _all:product~1) ToParentBlockJoinQuery (filtered(function score (conversions.query:product,function=org.elasticsearch.common.lucene.search.function.FieldValueFactorFunction@2c8a11b0))->random_access(_type:__conversions))],from[0],size[100000]: Parse Failure [Failed to parse source [{\"query\":{\"bool\":{\"must\":{\"dis_max\":{\"queries\":[{\"match\":{\"_all\":{\"query\":\"Product\",\"operator\":\"and\",\"boost\":10,\"analyzer\":\"searchkick_search\"}}},{\"match\":{\"_all\":{\"query\":\"Product\",\"operator\":\"and\",\"boost\":10,\"analyzer\":\"searchkick_search2\"}}},{\"match\":{\"_all\":{\"query\":\"Product\",\"operator\":\"and\",\"boost\":1,\"fuzziness\":1,\"max_expansions\":3,\"analyzer\":\"searchkick_search\"}}},{\"match\":{\"_all\":{\"query\":\"Product\",\"operator\":\"and\",\"boost\":1,\"fuzziness\":1,\"max_expansions\":3,\"analyzer\":\"searchkick_search2\"}}}]}},\"should\":{\"nested\":{\"path\":\"conversions\",\"score_mode\":\"total\",\"query\":{\"function_score\":{\"boost_mode\":\"replace\",\"query\":{\"match\":{\"query\":\"Product\"}},\"field_value_factor\":{\"field\":\"count\"}}}}}}},\"size\":100000,\"from\":0,\"filter\":{\"and\":[{\"term\":{\"store_id\":2}}]},\"facets\":{\"store_id\":{\"terms_stats\":{\"key_field\":\"store_id\",\"value_script\":\"_score\",\"size\":100000}}},\"fields\":[]}]]]; nested: ScriptException[dynamic scripting for [groovy] disabled]; }]","status":400}
    /home/adelevie/searchkick/lib/searchkick/query.rb:438:in `rescue in execute'
    /home/adelevie/searchkick/lib/searchkick/query.rb:420:in `execute'
    /home/adelevie/searchkick/lib/searchkick/index.rb:127:in `search_model'
    /home/adelevie/searchkick/lib/searchkick/model.rb:22:in `block (2 levels) in searchkick'
    /home/adelevie/searchkick/test/facets_test.rb:74:in `test_stats_facets'

171 runs, 257 assertions, 0 failures, 1 errors, 2 skips
```

Using Ubuntu 15.04 fwiw.

**Comment by ankane** [comment]
No longer an issue
