### ISSUE TITLE
Rake Reindexing Internal Server Error 500

### ISSUE THREAD

**Issue by natbatwat** [ankane/searchkick#447]
With elasticsearch server running on another tab, I ran: `rake searchkick:reindex:all` and got:
            
```Reindexing Area...
rake aborted!
Elasticsearch::Transport::Transport::Errors::InternalServerError: [500] {"error":"IndexCreationException[[areas_development_20150525173204528] failed to create index]; nested: FailedToResolveConfigException[Failed to resolve config path [/var/lib/wn_s.pl], tried file path [/var/lib/wn_s.pl], path file [/usr/local/Cellar/elasticsearch/1.5.2/config/var/lib/wn_s.pl], and classpath]; ","status":500}```


For more information with --trace: 
 ```rake searchkick:reindex:all --trace
** Invoke searchkick:reindex:all (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute searchkick:reindex:all
Reindexing Area...
rake aborted!
Elasticsearch::Transport::Transport::Errors::InternalServerError: [500] {"error":"IndexCreationException[[areas_development_20150525173215766] failed to create index]; nested: FailedToResolveConfigException[Failed to resolve config path [/var/lib/wn_s.pl], tried file path [/var/lib/wn_s.pl], path file [/usr/local/Cellar/elasticsearch/1.5.2/config/var/lib/wn_s.pl], and classpath]; ","status":500}
/Users/natalie/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/elasticsearch-transport-1.0.9/lib/elasticsearch/transport/transport/base.rb:132:in `__raise_transport_error'
/Users/natalie/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/elasticsearch-transport-1.0.9/lib/elasticsearch/transport/transport/base.rb:224:in `perform_request'
/Users/natalie/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/elasticsearch-transport-1.0.9/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
/Users/natalie/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/elasticsearch-transport-1.0.9/lib/elasticsearch/transport/client.rb:115:in `perform_request'
/Users/natalie/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/elasticsearch-api-1.0.9/lib/elasticsearch/api/namespace/common.rb:21:in `perform_request'
/Users/natalie/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/elasticsearch-api-1.0.9/lib/elasticsearch/api/actions/indices/create.rb:77:in `create'
/Users/natalie/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/searchkick-0.8.7/lib/searchkick/index.rb:11:in `create'
/Users/natalie/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/searchkick-0.8.7/lib/searchkick/index.rb:132:in `create_index'
/Users/natalie/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/searchkick-0.8.7/lib/searchkick/index.rb:153:in `reindex_scope'
/Users/natalie/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/searchkick-0.8.7/lib/searchkick/model.rb:47:in `reindex'
/Users/natalie/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/searchkick-0.8.7/lib/searchkick/tasks.rb:27:in `block (4 levels) in <top (required)>'
/Users/natalie/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/searchkick-0.8.7/lib/searchkick/tasks.rb:25:in `each'
/Users/natalie/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/searchkick-0.8.7/lib/searchkick/tasks.rb:25:in `block (3 levels) in <top (required)>'
/Users/natalie/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/Users/natalie/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/Users/natalie/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/Users/natalie/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/Users/natalie/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/Users/natalie/.rbenv/versions/2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/Users/natalie/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/Users/natalie/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/Users/natalie/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/Users/natalie/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/Users/natalie/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/Users/natalie/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/Users/natalie/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/Users/natalie/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/Users/natalie/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/Users/natalie/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/Users/natalie/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/Users/natalie/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/Users/natalie/.rbenv/versions/2.1.2/bin/rake:23:in `load'
/Users/natalie/.rbenv/versions/2.1.2/bin/rake:23:in `<main>'
Tasks: TOP => searchkick:reindex:all```

**Comment by ankane** [comment]
Looks like you're trying to use wordnet on a server that doesn't have it installed, or has it installed in a different location than expected.

**Comment by ankane** [comment]
Cleaning up issues.
