### ISSUE TITLE
Can't reindex Rails 4.2.0

### ISSUE THREAD

**Issue by jonathansimmons** [ankane/searchkick#478]
I'm getting the following error when I try to reindex. 

```ruby
[4] pry(main)> Team.reindex
Faraday::ConnectionFailed: wrong status line: "-ERR wrong number of arguments for 'get' command"
from /Users/jonathan/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http/response.rb:41:in `read_status_line'
```

Any help on this is appreciated!

**Comment by jonathansimmons** [comment]
Here is a bigger trace

```ruby
jonathan@Jonathan $ rake searchkick:reindex:all
[Simple Form] Simple Form is not configured in the application and will use the default values. Use `rails generate simple_form:install` to generate the Simple Form configuration.
Reindexing Team...
rake aborted!
Faraday::ConnectionFailed: wrong status line: "-ERR wrong number of arguments for 'get' command"
/Users/jonathan/.rvm/gems/ruby-2.1.2/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:80:in `perform_request'
/Users/jonathan/.rvm/gems/ruby-2.1.2/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:40:in `block in call'
/Users/jonathan/.rvm/gems/ruby-2.1.2/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
/Users/jonathan/.rvm/gems/ruby-2.1.2/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:32:in `call'
/Users/jonathan/.rvm/gems/ruby-2.1.2/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:139:in `build_response'
/Users/jonathan/.rvm/gems/ruby-2.1.2/gems/faraday-0.9.1/lib/faraday/connection.rb:377:in `run_request'
/Users/jonathan/.rvm/gems/ruby-2.1.2/gems/elasticsearch-transport-1.0.12/lib/elasticsearch/transport/transport/http/faraday.rb:21:in `block in perform_request'
/Users/jonathan/.rvm/gems/ruby-2.1.2/gems/elasticsearch-transport-1.0.12/lib/elasticsearch/transport/transport/base.rb:190:in `call'
/Users/jonathan/.rvm/gems/ruby-2.1.2/gems/elasticsearch-transport-1.0.12/lib/elasticsearch/transport/transport/base.rb:190:in `perform_request'
/Users/jonathan/.rvm/gems/ruby-2.1.2/gems/elasticsearch-transport-1.0.12/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
/Users/jonathan/.rvm/gems/ruby-2.1.2/gems/elasticsearch-transport-1.0.12/lib/elasticsearch/transport/client.rb:119:in `perform_request'
/Users/jonathan/.rvm/gems/ruby-2.1.2/gems/elasticsearch-api-1.0.12/lib/elasticsearch/api/namespace/common.rb:21:in `perform_request'
/Users/jonathan/.rvm/gems/ruby-2.1.2/gems/elasticsearch-api-1.0.12/lib/elasticsearch/api/actions/indices/get_aliases.rb:29:in `get_aliases'
/Users/jonathan/.rvm/gems/ruby-2.1.2/gems/searchkick-0.9.0/lib/searchkick/index.rb:141:in `clean_indices'
/Users/jonathan/.rvm/gems/ruby-2.1.2/gems/searchkick-0.9.0/lib/searchkick/index.rb:154:in `reindex_scope'
/Users/jonathan/.rvm/gems/ruby-2.1.2/gems/searchkick-0.9.0/lib/searchkick/model.rb:47:in `reindex'
/Users/jonathan/.rvm/gems/ruby-2.1.2/gems/searchkick-0.9.0/lib/searchkick/tasks.rb:27:in `block (4 levels) in <top (required)>'
/Users/jonathan/.rvm/gems/ruby-2.1.2/gems/searchkick-0.9.0/lib/searchkick/tasks.rb:25:in `each'
/Users/jonathan/.rvm/gems/ruby-2.1.2/gems/searchkick-0.9.0/lib/searchkick/tasks.rb:25:in `block (3 levels) in <top (required)>'
/Users/jonathan/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
/Users/jonathan/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
Net::HTTPBadResponse: wrong status line: "-ERR wrong number of arguments for 'get' command"
/Users/jonathan/.rvm/gems/ruby-2.1.2/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:80:in `perform_request'
/Users/jonathan/.rvm/gems/ruby-2.1.2/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:40:in `block in call'
/Users/jonathan/.rvm/gems/ruby-2.1.2/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
/Users/jonathan/.rvm/gems/ruby-2.1.2/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:32:in `call'
/Users/jonathan/.rvm/gems/ruby-2.1.2/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:139:in `build_response'
/Users/jonathan/.rvm/gems/ruby-2.1.2/gems/faraday-0.9.1/lib/faraday/connection.rb:377:in `run_request'
/Users/jonathan/.rvm/gems/ruby-2.1.2/gems/elasticsearch-transport-1.0.12/lib/elasticsearch/transport/transport/http/faraday.rb:21:in `block in perform_request'
/Users/jonathan/.rvm/gems/ruby-2.1.2/gems/elasticsearch-transport-1.0.12/lib/elasticsearch/transport/transport/base.rb:190:in `call'
/Users/jonathan/.rvm/gems/ruby-2.1.2/gems/elasticsearch-transport-1.0.12/lib/elasticsearch/transport/transport/base.rb:190:in `perform_request'
/Users/jonathan/.rvm/gems/ruby-2.1.2/gems/elasticsearch-transport-1.0.12/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
/Users/jonathan/.rvm/gems/ruby-2.1.2/gems/elasticsearch-transport-1.0.12/lib/elasticsearch/transport/client.rb:119:in `perform_request'
/Users/jonathan/.rvm/gems/ruby-2.1.2/gems/elasticsearch-api-1.0.12/lib/elasticsearch/api/namespace/common.rb:21:in `perform_request'
/Users/jonathan/.rvm/gems/ruby-2.1.2/gems/elasticsearch-api-1.0.12/lib/elasticsearch/api/actions/indices/get_aliases.rb:29:in `get_aliases'
/Users/jonathan/.rvm/gems/ruby-2.1.2/gems/searchkick-0.9.0/lib/searchkick/index.rb:141:in `clean_indices'
/Users/jonathan/.rvm/gems/ruby-2.1.2/gems/searchkick-0.9.0/lib/searchkick/index.rb:154:in `reindex_scope'
/Users/jonathan/.rvm/gems/ruby-2.1.2/gems/searchkick-0.9.0/lib/searchkick/model.rb:47:in `reindex'
/Users/jonathan/.rvm/gems/ruby-2.1.2/gems/searchkick-0.9.0/lib/searchkick/tasks.rb:27:in `block (4 levels) in <top (required)>'
/Users/jonathan/.rvm/gems/ruby-2.1.2/gems/searchkick-0.9.0/lib/searchkick/tasks.rb:25:in `each'
/Users/jonathan/.rvm/gems/ruby-2.1.2/gems/searchkick-0.9.0/lib/searchkick/tasks.rb:25:in `block (3 levels) in <top (required)>'
/Users/jonathan/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
/Users/jonathan/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => searchkick:reindex:all
(See full trace by running task with --trace)

```

An in this attempt I tried using ruby 2.1.2 but it made no difference.

**Comment by jonathansimmons** [comment]
This issue was due to me having a redis server running on 9200 instead of elasticsearch.
