### ISSUE TITLE
nested: QueryParsingException[[match] analyzer [searchkick_search] not found]; }

### ISSUE THREAD

**Issue by dcalixto** [ankane/searchkick#563]
Hi, @ankane  great work!
someone is having this kind of issue?

model: Product
after_touch :reindex
searchkick mappings: {
    product: {
      properties: {
        name: {type: "string", analyzer: "keyword"}
      }
    }
  }
   def search_data
    as_json only: [:name, :price]
    {
      name: name,
      price: price
    }
  end

controller: 
@products = Product.search(params)

elasticsearch log

nested: QueryParsingException[[match] analyzer [searchkick_search] not found]; }
	at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction.onFirstPhaseResult(TransportSearchTypeAction.java:228)
	at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction$1.onFailure(TransportSearchTypeAction.java:174)
	at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:46)
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:821)
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:799)
	at org.elasticsearch.transport.TransportService$4.onFailure(TransportService.java:361)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: [products_development_20151125165517504] QueryParsingException[[match] analyzer [searchkick_search] not found]
	at org.elasticsearch.index.query.MatchQueryParser.parse(MatchQueryParser.java:101)
	at org.elasticsearch.index.query.QueryParseContext.parseInnerQuery(QueryParseContext.java:250)
	at org.elasticsearch.index.query.DisMaxQueryParser.parse(DisMaxQueryParser.java:79)
	at org.elasticsearch.index.query.QueryParseContext.parseInnerQuery(QueryParseContext.java:250)
	at org.elasticsearch.index.query.IndexQueryParserService.innerParse(IndexQueryParserService.java:299)
	at org.elasticsearch.index.query.IndexQueryParserService.parse(IndexQueryParserService.java:202)
	at org.elasticsearch.index.query.IndexQueryParserService.parse(IndexQueryParserService.java:197)
	at org.elasticsearch.search.query.QueryParseElement.parse(QueryParseElement.java:33)
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:843)
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:663)
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:632)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:374)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:368)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:365)
	at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:350)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)

**Comment by ankane** [comment]
If you use a custom mapping, you'll need to use [custom searching](https://github.com/ankane/searchkick#advanced-search) as well.

```ruby
Product.search body: { ... }
```

**Comment by dcalixto** [comment]
Right, thank you very much @ankane
