### ISSUE TITLE
ImportError when doing rake searchkick:reindex:all

### ISSUE THREAD

**Issue by pramodthammaiah** [ankane/searchkick#572]
I'm trying to reindex all my products and run:
heroku run rake searchkick:reindex:all

It's starts to run but then fails with the following error:
```
Product Import (3334.2ms)  {"count":1000,"exception":["Searchkick::ImportError","Searchkick::ImportError"]}
[Rollbar] Scheduling payload
[Rollbar] Sending payload
[Rollbar] Success
[Rollbar] Details: https://rollbar.com/instance/uuid?uuid=b45858c0-b801-4ca3-a1f7-7435601006dd (only available if report was successful)
rake aborted!
Searchkick::ImportError: Searchkick::ImportError
/app/vendor/bundle/ruby/2.2.0/gems/searchkick-1.0.3/lib/searchkick/index.rb:76:in `block in import'
/app/vendor/bundle/ruby/2.2.0/gems/searchkick-1.0.3/lib/searchkick/index.rb:68:in `each'
/app/vendor/bundle/ruby/2.2.0/gems/searchkick-1.0.3/lib/searchkick/index.rb:68:in `import'
/app/vendor/bundle/ruby/2.2.0/gems/searchkick-1.0.3/lib/searchkick/logging.rb:47:in `block in import_with_instrumentation'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `block in instrument'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `instrument'
/app/vendor/bundle/ruby/2.2.0/gems/searchkick-1.0.3/lib/searchkick/logging.rb:46:in `import_with_instrumentation'
/app/vendor/bundle/ruby/2.2.0/gems/searchkick-1.0.3/lib/searchkick/index.rb:193:in `block in import_scope'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/relation/batches.rb:124:in `find_in_batches'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/querying.rb:9:in `find_in_batches'
/app/vendor/bundle/ruby/2.2.0/gems/searchkick-1.0.3/lib/searchkick/index.rb:192:in `import_scope'
/app/vendor/bundle/ruby/2.2.0/gems/searchkick-1.0.3/lib/searchkick/index.rb:168:in `reindex_scope'
/app/vendor/bundle/ruby/2.2.0/gems/searchkick-1.0.3/lib/searchkick/model.rb:51:in `searchkick_reindex'
/app/vendor/bundle/ruby/2.2.0/gems/searchkick-1.0.3/lib/searchkick/tasks.rb:26:in `block (4 levels) in <top (required)>'
/app/vendor/bundle/ruby/2.2.0/gems/searchkick-1.0.3/lib/searchkick/tasks.rb:24:in `each'
/app/vendor/bundle/ruby/2.2.0/gems/searchkick-1.0.3/lib/searchkick/tasks.rb:24:in `block (3 levels) in <top (required)>'
/app/vendor/ruby-2.2.2/lib/ruby/2.2.0/rake/task.rb:240:in `call'
/app/vendor/ruby-2.2.2/lib/ruby/2.2.0/rake/task.rb:240:in `block in execute'
/app/vendor/ruby-2.2.2/lib/ruby/2.2.0/rake/task.rb:235:in `each'
/app/vendor/ruby-2.2.2/lib/ruby/2.2.0/rake/task.rb:235:in `execute'
/app/vendor/ruby-2.2.2/lib/ruby/2.2.0/rake/task.rb:179:in `block in invoke_with_call_chain'
/app/vendor/ruby-2.2.2/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/app/vendor/ruby-2.2.2/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/app/vendor/ruby-2.2.2/lib/ruby/2.2.0/rake/task.rb:165:in `invoke'
/app/vendor/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:150:in `invoke_task'
/app/vendor/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:106:in `block (2 levels) in top_level'
/app/vendor/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:106:in `each'
/app/vendor/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:106:in `block in top_level'
/app/vendor/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:115:in `run_with_threads'
/app/vendor/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:100:in `top_level'
/app/vendor/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:78:in `block in run'
/app/vendor/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/app/vendor/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:75:in `run'
/app/bin/rake:4:in `<main>'
Tasks: TOP => searchkick:reindex:all
```

Bundler tells me I'm running searchkick 1.0.3.

Things were working fine a few weeks ago. I hadn't indexed in a while. Not sure what is causing this problem. Anything I can do to help debug?

**Comment by pramodthammaiah** [comment]
With some additional debugging it looks like there is something wrong with a product I'm trying to reindex:
```
{"id":240358,"exception":["Elasticsearch::Transport::Transport::Errors::InternalServerError","[500] {\"error\":\"IllegalArgumentException[Document contains at least one immense term in field=\\\"long_description\\\" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped.  Please correct the analyzer to not produce such terms.  The prefix of the first immense term is: '[99, 111, 108, 111, 114, 58, 103, 114, 97, 121, 10, 97, 109, 97, 122, 111, 110, 46, 99, 111, 109, 10, 109, 97, 107, 101, 115, 32, 113, 117]...', original message: bytes can be at most 32766 in length; got 85964]; nested: MaxBytesLengthExceededException[bytes can be at most 32766 in length; got 85964]; \",\"status\":500}"]}
```

**Comment by pramodthammaiah** [comment]
This was an issue with some of the characters that were in the description that I was trying to index. Removing them allowed me to reindex fine.
