### ISSUE TITLE
Bulk import failure raises Searchkick::ImportError without a message

### ISSUE THREAD

**Issue by audreyschwarz** [ankane/searchkick#630]
Hi there,

I noticed that Searchkick prints nothing but `Searchkick::ImportError: Searchkick::ImportError` with a rather unhelpful stack trace when bulk importing fails.

The problem is that Searchkick is looking at only the first item returned for the error message, so when the first item is okay but any other items in the batch aren't, ImportError is raised with a nil message. I'll open a PR with a fix.

Thanks for writing this awesome gem--it's saved me a ton of time :)

**Comment by haslinger** [comment]
Probably the same problem here, error message looks like this:

```
Searchkick::ImportError: Searchkick::ImportError
	from /home/stefan/.rvm/gems/ruby-2.1.8/gems/searchkick-1.2.1/lib/searchkick.rb:107:in `perform_items'
	from /home/stefan/.rvm/gems/ruby-2.1.8/gems/searchkick-1.2.1/lib/searchkick/logging.rb:82:in `perform_items'
	from /home/stefan/.rvm/gems/ruby-2.1.8/gems/searchkick-1.2.1/lib/searchkick.rb:98:in `perform_bulk'
	from /home/stefan/.rvm/gems/ruby-2.1.8/gems/searchkick-1.2.1/lib/searchkick.rb:91:in `queue_items'
	from /home/stefan/.rvm/gems/ruby-2.1.8/gems/searchkick-1.2.1/lib/searchkick/index.rb:60:in `bulk_index'
	from /home/stefan/.rvm/gems/ruby-2.1.8/gems/searchkick-1.2.1/lib/searchkick/logging.rb:55:in `block in import'
	from /home/stefan/.rvm/gems/ruby-2.1.8/gems/activesupport-4.2.5.2/lib/active_support/notifications.rb:164:in `block in instrument'
	from /home/stefan/.rvm/gems/ruby-2.1.8/gems/activesupport-4.2.5.2/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
	from /home/stefan/.rvm/gems/ruby-2.1.8/gems/activesupport-4.2.5.2/lib/active_support/notifications.rb:164:in `instrument'
	from /home/stefan/.rvm/gems/ruby-2.1.8/gems/searchkick-1.2.1/lib/searchkick/logging.rb:54:in `import'
	from /home/stefan/.rvm/gems/ruby-2.1.8/gems/searchkick-1.2.1/lib/searchkick/index.rb:195:in `block in import_scope'
	from /home/stefan/.rvm/gems/ruby-2.1.8/gems/activerecord-4.2.5.2/lib/active_record/relation/batches.rb:124:in `find_in_batches'
	from /home/stefan/.rvm/gems/ruby-2.1.8/gems/activerecord-4.2.5.2/lib/active_record/querying.rb:9:in `find_in_batches'
	from /home/stefan/.rvm/gems/ruby-2.1.8/gems/searchkick-1.2.1/lib/searchkick/index.rb:194:in `import_scope'
	from /home/stefan/.rvm/gems/ruby-2.1.8/gems/searchkick-1.2.1/lib/searchkick/index.rb:170:in `reindex_scope'
	from /home/stefan/.rvm/gems/ruby-2.1.8/gems/searchkick-1.2.1/lib/searchkick/model.rb:51:in `searchkick_reindex'
	from (irb):1
	from /home/stefan/.rvm/gems/ruby-2.1.8/gems/railties-4.2.5.2/lib/rails/commands/console.rb:110:in `start'
	from /home/stefan/.rvm/gems/ruby-2.1.8/gems/railties-4.2.5.2/lib/rails/commands/console.rb:9:in `start'
	from /home/stefan/.rvm/gems/ruby-2.1.8/gems/railties-4.2.5.2/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /home/stefan/.rvm/gems/ruby-2.1.8/gems/railties-4.2.5.2/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/stefan/.rvm/gems/ruby-2.1.8/gems/railties-4.2.5.2/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:6:in `require'
	from bin/rails:6:in `<main>'2.1.8 :002 > 
```
