### ISSUE TITLE
Faraday::ConnectionFailed: easy handle already used in multi handle

### ISSUE THREAD

**Issue by chriskaukis** [ankane/searchkick#669]
I am seeing tons of these in our sidekiq logs. I'm not entirely certain if this is an issue with searchkick, but it only seems to happen with the searchkick re-index jobs. Other jobs run fine from what am currently seeing. The problem is this is killing each sidekiq process when it happens.

```
2016-05-03T18:24:35.854Z 31771 TID-gstxedppw Searchkick::ReindexV2Job JID-8e9657a40e49ab7975c8ff1b INFO: start
2016-05-03T18:24:35.861Z 31771 TID-gstxedppw Searchkick::ReindexV2Job JID-8e9657a40e49ab7975c8ff1b INFO: fail: 0.006 sec
2016-05-03T18:24:35.861Z 31771 TID-gstxedppw WARN: {"class"=>"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper", "wrapped"=>"Searchkick::ReindexV2Job", "queue"=>"searchkick", "args"=>[{"job_class"=>"Searchkick::ReindexV2Job", "job_id"=>"3a9157b6-b816-4eb9-b3d2-27e2bf81b1b1", "queue_name"=>"searchkick", "arguments"=>["User", "139234"], "locale"=>"en"}], "retry"=>true, "jid"=>"8e9657a40e49ab7975c8ff1b", "created_at"=>1462294747.0440958, "enqueued_at"=>1462295602.3268888, "error_message"=>"easy handle already used in multi handle", "error_class"=>"Faraday::ConnectionFailed", "failed_at"=>1462295198.90197, "retry_count"=>1, "retried_at"=>1462299875.8605464}
2016-05-03T18:24:35.861Z 31771 TID-gstxedppw WARN: Faraday::ConnectionFailed: easy handle already used in multi handle
2016-05-03T18:24:35.861Z 31771 TID-gstxedppw WARN: /opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/patron-0.5.1/lib/patron/session.rb:216:in `handle_request'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/patron-0.5.1/lib/patron/session.rb:216:in `request'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/adapter/patron.rb:33:in `call'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/faraday_middleware-aws-signers-v4-0.1.5/lib/faraday_middleware/request/aws_signers_v4.rb:57:in `call'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/elasticsearch-transport-1.0.15/lib/elasticsearch/transport/transport/http/faraday.rb:21:in `block in perform_request'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/elasticsearch-transport-1.0.15/lib/elasticsearch/transport/transport/base.rb:201:in `call'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/elasticsearch-transport-1.0.15/lib/elasticsearch/transport/transport/base.rb:201:in `perform_request'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/elasticsearch-transport-1.0.15/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/elasticsearch-transport-1.0.15/lib/elasticsearch/transport/client.rb:125:in `perform_request'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/elasticsearch-api-1.0.15/lib/elasticsearch/api/actions/bulk.rb:87:in `bulk'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/searchkick-1.1.2/lib/searchkick.rb:104:in `perform_items'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/searchkick-1.1.2/lib/searchkick.rb:98:in `perform_bulk'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/searchkick-1.1.2/lib/searchkick.rb:91:in `queue_items'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/searchkick-1.1.2/lib/searchkick/index.rb:60:in `bulk_index'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/searchkick-1.1.2/lib/searchkick/index.rb:48:in `store'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/searchkick-1.1.2/lib/searchkick/logging.rb:24:in `block in store_with_instrumentation'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/notifications.rb:164:in `block in instrument'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/notifications.rb:164:in `instrument'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/searchkick-1.1.2/lib/searchkick/logging.rb:23:in `store_with_instrumentation'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/searchkick-1.1.2/lib/searchkick/reindex_v2_job.rb:19:in `perform'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/activejob-4.2.5/lib/active_job/execution.rb:32:in `block in perform_now'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:117:in `call'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:117:in `call'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:505:in `call'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:505:in `call'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:343:in `call'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:343:in `block (2 levels) in simple'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/i18n-0.7.0/lib/i18n.rb:257:in `with_locale'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/activejob-4.2.5/lib/active_job/translation.rb:7:in `block (2 levels) in <module:Translation>'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:441:in `instance_exec'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:441:in `block in make_lambda'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:342:in `call'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:342:in `block in simple'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:497:in `call'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:497:in `block in around'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:505:in `call'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:505:in `call'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:343:in `call'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:343:in `block (2 levels) in simple'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/activejob-4.2.5/lib/active_job/logging.rb:23:in `call'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/activejob-4.2.5/lib/active_job/logging.rb:23:in `block (4 levels) in <module:Logging>'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/notifications.rb:164:in `block in instrument'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/notifications.rb:164:in `instrument'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/activejob-4.2.5/lib/active_job/logging.rb:22:in `block (3 levels) in <module:Logging>'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/activejob-4.2.5/lib/active_job/logging.rb:45:in `tag_logger'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/activejob-4.2.5/lib/active_job/logging.rb:19:in `block (2 levels) in <module:Logging>'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:441:in `instance_exec'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:441:in `block in make_lambda'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:342:in `call'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:342:in `block in simple'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:497:in `call'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:497:in `block in around'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:505:in `call'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:505:in `call'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:778:in `_run_perform_callbacks'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:81:in `run_callbacks'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/activejob-4.2.5/lib/active_job/execution.rb:31:in `perform_now'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/activejob-4.2.5/lib/active_job/execution.rb:21:in `execute'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/activejob-4.2.5/lib/active_job/queue_adapters/sidekiq_adapter.rb:42:in `perform'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:150:in `execute_job'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:132:in `block (2 levels) in process'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:127:in `block in invoke'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/logging.rb:30:in `with_context'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/server/logging.rb:7:in `call'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:132:in `call'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:132:in `invoke'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:127:in `block in process'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:166:in `stats'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:126:in `process'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:79:in `process_one'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:67:in `run'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/util.rb:16:in `watchdog'
/opt/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/util.rb:24:in `block in safe_thread'
```

Here is my configuration for connecting to our Elasticsearch server (on AWS):

```
  require 'faraday_middleware/aws_signers_v4'
  Searchkick.client = Elasticsearch::Client.new(url: Rails.application.secrets.elasticsearch_host) do |f|
    f.request :aws_signers_v4,
      credentials: Aws::Credentials.new(Rails.application.secrets.aws_access_key_id, Rails.application.secrets.aws_secret_access_key),
      service_name: 'es',
      region: 'us-west-2'
  end
```

And if it matters, here is my sidekiq.yml:

```
:verbose: false
:concurrency: 2
:timeout: 5000
:pidfile: tmp/pids/sidekiq.pid
:logfile: log/sidekiq.log
:queues:
  - critical
  - default
  - mailers
  - low
  - searchkick
```

I'm really not certain where else to ask or get help with this at the moment. I've been troubleshooting all day so far with nothing to go off of. Even a temporary fix or suggestion would be helpful. 

NOTE: We are running multiple server (Ec2) instances behind load balancer on AWS (Redis Elasticache and AWS Elasticsearch for job and search).

**Comment by chriskaukis** [comment]
I continue to see these. Anyone else? Any suggestions or help? It only seems to be with Searchkick.

**Comment by ankane** [comment]
Use typhoeus instead of patron - patron is not thread-safe, which Sidekiq requires.

Instructions here: https://github.com/ankane/searchkick#performance

**Comment by chriskaukis** [comment]
I forgot to say thank you so much. It appears to fixed the problem and is exactly what I thought the issue was related to. I am closing this ticket, sorry to bother. I missed that part of the documentation or it wasn't up when I started using Searchkick.
