### ISSUE TITLE
Searchkick::ImportError

### ISSUE THREAD

**Issue by abcnever** [ankane/searchkick#730]
Hi there, 

After upgrading my elasticsearch from 1.7 to 2.4, I can no longer reindex my data anymore. following is the stack trace: 

```
** Invoke searchkick:reindex:all (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute searchkick:reindex:all
Reindexing User...
rake aborted!
Searchkick::ImportError: {"type"=>"illegal_argument_exception", "reason"=>"mapper [league_score.1] of different type, current_type [long], merged_type [double]"} on item with id '2'
/home/edward/.rvm/gems/ruby-2.2.4@statiscore_server/gems/searchkick-1.3.4/lib/searchkick.rb:113:in `perform_items'
/home/edward/.rvm/gems/ruby-2.2.4@statiscore_server/gems/searchkick-1.3.4/lib/searchkick/logging.rb:82:in `perform_items'
/home/edward/.rvm/gems/ruby-2.2.4@statiscore_server/gems/searchkick-1.3.4/lib/searchkick.rb:102:in `perform_bulk'
/home/edward/.rvm/gems/ruby-2.2.4@statiscore_server/gems/searchkick-1.3.4/lib/searchkick.rb:95:in `queue_items'
/home/edward/.rvm/gems/ruby-2.2.4@statiscore_server/gems/searchkick-1.3.4/lib/searchkick/index.rb:60:in `bulk_index'
/home/edward/.rvm/gems/ruby-2.2.4@statiscore_server/gems/searchkick-1.3.4/lib/searchkick/logging.rb:55:in `block in import'
/home/edward/.rvm/gems/ruby-2.2.4@statiscore_server/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `block in instrument'
/home/edward/.rvm/gems/ruby-2.2.4@statiscore_server/gems/activesupport-4.2.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/edward/.rvm/gems/ruby-2.2.4@statiscore_server/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `instrument'
/home/edward/.rvm/gems/ruby-2.2.4@statiscore_server/gems/searchkick-1.3.4/lib/searchkick/logging.rb:54:in `import'
/home/edward/.rvm/gems/ruby-2.2.4@statiscore_server/gems/searchkick-1.3.4/lib/searchkick/index.rb:229:in `block in import_scope'
/home/edward/.rvm/gems/ruby-2.2.4@statiscore_server/gems/activerecord-4.2.1/lib/active_record/relation/batches.rb:124:in `find_in_batches'
/home/edward/.rvm/gems/ruby-2.2.4@statiscore_server/gems/activerecord-4.2.1/lib/active_record/querying.rb:9:in `find_in_batches'
/home/edward/.rvm/gems/ruby-2.2.4@statiscore_server/gems/searchkick-1.3.4/lib/searchkick/index.rb:228:in `import_scope'
/home/edward/.rvm/gems/ruby-2.2.4@statiscore_server/gems/searchkick-1.3.4/lib/searchkick/index.rb:196:in `reindex_scope'
/home/edward/.rvm/gems/ruby-2.2.4@statiscore_server/gems/searchkick-1.3.4/lib/searchkick/model.rb:53:in `searchkick_reindex'
/home/edward/.rvm/gems/ruby-2.2.4@statiscore_server/gems/searchkick-1.3.4/lib/searchkick/tasks.rb:26:in `block (4 levels) in <top (required)>'
/home/edward/.rvm/gems/ruby-2.2.4@statiscore_server/gems/searchkick-1.3.4/lib/searchkick/tasks.rb:24:in `each'
/home/edward/.rvm/gems/ruby-2.2.4@statiscore_server/gems/searchkick-1.3.4/lib/searchkick/tasks.rb:24:in `block (3 levels) in <top (required)>'
/home/edward/.rvm/gems/ruby-2.2.4@statiscore_server/gems/rake-11.2.2/lib/rake/task.rb:248:in `call'
/home/edward/.rvm/gems/ruby-2.2.4@statiscore_server/gems/rake-11.2.2/lib/rake/task.rb:248:in `block in execute'
/home/edward/.rvm/gems/ruby-2.2.4@statiscore_server/gems/rake-11.2.2/lib/rake/task.rb:243:in `each'
/home/edward/.rvm/gems/ruby-2.2.4@statiscore_server/gems/rake-11.2.2/lib/rake/task.rb:243:in `execute'
/home/edward/.rvm/gems/ruby-2.2.4@statiscore_server/gems/rake-11.2.2/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
/home/edward/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/home/edward/.rvm/gems/ruby-2.2.4@statiscore_server/gems/rake-11.2.2/lib/rake/task.rb:180:in `invoke_with_call_chain'
/home/edward/.rvm/gems/ruby-2.2.4@statiscore_server/gems/rake-11.2.2/lib/rake/task.rb:173:in `invoke'
/home/edward/.rvm/gems/ruby-2.2.4@statiscore_server/gems/rake-11.2.2/lib/rake/application.rb:152:in `invoke_task'
/home/edward/.rvm/gems/ruby-2.2.4@statiscore_server/gems/rake-11.2.2/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/home/edward/.rvm/gems/ruby-2.2.4@statiscore_server/gems/rake-11.2.2/lib/rake/application.rb:108:in `each'
/home/edward/.rvm/gems/ruby-2.2.4@statiscore_server/gems/rake-11.2.2/lib/rake/application.rb:108:in `block in top_level'
/home/edward/.rvm/gems/ruby-2.2.4@statiscore_server/gems/rake-11.2.2/lib/rake/application.rb:117:in `run_with_threads'
/home/edward/.rvm/gems/ruby-2.2.4@statiscore_server/gems/rake-11.2.2/lib/rake/application.rb:102:in `top_level'
/home/edward/.rvm/gems/ruby-2.2.4@statiscore_server/gems/rake-11.2.2/lib/rake/application.rb:80:in `block in run'
/home/edward/.rvm/gems/ruby-2.2.4@statiscore_server/gems/rake-11.2.2/lib/rake/application.rb:178:in `standard_exception_handling'
/home/edward/.rvm/gems/ruby-2.2.4@statiscore_server/gems/rake-11.2.2/lib/rake/application.rb:77:in `run'
/home/edward/.rvm/gems/ruby-2.2.4@statiscore_server/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
/home/edward/.rvm/gems/ruby-2.2.4@statiscore_server/bin/rake:23:in `load'
/home/edward/.rvm/gems/ruby-2.2.4@statiscore_server/bin/rake:23:in `<main>'
/home/edward/.rvm/gems/ruby-2.2.4@statiscore_server/bin/ruby_executable_hooks:15:in `eval'
/home/edward/.rvm/gems/ruby-2.2.4@statiscore_server/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => searchkick:reindex:all
```
Searching with google and in the issue list of this repo did not help me at all. Anyone got an idea?

**Comment by ankane** [comment]
From the error message, it sounds like the `league_score.1` field has values of different types. I'd try casting its values to a float (`to_f`) in your `search_data` method so it's indexed as a `double`.

**Comment by abcnever** [comment]
@ankane thank you very much! that did it.
