### ISSUE TITLE
undefined method `connect_timeout=' for #<Typhoeus::Request:...

### ISSUE THREAD

**Issue by bgvo** [ankane/searchkick#737]
```
2.2.3 :001 > User.reindex
NoMethodError: undefined method `connect_timeout=' for #<Typhoeus::Request:0x007fdbf4d70ff0>
	from /Users/borjagvo/.rvm/gems/ruby-2.2.3/gems/faraday-0.9.2/lib/faraday/adapter/typhoeus.rb:104:in `configure_timeout'
	from /Users/borjagvo/.rvm/gems/ruby-2.2.3/gems/faraday-0.9.2/lib/faraday/adapter/typhoeus.rb:47:in `request'
	from /Users/borjagvo/.rvm/gems/ruby-2.2.3/gems/faraday-0.9.2/lib/faraday/adapter/typhoeus.rb:22:in `perform_request'
	from /Users/borjagvo/.rvm/gems/ruby-2.2.3/gems/faraday-0.9.2/lib/faraday/adapter/typhoeus.rb:14:in `call'
	from /Users/borjagvo/.rvm/gems/ruby-2.2.3/gems/searchkick-1.3.4/lib/searchkick/middleware.rb:9:in `call'
	from /Users/borjagvo/.rvm/gems/ruby-2.2.3/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
	from /Users/borjagvo/.rvm/gems/ruby-2.2.3/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
	from /Users/borjagvo/.rvm/gems/ruby-2.2.3/gems/elasticsearch-transport-2.0.0/lib/elasticsearch/transport/transport/http/faraday.rb:21:in `block in perform_request'
	from /Users/borjagvo/.rvm/gems/ruby-2.2.3/gems/elasticsearch-transport-2.0.0/lib/elasticsearch/transport/transport/base.rb:257:in `call'
	from /Users/borjagvo/.rvm/gems/ruby-2.2.3/gems/elasticsearch-transport-2.0.0/lib/elasticsearch/transport/transport/base.rb:257:in `perform_request'
	from /Users/borjagvo/.rvm/gems/ruby-2.2.3/gems/elasticsearch-transport-2.0.0/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
	from /Users/borjagvo/.rvm/gems/ruby-2.2.3/gems/elasticsearch-transport-2.0.0/lib/elasticsearch/transport/client.rb:127:in `perform_request'
	from /Users/borjagvo/.rvm/gems/ruby-2.2.3/gems/elasticsearch-api-2.0.0/lib/elasticsearch/api/namespace/common.rb:21:in `perform_request'
	from /Users/borjagvo/.rvm/gems/ruby-2.2.3/gems/elasticsearch-api-2.0.0/lib/elasticsearch/api/actions/indices/get_aliases.rb:29:in `get_aliases'
	from /Users/borjagvo/.rvm/gems/ruby-2.2.3/gems/searchkick-1.3.4/lib/searchkick/index.rb:146:in `all_indices'
	from /Users/borjagvo/.rvm/gems/ruby-2.2.3/gems/searchkick-1.3.4/lib/searchkick/index.rb:156:in `clean_indices'
... 4 levels...
	from /Users/borjagvo/.rvm/gems/ruby-2.2.3/gems/railties-4.2.5/lib/rails/commands/console.rb:9:in `start'
	from /Users/borjagvo/.rvm/gems/ruby-2.2.3/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/borjagvo/.rvm/gems/ruby-2.2.3/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/borjagvo/.rvm/gems/ruby-2.2.3/gems/railties-4.2.5/lib/rails/commands.rb:17:in `<top (required)>'
	from /Users/borjagvo/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
	from /Users/borjagvo/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/borjagvo/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/borjagvo/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
	from /Users/borjagvo/MyStuff/webdev/Work/Gemfeed/dev/repos/api/bin/rails:8:in `<top (required)>'
	from /Users/borjagvo/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
	from /Users/borjagvo/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `block in load'
	from /Users/borjagvo/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/borjagvo/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
	from /Users/borjagvo/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/borjagvo/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'2.2.3 :002 > exit
```

I added Typhoeus to my Gemfile. Suddenly, `Model.reindex` stopped working.

**Comment by ankane** [comment]
@bgvo this can be solved by creating an initializer with:

```ruby
require "typhoeus/adapters/faraday"
```

Searchkick should probably do this automatically if typhoeus is detected.

**Comment by ankane** [comment]
Searchkick will load the adapter automatically now.
