### ISSUE TITLE
undefined method `in' for :id:Symbol

### ISSUE THREAD

**Issue by jwoertink** [ankane/searchkick#779]
After getting my results back and trying to see how many records were returned, I get this error:

```text
2.2.0 :006 > results.count
NoMethodError: undefined method `in' for :id:Symbol
	from /Users/jeremywoertink/.rvm/gems/ruby-2.2.0@stan/gems/searchkick-1.4.0/lib/searchkick/results.rb:201:in `results_query'
	from /Users/jeremywoertink/.rvm/gems/ruby-2.2.0@stan/gems/searchkick-1.4.0/lib/searchkick/results.rb:30:in `block in results'
	from /Users/jeremywoertink/.rvm/gems/ruby-2.2.0@stan/gems/searchkick-1.4.0/lib/searchkick/results.rb:29:in `each'
	from /Users/jeremywoertink/.rvm/gems/ruby-2.2.0@stan/gems/searchkick-1.4.0/lib/searchkick/results.rb:29:in `results'
	from (irb):6:in `count'
	from (irb):6
	from /Users/jeremywoertink/.rvm/gems/ruby-2.2.0@stan/gems/railties-4.2.4/lib/rails/commands/console.rb:110:in `start'
	from /Users/jeremywoertink/.rvm/gems/ruby-2.2.0@stan/gems/railties-4.2.4/lib/rails/commands/console.rb:9:in `start'
	from /Users/jeremywoertink/.rvm/gems/ruby-2.2.0@stan/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/jeremywoertink/.rvm/gems/ruby-2.2.0@stan/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/jeremywoertink/.rvm/gems/ruby-2.2.0@stan/gems/railties-4.2.4/lib/rails/commands.rb:17:in `<top (required)>'
	from /Users/jeremywoertink/.rvm/gems/ruby-2.2.0@stan/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
	from /Users/jeremywoertink/.rvm/gems/ruby-2.2.0@stan/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/jeremywoertink/.rvm/gems/ruby-2.2.0@stan/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/jeremywoertink/.rvm/gems/ruby-2.2.0@stan/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
	from /Users/jeremywoertink/Sites/stan/bar/bin/rails:8:in `<top (required)>'
	from /Users/jeremywoertink/.rvm/gems/ruby-2.2.0@stan/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'
	from /Users/jeremywoertink/.rvm/gems/ruby-2.2.0@stan/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `block in load'
	from /Users/jeremywoertink/.rvm/gems/ruby-2.2.0@stan/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/jeremywoertink/.rvm/gems/ruby-2.2.0@stan/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'
	from /Users/jeremywoertink/.rvm/gems/ruby-2.2.0@stan/gems/spring-1.3.6/lib/spring/commands/rails.rb:6:in `call'
	from /Users/jeremywoertink/.rvm/gems/ruby-2.2.0@stan/gems/spring-1.3.6/lib/spring/command_wrapper.rb:38:in `call'
	from /Users/jeremywoertink/.rvm/gems/ruby-2.2.0@stan/gems/spring-1.3.6/lib/spring/application.rb:183:in `block in serve'
	from /Users/jeremywoertink/.rvm/gems/ruby-2.2.0@stan/gems/spring-1.3.6/lib/spring/application.rb:156:in `fork'
	from /Users/jeremywoertink/.rvm/gems/ruby-2.2.0@stan/gems/spring-1.3.6/lib/spring/application.rb:156:in `serve'
	from /Users/jeremywoertink/.rvm/gems/ruby-2.2.0@stan/gems/spring-1.3.6/lib/spring/application.rb:131:in `block in run'
	from /Users/jeremywoertink/.rvm/gems/ruby-2.2.0@stan/gems/spring-1.3.6/lib/spring/application.rb:125:in `loop'
	from /Users/jeremywoertink/.rvm/gems/ruby-2.2.0@stan/gems/spring-1.3.6/lib/spring/application.rb:125:in `run'
	from /Users/jeremywoertink/.rvm/gems/ruby-2.2.0@stan/gems/spring-1.3.6/lib/spring/application/boot.rb:18:in `<top (required)>'
	from /Users/jeremywoertink/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/jeremywoertink/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'2.2.0 :007 > 

```

Looking in to this, on [this file](https://github.com/ankane/searchkick/blob/d5be48ee83bbd2aa09d9f46680c70bfbaf511187/lib/searchkick/results.rb#L190) it's looking for the primary key. I'm using ActiveRecord, but in my case, this table I'm querying is for reporting and does not contain a primary key, so that field is nil.

**Comment by ankane** [comment]
Searchkick currently requires a primary key to match with Elasticsearch's `_id`. You can use `load: false` to only load records from Elasticsearch. If you have ideas for how Searchkick could handle models with a primary key, feel free to post them.

**Comment by jwoertink** [comment]
Cool. Yeah, the table I have is a view from [Scenic](https://github.com/thoughtbot/scenic). I hadn't even thought about the load part. Since there's no primary key, you wouldn't do a `SomeReport.find(id)` anyway. Generally in this case, you're looking for at least 2 or more records. Maybe this is a case where `defined?(ActiveRecord::Base) && !records.respond_to?(:primary_key)` then `raise UnableToLoadObjectsError`? In that sort of case it would become clear that someone would need to use `load: false`.
