### ISSUE TITLE
raise an exception when adding Typhoeus gem

### ISSUE THREAD

**Issue by kevin-jj** [ankane/searchkick#826]
## Environment：

Rails 5.0.1
faraday (0.11.0)
typhoeus (1.1.2)

## Exception:

```ruby
NoMethodError - undefined method `proxy=' for #<Typhoeus::Request:0x007fcca1985c40>:
  faraday (0.11.0) lib/faraday/adapter/typhoeus.rb:94:in `configure_proxy'
  faraday (0.11.0) lib/faraday/adapter/typhoeus.rb:46:in `request'
  faraday (0.11.0) lib/faraday/adapter/typhoeus.rb:22:in `perform_request'
  faraday (0.11.0) lib/faraday/adapter/typhoeus.rb:14:in `call'
  faraday (0.11.0) lib/faraday/rack_builder.rb:139:in `build_response'
  faraday (0.11.0) lib/faraday/connection.rb:377:in `run_request'
  elasticsearch-transport (5.0.1) lib/elasticsearch/transport/transport/http/faraday.rb:23:in `block in perform_request'
  elasticsearch-transport (5.0.1) lib/elasticsearch/transport/transport/base.rb:261:in `perform_request'
  elasticsearch-transport (5.0.1) lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
  elasticsearch-transport (5.0.1) lib/elasticsearch/transport/client.rb:128:in `perform_request'
  elasticsearch-api (5.0.1) lib/elasticsearch/api/actions/bulk.rb:95:in `bulk'
  searchkick (2.1.1) lib/searchkick/indexer.rb:18:in `perform'
  searchkick (2.1.1) lib/searchkick/logging.rb:126:in `perform'
  searchkick (2.1.1) lib/searchkick/indexer.rb:11:in `queue'
  searchkick (2.1.1) lib/searchkick/index.rb:488:in `bulk_delete_helper'
  searchkick (2.1.1) lib/searchkick/index.rb:76:in `remove'
  searchkick (2.1.1) lib/searchkick/logging.rb:43:in `block in remove'
  activesupport (5.0.1) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (5.0.1) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
  activesupport (5.0.1) lib/active_support/notifications.rb:164:in `instrument'
  searchkick (2.1.1) lib/searchkick/logging.rb:42:in `remove'
  searchkick (2.1.1) lib/searchkick/index.rb:117:in `reindex_record'
  searchkick (2.1.1) lib/searchkick/model.rb:125:in `reindex'
  activesupport (5.0.1) lib/active_support/callbacks.rb:382:in `block in make_lambda'
  activesupport (5.0.1) lib/active_support/callbacks.rb:232:in `block in conditional'
  activesupport (5.0.1) lib/active_support/callbacks.rb:456:in `block in call'
  activesupport (5.0.1) lib/active_support/callbacks.rb:456:in `each'
  activesupport (5.0.1) lib/active_support/callbacks.rb:456:in `call'
  activesupport (5.0.1) lib/active_support/callbacks.rb:101:in `__run_callbacks__'
  activesupport (5.0.1) lib/active_support/callbacks.rb:750:in `_run_commit_callbacks'
  activerecord (5.0.1) lib/active_record/transactions.rb:354:in `committed!'
  activerecord (5.0.1) lib/active_record/connection_adapters/abstract/transaction.rb:87:in `commit_records'
  activerecord (5.0.1) lib/active_record/connection_adapters/abstract/transaction.rb:178:in `commit_transaction'
  activerecord (5.0.1) lib/active_record/connection_adapters/abstract/transaction.rb:202:in `within_new_transaction'
  activerecord (5.0.1) lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
  activerecord (5.0.1) lib/active_record/transactions.rb:211:in `transaction'
  activerecord (5.0.1) lib/active_record/transactions.rb:392:in `with_transaction_returning_status'
  activerecord (5.0.1) lib/active_record/transactions.rb:319:in `block in save'
  activerecord (5.0.1) lib/active_record/transactions.rb:334:in `rollback_active_record_state!'
  activerecord (5.0.1) lib/active_record/transactions.rb:318:in `save'
  activerecord (5.0.1) lib/active_record/suppressor.rb:41:in `save'
```

It does not work even if  I require "faraday" and "require "typhoeus/adapters/faraday"

**Comment by ankane** [comment]
Hey @kevin-jj, this looks to be an error between Faraday and Typhoeus rather Searchkick.

**Comment by kevin-jj** [comment]
Hey @ankane.  Documentation shows that "## Add Typhoeus to your Gemfile and it’ll automatically be used",  so why it still raises an exception?

**Comment by ankane** [comment]
Lol, it typically just works. The tests use those same versions together, and they are all green. It looks like something specific to your app is interfering. My guess from the error is it's some type of proxy settings.

**Comment by kevin-jj** [comment]
I just figured out that I should correctly setup Searchkick.client as below. Thanks @ankane 

```ruby
require 'typhoeus'
require 'typhoeus/adapters/faraday'

Searchkick.client = Elasticsearch::Client.new(hosts: ["http://127.0.0.1:9200"], retry_on_failure: true) do|f|
  f.response :logger
  f.adapter  :typhoeus
end

```
